/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
    LinksToJSONTyped,
} from './Links';

/**
 * 
 * @export
 * @interface AssetWriteoff
 */
export interface AssetWriteoff {
    /**
     * 
     * @type {string}
     * @memberof AssetWriteoff
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof AssetWriteoff
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof AssetWriteoff
     */
    amount: number;
    /**
     * 
     * @type {Date}
     * @memberof AssetWriteoff
     */
    date: Date;
    /**
     * Free form key/ value pair
     * @type {{ [key: string]: any; }}
     * @memberof AssetWriteoff
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {Links}
     * @memberof AssetWriteoff
     */
    links: Links;
    /**
     * 
     * @type {Date}
     * @memberof AssetWriteoff
     */
    readonly updated: Date;
    /**
     * 
     * @type {Date}
     * @memberof AssetWriteoff
     */
    readonly created: Date;
}

/**
 * Check if a given object implements the AssetWriteoff interface.
 */
export function instanceOfAssetWriteoff(value: object): value is AssetWriteoff {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function AssetWriteoffFromJSON(json: any): AssetWriteoff {
    return AssetWriteoffFromJSONTyped(json, false);
}

export function AssetWriteoffFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetWriteoff {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'],
        'date': (new Date(json['date'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'links': LinksFromJSON(json['_links']),
        'updated': (new Date(json['updated'])),
        'created': (new Date(json['created'])),
    };
}

export function AssetWriteoffToJSON(json: any): AssetWriteoff {
    return AssetWriteoffToJSONTyped(json, false);
}

export function AssetWriteoffToJSONTyped(value?: Omit<AssetWriteoff, 'id'|'updated'|'created'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'amount': value['amount'],
        'date': ((value['date']).toISOString().substring(0,10)),
        'metadata': value['metadata'],
        '_links': LinksToJSON(value['links']),
    };
}

