/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BuyCreditsRequest
 */
export interface BuyCreditsRequest {
    /**
     * The number of credits to buy
     * @type {number}
     * @memberof BuyCreditsRequest
     */
    credits: number;
}

/**
 * Check if a given object implements the BuyCreditsRequest interface.
 */
export function instanceOfBuyCreditsRequest(value: object): value is BuyCreditsRequest {
    if (!('credits' in value) || value['credits'] === undefined) return false;
    return true;
}

export function BuyCreditsRequestFromJSON(json: any): BuyCreditsRequest {
    return BuyCreditsRequestFromJSONTyped(json, false);
}

export function BuyCreditsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuyCreditsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'credits': json['credits'],
    };
}

export function BuyCreditsRequestToJSON(json: any): BuyCreditsRequest {
    return BuyCreditsRequestToJSONTyped(json, false);
}

export function BuyCreditsRequestToJSONTyped(value?: BuyCreditsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credits': value['credits'],
    };
}

