/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBookkeeperProfileRequestSettingsEmail
 */
export interface CreateBookkeeperProfileRequestSettingsEmail {
    /**
     * The email address to show as the sender of the emails, people can also directly reply to this email.
     * @type {string}
     * @memberof CreateBookkeeperProfileRequestSettingsEmail
     */
    email?: string;
    /**
     * The name to show as the sender of the emails.
     * @type {string}
     * @memberof CreateBookkeeperProfileRequestSettingsEmail
     */
    name?: string;
    /**
     * 
     * @type {any}
     * @memberof CreateBookkeeperProfileRequestSettingsEmail
     */
    smtp?: any | null;
}

/**
 * Check if a given object implements the CreateBookkeeperProfileRequestSettingsEmail interface.
 */
export function instanceOfCreateBookkeeperProfileRequestSettingsEmail(value: object): value is CreateBookkeeperProfileRequestSettingsEmail {
    return true;
}

export function CreateBookkeeperProfileRequestSettingsEmailFromJSON(json: any): CreateBookkeeperProfileRequestSettingsEmail {
    return CreateBookkeeperProfileRequestSettingsEmailFromJSONTyped(json, false);
}

export function CreateBookkeeperProfileRequestSettingsEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBookkeeperProfileRequestSettingsEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'smtp': json['smtp'] == null ? undefined : json['smtp'],
    };
}

export function CreateBookkeeperProfileRequestSettingsEmailToJSON(json: any): CreateBookkeeperProfileRequestSettingsEmail {
    return CreateBookkeeperProfileRequestSettingsEmailToJSONTyped(json, false);
}

export function CreateBookkeeperProfileRequestSettingsEmailToJSONTyped(value?: CreateBookkeeperProfileRequestSettingsEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'smtp': value['smtp'],
    };
}

