/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
    ProfileToJSONTyped,
} from './Profile';

/**
 * 
 * @export
 * @interface GetCreditsAnalytics200ResponseValueInnerEmbedded
 */
export interface GetCreditsAnalytics200ResponseValueInnerEmbedded {
    /**
     * 
     * @type {Profile}
     * @memberof GetCreditsAnalytics200ResponseValueInnerEmbedded
     */
    profile: Profile;
}

/**
 * Check if a given object implements the GetCreditsAnalytics200ResponseValueInnerEmbedded interface.
 */
export function instanceOfGetCreditsAnalytics200ResponseValueInnerEmbedded(value: object): value is GetCreditsAnalytics200ResponseValueInnerEmbedded {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    return true;
}

export function GetCreditsAnalytics200ResponseValueInnerEmbeddedFromJSON(json: any): GetCreditsAnalytics200ResponseValueInnerEmbedded {
    return GetCreditsAnalytics200ResponseValueInnerEmbeddedFromJSONTyped(json, false);
}

export function GetCreditsAnalytics200ResponseValueInnerEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCreditsAnalytics200ResponseValueInnerEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': ProfileFromJSON(json['profile']),
    };
}

export function GetCreditsAnalytics200ResponseValueInnerEmbeddedToJSON(json: any): GetCreditsAnalytics200ResponseValueInnerEmbedded {
    return GetCreditsAnalytics200ResponseValueInnerEmbeddedToJSONTyped(json, false);
}

export function GetCreditsAnalytics200ResponseValueInnerEmbeddedToJSONTyped(value?: GetCreditsAnalytics200ResponseValueInnerEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile': ProfileToJSON(value['profile']),
    };
}

