/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetVATFilings200ResponseDataInnerEmbedded } from './GetVATFilings200ResponseDataInnerEmbedded';
import {
    GetVATFilings200ResponseDataInnerEmbeddedFromJSON,
    GetVATFilings200ResponseDataInnerEmbeddedFromJSONTyped,
    GetVATFilings200ResponseDataInnerEmbeddedToJSON,
    GetVATFilings200ResponseDataInnerEmbeddedToJSONTyped,
} from './GetVATFilings200ResponseDataInnerEmbedded';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
    LinksToJSONTyped,
} from './Links';

/**
 * 
 * @export
 * @interface GetVATFilings200ResponseDataInner
 */
export interface GetVATFilings200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetVATFilings200ResponseDataInner
     */
    readonly id: string;
    /**
     * VAT filing type
     * @type {string}
     * @memberof GetVATFilings200ResponseDataInner
     */
    type?: GetVATFilings200ResponseDataInnerTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof GetVATFilings200ResponseDataInner
     */
    readonly from: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetVATFilings200ResponseDataInner
     */
    readonly to: Date;
    /**
     * 
     * @type {any}
     * @memberof GetVATFilings200ResponseDataInner
     */
    data?: any | null;
    /**
     * Free form key/ value pair
     * @type {{ [key: string]: any; }}
     * @memberof GetVATFilings200ResponseDataInner
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {GetVATFilings200ResponseDataInnerEmbedded}
     * @memberof GetVATFilings200ResponseDataInner
     */
    embedded: GetVATFilings200ResponseDataInnerEmbedded;
    /**
     * 
     * @type {Links}
     * @memberof GetVATFilings200ResponseDataInner
     */
    links: Links;
    /**
     * 
     * @type {Date}
     * @memberof GetVATFilings200ResponseDataInner
     */
    readonly updated: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetVATFilings200ResponseDataInner
     */
    readonly created: Date;
}


/**
 * @export
 */
export const GetVATFilings200ResponseDataInnerTypeEnum = {
    Vat: 'nl_vat',
    Oss: 'nl_oss'
} as const;
export type GetVATFilings200ResponseDataInnerTypeEnum = typeof GetVATFilings200ResponseDataInnerTypeEnum[keyof typeof GetVATFilings200ResponseDataInnerTypeEnum];


/**
 * Check if a given object implements the GetVATFilings200ResponseDataInner interface.
 */
export function instanceOfGetVATFilings200ResponseDataInner(value: object): value is GetVATFilings200ResponseDataInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('embedded' in value) || value['embedded'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function GetVATFilings200ResponseDataInnerFromJSON(json: any): GetVATFilings200ResponseDataInner {
    return GetVATFilings200ResponseDataInnerFromJSONTyped(json, false);
}

export function GetVATFilings200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVATFilings200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'from': (new Date(json['from'])),
        'to': (new Date(json['to'])),
        'data': json['data'] == null ? undefined : json['data'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'embedded': GetVATFilings200ResponseDataInnerEmbeddedFromJSON(json['_embedded']),
        'links': LinksFromJSON(json['_links']),
        'updated': (new Date(json['updated'])),
        'created': (new Date(json['created'])),
    };
}

export function GetVATFilings200ResponseDataInnerToJSON(json: any): GetVATFilings200ResponseDataInner {
    return GetVATFilings200ResponseDataInnerToJSONTyped(json, false);
}

export function GetVATFilings200ResponseDataInnerToJSONTyped(value?: Omit<GetVATFilings200ResponseDataInner, 'id'|'from'|'to'|'updated'|'created'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'data': value['data'],
        'metadata': value['metadata'],
        '_embedded': GetVATFilings200ResponseDataInnerEmbeddedToJSON(value['embedded']),
        '_links': LinksToJSON(value['links']),
    };
}

