/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
    ProfileToJSONTyped,
} from './Profile';

/**
 * 
 * @export
 * @interface GetVATFilings200ResponseDataInnerEmbedded
 */
export interface GetVATFilings200ResponseDataInnerEmbedded {
    /**
     * 
     * @type {Profile}
     * @memberof GetVATFilings200ResponseDataInnerEmbedded
     */
    relation?: Profile;
}

/**
 * Check if a given object implements the GetVATFilings200ResponseDataInnerEmbedded interface.
 */
export function instanceOfGetVATFilings200ResponseDataInnerEmbedded(value: object): value is GetVATFilings200ResponseDataInnerEmbedded {
    return true;
}

export function GetVATFilings200ResponseDataInnerEmbeddedFromJSON(json: any): GetVATFilings200ResponseDataInnerEmbedded {
    return GetVATFilings200ResponseDataInnerEmbeddedFromJSONTyped(json, false);
}

export function GetVATFilings200ResponseDataInnerEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVATFilings200ResponseDataInnerEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'relation': json['relation'] == null ? undefined : ProfileFromJSON(json['relation']),
    };
}

export function GetVATFilings200ResponseDataInnerEmbeddedToJSON(json: any): GetVATFilings200ResponseDataInnerEmbedded {
    return GetVATFilings200ResponseDataInnerEmbeddedToJSONTyped(json, false);
}

export function GetVATFilings200ResponseDataInnerEmbeddedToJSONTyped(value?: GetVATFilings200ResponseDataInnerEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relation': ProfileToJSON(value['relation']),
    };
}

