/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinksValue
 */
export interface LinksValue {
    /**
     * The URL of the resource
     * @type {string}
     * @memberof LinksValue
     */
    href: string;
    /**
     * 
     * @type {string}
     * @memberof LinksValue
     */
    type: string;
}

/**
 * Check if a given object implements the LinksValue interface.
 */
export function instanceOfLinksValue(value: object): value is LinksValue {
    if (!('href' in value) || value['href'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function LinksValueFromJSON(json: any): LinksValue {
    return LinksValueFromJSONTyped(json, false);
}

export function LinksValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinksValue {
    if (json == null) {
        return json;
    }
    return {
        
        'href': json['href'],
        'type': json['type'],
    };
}

export function LinksValueToJSON(json: any): LinksValue {
    return LinksValueToJSONTyped(json, false);
}

export function LinksValueToJSONTyped(value?: LinksValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'href': value['href'],
        'type': value['type'],
    };
}

