/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonetaryAccountPayment } from './MonetaryAccountPayment';
import {
    MonetaryAccountPaymentFromJSON,
    MonetaryAccountPaymentFromJSONTyped,
    MonetaryAccountPaymentToJSON,
    MonetaryAccountPaymentToJSONTyped,
} from './MonetaryAccountPayment';

/**
 * 
 * @export
 * @interface MemorialBatchEmbedded
 */
export interface MemorialBatchEmbedded {
    /**
     * 
     * @type {Array<MonetaryAccountPayment>}
     * @memberof MemorialBatchEmbedded
     */
    payments: Array<MonetaryAccountPayment>;
    /**
     * 
     * @type {MonetaryAccountPayment}
     * @memberof MemorialBatchEmbedded
     */
    initialPayment?: MonetaryAccountPayment;
}

/**
 * Check if a given object implements the MemorialBatchEmbedded interface.
 */
export function instanceOfMemorialBatchEmbedded(value: object): value is MemorialBatchEmbedded {
    if (!('payments' in value) || value['payments'] === undefined) return false;
    return true;
}

export function MemorialBatchEmbeddedFromJSON(json: any): MemorialBatchEmbedded {
    return MemorialBatchEmbeddedFromJSONTyped(json, false);
}

export function MemorialBatchEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemorialBatchEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'payments': ((json['payments'] as Array<any>).map(MonetaryAccountPaymentFromJSON)),
        'initialPayment': json['initial_payment'] == null ? undefined : MonetaryAccountPaymentFromJSON(json['initial_payment']),
    };
}

export function MemorialBatchEmbeddedToJSON(json: any): MemorialBatchEmbedded {
    return MemorialBatchEmbeddedToJSONTyped(json, false);
}

export function MemorialBatchEmbeddedToJSONTyped(value?: MemorialBatchEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payments': ((value['payments'] as Array<any>).map(MonetaryAccountPaymentToJSON)),
        'initial_payment': MonetaryAccountPaymentToJSON(value['initialPayment']),
    };
}

