/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MonetaryAccountPaymentEmbeddedLedger
 */
export interface MonetaryAccountPaymentEmbeddedLedger {
    /**
     * 
     * @type {string}
     * @memberof MonetaryAccountPaymentEmbeddedLedger
     */
    ledger: string;
}

/**
 * Check if a given object implements the MonetaryAccountPaymentEmbeddedLedger interface.
 */
export function instanceOfMonetaryAccountPaymentEmbeddedLedger(value: object): value is MonetaryAccountPaymentEmbeddedLedger {
    if (!('ledger' in value) || value['ledger'] === undefined) return false;
    return true;
}

export function MonetaryAccountPaymentEmbeddedLedgerFromJSON(json: any): MonetaryAccountPaymentEmbeddedLedger {
    return MonetaryAccountPaymentEmbeddedLedgerFromJSONTyped(json, false);
}

export function MonetaryAccountPaymentEmbeddedLedgerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonetaryAccountPaymentEmbeddedLedger {
    if (json == null) {
        return json;
    }
    return {
        
        'ledger': json['ledger'],
    };
}

export function MonetaryAccountPaymentEmbeddedLedgerToJSON(json: any): MonetaryAccountPaymentEmbeddedLedger {
    return MonetaryAccountPaymentEmbeddedLedgerToJSONTyped(json, false);
}

export function MonetaryAccountPaymentEmbeddedLedgerToJSONTyped(value?: MonetaryAccountPaymentEmbeddedLedger | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ledger': value['ledger'],
    };
}

