/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { Language } from './Language';
import {
    LanguageFromJSON,
    LanguageFromJSONTyped,
    LanguageToJSON,
    LanguageToJSONTyped,
} from './Language';
import type { CreateBookkeeperProfileRequestNl } from './CreateBookkeeperProfileRequestNl';
import {
    CreateBookkeeperProfileRequestNlFromJSON,
    CreateBookkeeperProfileRequestNlFromJSONTyped,
    CreateBookkeeperProfileRequestNlToJSON,
    CreateBookkeeperProfileRequestNlToJSONTyped,
} from './CreateBookkeeperProfileRequestNl';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
    LinksToJSONTyped,
} from './Links';
import type { ProfileFeatures } from './ProfileFeatures';
import {
    ProfileFeaturesFromJSON,
    ProfileFeaturesFromJSONTyped,
    ProfileFeaturesToJSON,
    ProfileFeaturesToJSONTyped,
} from './ProfileFeatures';
import type { ProfileSettings } from './ProfileSettings';
import {
    ProfileSettingsFromJSON,
    ProfileSettingsFromJSONTyped,
    ProfileSettingsToJSON,
    ProfileSettingsToJSONTyped,
} from './ProfileSettings';

/**
 * 
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    legalName: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    ledgerChart: string;
    /**
     * 
     * @type {ProfileFeatures}
     * @memberof Profile
     */
    features: ProfileFeatures;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    url: string;
    /**
     * 
     * @type {Language}
     * @memberof Profile
     */
    language: Language;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    registrationNumber: string;
    /**
     * ISO 3166-1 alpha-2 country code
     * @type {string}
     * @memberof Profile
     */
    registrationCountry: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    timezone: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    name: string;
    /**
     * 
     * @type {CreateBookkeeperProfileRequestNl}
     * @memberof Profile
     */
    nl?: CreateBookkeeperProfileRequestNl;
    /**
     * 
     * @type {ProfileSettings}
     * @memberof Profile
     */
    settings?: ProfileSettings;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    distanceUnit: ProfileDistanceUnitEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof Profile
     */
    currencies?: Array<string>;
    /**
     * ISO 3166-1 alpha-2 currency code
     * @type {string}
     * @memberof Profile
     */
    currency: string;
    /**
     * 
     * @type {Address}
     * @memberof Profile
     */
    address: Address;
    /**
     * 
     * @type {Date}
     * @memberof Profile
     */
    readonly updated: Date;
    /**
     * 
     * @type {Date}
     * @memberof Profile
     */
    readonly created: Date;
    /**
     * 
     * @type {Links}
     * @memberof Profile
     */
    links: Links;
    /**
     * Free form key/ value pair
     * @type {{ [key: string]: any; }}
     * @memberof Profile
     */
    metadata?: { [key: string]: any; };
}


/**
 * @export
 */
export const ProfileDistanceUnitEnum = {
    Kilometers: 'kilometers',
    Miles: 'miles'
} as const;
export type ProfileDistanceUnitEnum = typeof ProfileDistanceUnitEnum[keyof typeof ProfileDistanceUnitEnum];


/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): value is Profile {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('legalName' in value) || value['legalName'] === undefined) return false;
    if (!('ledgerChart' in value) || value['ledgerChart'] === undefined) return false;
    if (!('features' in value) || value['features'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('registrationNumber' in value) || value['registrationNumber'] === undefined) return false;
    if (!('registrationCountry' in value) || value['registrationCountry'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('distanceUnit' in value) || value['distanceUnit'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'legalName': json['legal-name'],
        'ledgerChart': json['ledger-chart'],
        'features': ProfileFeaturesFromJSON(json['features']),
        'url': json['url'],
        'language': LanguageFromJSON(json['language']),
        'registrationNumber': json['registration-number'],
        'registrationCountry': json['registration-country'],
        'timezone': json['timezone'],
        'name': json['name'],
        'nl': json['nl'] == null ? undefined : CreateBookkeeperProfileRequestNlFromJSON(json['nl']),
        'settings': json['settings'] == null ? undefined : ProfileSettingsFromJSON(json['settings']),
        'distanceUnit': json['distance-unit'],
        'currencies': json['currencies'] == null ? undefined : json['currencies'],
        'currency': json['currency'],
        'address': AddressFromJSON(json['address']),
        'updated': (new Date(json['updated'])),
        'created': (new Date(json['created'])),
        'links': LinksFromJSON(json['_links']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ProfileToJSON(json: any): Profile {
    return ProfileToJSONTyped(json, false);
}

export function ProfileToJSONTyped(value?: Omit<Profile, 'id'|'updated'|'created'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'legal-name': value['legalName'],
        'ledger-chart': value['ledgerChart'],
        'features': ProfileFeaturesToJSON(value['features']),
        'url': value['url'],
        'language': LanguageToJSON(value['language']),
        'registration-number': value['registrationNumber'],
        'registration-country': value['registrationCountry'],
        'timezone': value['timezone'],
        'name': value['name'],
        'nl': CreateBookkeeperProfileRequestNlToJSON(value['nl']),
        'settings': ProfileSettingsToJSON(value['settings']),
        'distance-unit': value['distanceUnit'],
        'currencies': value['currencies'],
        'currency': value['currency'],
        'address': AddressToJSON(value['address']),
        '_links': LinksToJSON(value['links']),
        'metadata': value['metadata'],
    };
}

