/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileSettingsBranding
 */
export interface ProfileSettingsBranding {
    /**
     * 
     * @type {string}
     * @memberof ProfileSettingsBranding
     */
    logo: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileSettingsBranding
     */
    primary: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileSettingsBranding
     */
    secondary: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileSettingsBranding
     */
    background?: string;
}

/**
 * Check if a given object implements the ProfileSettingsBranding interface.
 */
export function instanceOfProfileSettingsBranding(value: object): value is ProfileSettingsBranding {
    if (!('logo' in value) || value['logo'] === undefined) return false;
    if (!('primary' in value) || value['primary'] === undefined) return false;
    if (!('secondary' in value) || value['secondary'] === undefined) return false;
    return true;
}

export function ProfileSettingsBrandingFromJSON(json: any): ProfileSettingsBranding {
    return ProfileSettingsBrandingFromJSONTyped(json, false);
}

export function ProfileSettingsBrandingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileSettingsBranding {
    if (json == null) {
        return json;
    }
    return {
        
        'logo': json['logo'],
        'primary': json['primary'],
        'secondary': json['secondary'],
        'background': json['background'] == null ? undefined : json['background'],
    };
}

export function ProfileSettingsBrandingToJSON(json: any): ProfileSettingsBranding {
    return ProfileSettingsBrandingToJSONTyped(json, false);
}

export function ProfileSettingsBrandingToJSONTyped(value?: ProfileSettingsBranding | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logo': value['logo'],
        'primary': value['primary'],
        'secondary': value['secondary'],
        'background': value['background'],
    };
}

