/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateBookkeeperProfileRequestSettingsEmail } from './CreateBookkeeperProfileRequestSettingsEmail';
import {
    CreateBookkeeperProfileRequestSettingsEmailFromJSON,
    CreateBookkeeperProfileRequestSettingsEmailFromJSONTyped,
    CreateBookkeeperProfileRequestSettingsEmailToJSON,
    CreateBookkeeperProfileRequestSettingsEmailToJSONTyped,
} from './CreateBookkeeperProfileRequestSettingsEmail';
import type { CreateBookkeeperProfileRequestSettingsPurchaseInvoice } from './CreateBookkeeperProfileRequestSettingsPurchaseInvoice';
import {
    CreateBookkeeperProfileRequestSettingsPurchaseInvoiceFromJSON,
    CreateBookkeeperProfileRequestSettingsPurchaseInvoiceFromJSONTyped,
    CreateBookkeeperProfileRequestSettingsPurchaseInvoiceToJSON,
    CreateBookkeeperProfileRequestSettingsPurchaseInvoiceToJSONTyped,
} from './CreateBookkeeperProfileRequestSettingsPurchaseInvoice';
import type { CreateBookkeeperProfileRequestSettingsSalesInvoice } from './CreateBookkeeperProfileRequestSettingsSalesInvoice';
import {
    CreateBookkeeperProfileRequestSettingsSalesInvoiceFromJSON,
    CreateBookkeeperProfileRequestSettingsSalesInvoiceFromJSONTyped,
    CreateBookkeeperProfileRequestSettingsSalesInvoiceToJSON,
    CreateBookkeeperProfileRequestSettingsSalesInvoiceToJSONTyped,
} from './CreateBookkeeperProfileRequestSettingsSalesInvoice';
import type { ProfileSettingsBranding } from './ProfileSettingsBranding';
import {
    ProfileSettingsBrandingFromJSON,
    ProfileSettingsBrandingFromJSONTyped,
    ProfileSettingsBrandingToJSON,
    ProfileSettingsBrandingToJSONTyped,
} from './ProfileSettingsBranding';

/**
 * 
 * @export
 * @interface ProfileSettings
 */
export interface ProfileSettings {
    /**
     * 
     * @type {CreateBookkeeperProfileRequestSettingsEmail}
     * @memberof ProfileSettings
     */
    email?: CreateBookkeeperProfileRequestSettingsEmail;
    /**
     * 
     * @type {CreateBookkeeperProfileRequestSettingsSalesInvoice}
     * @memberof ProfileSettings
     */
    salesInvoice?: CreateBookkeeperProfileRequestSettingsSalesInvoice;
    /**
     * 
     * @type {CreateBookkeeperProfileRequestSettingsPurchaseInvoice}
     * @memberof ProfileSettings
     */
    purchaseInvoice?: CreateBookkeeperProfileRequestSettingsPurchaseInvoice;
    /**
     * 
     * @type {ProfileSettingsBranding}
     * @memberof ProfileSettings
     */
    branding?: ProfileSettingsBranding;
}

/**
 * Check if a given object implements the ProfileSettings interface.
 */
export function instanceOfProfileSettings(value: object): value is ProfileSettings {
    return true;
}

export function ProfileSettingsFromJSON(json: any): ProfileSettings {
    return ProfileSettingsFromJSONTyped(json, false);
}

export function ProfileSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : CreateBookkeeperProfileRequestSettingsEmailFromJSON(json['email']),
        'salesInvoice': json['sales_invoice'] == null ? undefined : CreateBookkeeperProfileRequestSettingsSalesInvoiceFromJSON(json['sales_invoice']),
        'purchaseInvoice': json['purchase_invoice'] == null ? undefined : CreateBookkeeperProfileRequestSettingsPurchaseInvoiceFromJSON(json['purchase_invoice']),
        'branding': json['branding'] == null ? undefined : ProfileSettingsBrandingFromJSON(json['branding']),
    };
}

export function ProfileSettingsToJSON(json: any): ProfileSettings {
    return ProfileSettingsToJSONTyped(json, false);
}

export function ProfileSettingsToJSONTyped(value?: ProfileSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': CreateBookkeeperProfileRequestSettingsEmailToJSON(value['email']),
        'sales_invoice': CreateBookkeeperProfileRequestSettingsSalesInvoiceToJSON(value['salesInvoice']),
        'purchase_invoice': CreateBookkeeperProfileRequestSettingsPurchaseInvoiceToJSON(value['purchaseInvoice']),
        'branding': ProfileSettingsBrandingToJSON(value['branding']),
    };
}

