/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelationBankIban } from './RelationBankIban';
import {
    RelationBankIbanFromJSON,
    RelationBankIbanFromJSONTyped,
    RelationBankIbanToJSON,
    RelationBankIbanToJSONTyped,
} from './RelationBankIban';

/**
 * 
 * @export
 * @interface RelationBank
 */
export interface RelationBank {
    /**
     * 
     * @type {RelationBankIban}
     * @memberof RelationBank
     */
    iban?: RelationBankIban;
}

/**
 * Check if a given object implements the RelationBank interface.
 */
export function instanceOfRelationBank(value: object): value is RelationBank {
    return true;
}

export function RelationBankFromJSON(json: any): RelationBank {
    return RelationBankFromJSONTyped(json, false);
}

export function RelationBankFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationBank {
    if (json == null) {
        return json;
    }
    return {
        
        'iban': json['iban'] == null ? undefined : RelationBankIbanFromJSON(json['iban']),
    };
}

export function RelationBankToJSON(json: any): RelationBank {
    return RelationBankToJSONTyped(json, false);
}

export function RelationBankToJSONTyped(value?: RelationBank | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iban': RelationBankIbanToJSON(value['iban']),
    };
}

