/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SalesInvoiceAmountsBooked } from './SalesInvoiceAmountsBooked';
import {
    SalesInvoiceAmountsBookedFromJSON,
    SalesInvoiceAmountsBookedFromJSONTyped,
    SalesInvoiceAmountsBookedToJSON,
    SalesInvoiceAmountsBookedToJSONTyped,
} from './SalesInvoiceAmountsBooked';

/**
 * 
 * @export
 * @interface SalesInvoiceAmounts
 */
export interface SalesInvoiceAmounts {
    /**
     * 
     * @type {SalesInvoiceAmountsBooked}
     * @memberof SalesInvoiceAmounts
     */
    booked: SalesInvoiceAmountsBooked;
    /**
     * 
     * @type {number}
     * @memberof SalesInvoiceAmounts
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof SalesInvoiceAmounts
     */
    subTotal: number;
    /**
     * 
     * @type {number}
     * @memberof SalesInvoiceAmounts
     */
    tax: number;
    /**
     * 
     * @type {number}
     * @memberof SalesInvoiceAmounts
     */
    discount: number;
    /**
     * 
     * @type {number}
     * @memberof SalesInvoiceAmounts
     */
    payments: number;
}

/**
 * Check if a given object implements the SalesInvoiceAmounts interface.
 */
export function instanceOfSalesInvoiceAmounts(value: object): value is SalesInvoiceAmounts {
    if (!('booked' in value) || value['booked'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('subTotal' in value) || value['subTotal'] === undefined) return false;
    if (!('tax' in value) || value['tax'] === undefined) return false;
    if (!('discount' in value) || value['discount'] === undefined) return false;
    if (!('payments' in value) || value['payments'] === undefined) return false;
    return true;
}

export function SalesInvoiceAmountsFromJSON(json: any): SalesInvoiceAmounts {
    return SalesInvoiceAmountsFromJSONTyped(json, false);
}

export function SalesInvoiceAmountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesInvoiceAmounts {
    if (json == null) {
        return json;
    }
    return {
        
        'booked': SalesInvoiceAmountsBookedFromJSON(json['booked']),
        'total': json['total'],
        'subTotal': json['sub-total'],
        'tax': json['tax'],
        'discount': json['discount'],
        'payments': json['payments'],
    };
}

export function SalesInvoiceAmountsToJSON(json: any): SalesInvoiceAmounts {
    return SalesInvoiceAmountsToJSONTyped(json, false);
}

export function SalesInvoiceAmountsToJSONTyped(value?: SalesInvoiceAmounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'booked': SalesInvoiceAmountsBookedToJSON(value['booked']),
        'total': value['total'],
        'sub-total': value['subTotal'],
        'tax': value['tax'],
        'discount': value['discount'],
        'payments': value['payments'],
    };
}

