/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SalesInvoiceAmountsBooked
 */
export interface SalesInvoiceAmountsBooked {
    /**
     * 
     * @type {number}
     * @memberof SalesInvoiceAmountsBooked
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof SalesInvoiceAmountsBooked
     */
    subTotal: number;
    /**
     * 
     * @type {number}
     * @memberof SalesInvoiceAmountsBooked
     */
    tax: number;
    /**
     * 
     * @type {number}
     * @memberof SalesInvoiceAmountsBooked
     */
    discount: number;
    /**
     * 
     * @type {number}
     * @memberof SalesInvoiceAmountsBooked
     */
    payments: number;
}

/**
 * Check if a given object implements the SalesInvoiceAmountsBooked interface.
 */
export function instanceOfSalesInvoiceAmountsBooked(value: object): value is SalesInvoiceAmountsBooked {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('subTotal' in value) || value['subTotal'] === undefined) return false;
    if (!('tax' in value) || value['tax'] === undefined) return false;
    if (!('discount' in value) || value['discount'] === undefined) return false;
    if (!('payments' in value) || value['payments'] === undefined) return false;
    return true;
}

export function SalesInvoiceAmountsBookedFromJSON(json: any): SalesInvoiceAmountsBooked {
    return SalesInvoiceAmountsBookedFromJSONTyped(json, false);
}

export function SalesInvoiceAmountsBookedFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesInvoiceAmountsBooked {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'subTotal': json['sub-total'],
        'tax': json['tax'],
        'discount': json['discount'],
        'payments': json['payments'],
    };
}

export function SalesInvoiceAmountsBookedToJSON(json: any): SalesInvoiceAmountsBooked {
    return SalesInvoiceAmountsBookedToJSONTyped(json, false);
}

export function SalesInvoiceAmountsBookedToJSONTyped(value?: SalesInvoiceAmountsBooked | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'sub-total': value['subTotal'],
        'tax': value['tax'],
        'discount': value['discount'],
        'payments': value['payments'],
    };
}

