/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze bookkeepers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SalesInvoice } from './SalesInvoice';
import {
    SalesInvoiceFromJSON,
    SalesInvoiceFromJSONTyped,
    SalesInvoiceToJSON,
    SalesInvoiceToJSONTyped,
} from './SalesInvoice';
import type { Relation } from './Relation';
import {
    RelationFromJSON,
    RelationFromJSONTyped,
    RelationToJSON,
    RelationToJSONTyped,
} from './Relation';
import type { SalesInvoiceLine } from './SalesInvoiceLine';
import {
    SalesInvoiceLineFromJSON,
    SalesInvoiceLineFromJSONTyped,
    SalesInvoiceLineToJSON,
    SalesInvoiceLineToJSONTyped,
} from './SalesInvoiceLine';
import type { MonetaryAccountPayment } from './MonetaryAccountPayment';
import {
    MonetaryAccountPaymentFromJSON,
    MonetaryAccountPaymentFromJSONTyped,
    MonetaryAccountPaymentToJSON,
    MonetaryAccountPaymentToJSONTyped,
} from './MonetaryAccountPayment';
import type { Subscription } from './Subscription';
import {
    SubscriptionFromJSON,
    SubscriptionFromJSONTyped,
    SubscriptionToJSON,
    SubscriptionToJSONTyped,
} from './Subscription';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
    ProfileToJSONTyped,
} from './Profile';

/**
 * 
 * @export
 * @interface SalesInvoiceEmbedded
 */
export interface SalesInvoiceEmbedded {
    /**
     * 
     * @type {Profile}
     * @memberof SalesInvoiceEmbedded
     */
    profile: Profile;
    /**
     * 
     * @type {Array<SalesInvoiceLine>}
     * @memberof SalesInvoiceEmbedded
     */
    lines: Array<SalesInvoiceLine>;
    /**
     * 
     * @type {SalesInvoice}
     * @memberof SalesInvoiceEmbedded
     */
    initialInvoice?: SalesInvoice;
    /**
     * 
     * @type {Array<SalesInvoice>}
     * @memberof SalesInvoiceEmbedded
     */
    attachedInvoices: Array<SalesInvoice>;
    /**
     * 
     * @type {Subscription}
     * @memberof SalesInvoiceEmbedded
     */
    subscription?: Subscription;
    /**
     * 
     * @type {Relation}
     * @memberof SalesInvoiceEmbedded
     */
    relation?: Relation;
    /**
     * 
     * @type {Array<MonetaryAccountPayment>}
     * @memberof SalesInvoiceEmbedded
     */
    payments: Array<MonetaryAccountPayment>;
}

/**
 * Check if a given object implements the SalesInvoiceEmbedded interface.
 */
export function instanceOfSalesInvoiceEmbedded(value: object): value is SalesInvoiceEmbedded {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('lines' in value) || value['lines'] === undefined) return false;
    if (!('attachedInvoices' in value) || value['attachedInvoices'] === undefined) return false;
    if (!('payments' in value) || value['payments'] === undefined) return false;
    return true;
}

export function SalesInvoiceEmbeddedFromJSON(json: any): SalesInvoiceEmbedded {
    return SalesInvoiceEmbeddedFromJSONTyped(json, false);
}

export function SalesInvoiceEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesInvoiceEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': ProfileFromJSON(json['profile']),
        'lines': ((json['lines'] as Array<any>).map(SalesInvoiceLineFromJSON)),
        'initialInvoice': json['initial-invoice'] == null ? undefined : SalesInvoiceFromJSON(json['initial-invoice']),
        'attachedInvoices': ((json['attached-invoices'] as Array<any>).map(SalesInvoiceFromJSON)),
        'subscription': json['subscription'] == null ? undefined : SubscriptionFromJSON(json['subscription']),
        'relation': json['relation'] == null ? undefined : RelationFromJSON(json['relation']),
        'payments': ((json['payments'] as Array<any>).map(MonetaryAccountPaymentFromJSON)),
    };
}

export function SalesInvoiceEmbeddedToJSON(json: any): SalesInvoiceEmbedded {
    return SalesInvoiceEmbeddedToJSONTyped(json, false);
}

export function SalesInvoiceEmbeddedToJSONTyped(value?: SalesInvoiceEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile': ProfileToJSON(value['profile']),
        'lines': ((value['lines'] as Array<any>).map(SalesInvoiceLineToJSON)),
        'initial-invoice': SalesInvoiceToJSON(value['initialInvoice']),
        'attached-invoices': ((value['attachedInvoices'] as Array<any>).map(SalesInvoiceToJSON)),
        'subscription': SubscriptionToJSON(value['subscription']),
        'relation': RelationToJSON(value['relation']),
        'payments': ((value['payments'] as Array<any>).map(MonetaryAccountPaymentToJSON)),
    };
}

