/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateReminderPublicPayment200ResponseSepaTransfer } from './CreateReminderPublicPayment200ResponseSepaTransfer';
import {
    CreateReminderPublicPayment200ResponseSepaTransferFromJSON,
    CreateReminderPublicPayment200ResponseSepaTransferFromJSONTyped,
    CreateReminderPublicPayment200ResponseSepaTransferToJSON,
    CreateReminderPublicPayment200ResponseSepaTransferToJSONTyped,
} from './CreateReminderPublicPayment200ResponseSepaTransfer';

/**
 * 
 * @export
 * @interface CreateReminderPublicPayment200Response
 */
export interface CreateReminderPublicPayment200Response {
    /**
     * 
     * @type {string}
     * @memberof CreateReminderPublicPayment200Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReminderPublicPayment200Response
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReminderPublicPayment200Response
     */
    state: CreateReminderPublicPayment200ResponseStateEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateReminderPublicPayment200Response
     */
    redirect?: string;
    /**
     * 
     * @type {CreateReminderPublicPayment200ResponseSepaTransfer}
     * @memberof CreateReminderPublicPayment200Response
     */
    sepaTransfer?: CreateReminderPublicPayment200ResponseSepaTransfer;
}


/**
 * @export
 */
export const CreateReminderPublicPayment200ResponseStateEnum = {
    Created: 'created',
    Processing: 'processing',
    Succeeded: 'succeeded',
    Failed: 'failed'
} as const;
export type CreateReminderPublicPayment200ResponseStateEnum = typeof CreateReminderPublicPayment200ResponseStateEnum[keyof typeof CreateReminderPublicPayment200ResponseStateEnum];


/**
 * Check if a given object implements the CreateReminderPublicPayment200Response interface.
 */
export function instanceOfCreateReminderPublicPayment200Response(value: object): value is CreateReminderPublicPayment200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function CreateReminderPublicPayment200ResponseFromJSON(json: any): CreateReminderPublicPayment200Response {
    return CreateReminderPublicPayment200ResponseFromJSONTyped(json, false);
}

export function CreateReminderPublicPayment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReminderPublicPayment200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'externalId': json['external_id'],
        'state': json['state'],
        'redirect': json['redirect'] == null ? undefined : json['redirect'],
        'sepaTransfer': json['sepa_transfer'] == null ? undefined : CreateReminderPublicPayment200ResponseSepaTransferFromJSON(json['sepa_transfer']),
    };
}

export function CreateReminderPublicPayment200ResponseToJSON(json: any): CreateReminderPublicPayment200Response {
    return CreateReminderPublicPayment200ResponseToJSONTyped(json, false);
}

export function CreateReminderPublicPayment200ResponseToJSONTyped(value?: CreateReminderPublicPayment200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'external_id': value['externalId'],
        'state': value['state'],
        'redirect': value['redirect'],
        'sepa_transfer': CreateReminderPublicPayment200ResponseSepaTransferToJSON(value['sepaTransfer']),
    };
}

