/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDeviceRequest
 */
export interface CreateDeviceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateDeviceRequest
     */
    pushToken?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeviceRequest
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeviceRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeviceRequest
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeviceRequest
     */
    os: CreateDeviceRequestOsEnum;
}


/**
 * @export
 */
export const CreateDeviceRequestOsEnum = {
    Ios: 'ios',
    Android: 'android',
    Web: 'web',
    Visionos: 'visionos'
} as const;
export type CreateDeviceRequestOsEnum = typeof CreateDeviceRequestOsEnum[keyof typeof CreateDeviceRequestOsEnum];


/**
 * Check if a given object implements the CreateDeviceRequest interface.
 */
export function instanceOfCreateDeviceRequest(value: object): value is CreateDeviceRequest {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('os' in value) || value['os'] === undefined) return false;
    return true;
}

export function CreateDeviceRequestFromJSON(json: any): CreateDeviceRequest {
    return CreateDeviceRequestFromJSONTyped(json, false);
}

export function CreateDeviceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeviceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pushToken': json['push_token'] == null ? undefined : json['push_token'],
        'uuid': json['uuid'],
        'name': json['name'],
        'model': json['model'],
        'os': json['os'],
    };
}

export function CreateDeviceRequestToJSON(json: any): CreateDeviceRequest {
    return CreateDeviceRequestToJSONTyped(json, false);
}

export function CreateDeviceRequestToJSONTyped(value?: CreateDeviceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'push_token': value['pushToken'],
        'uuid': value['uuid'],
        'name': value['name'],
        'model': value['model'],
        'os': value['os'],
    };
}

