/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateSubscriptionPublicPaymentMethodRequestData } from './CreateSubscriptionPublicPaymentMethodRequestData';
import {
    CreateSubscriptionPublicPaymentMethodRequestDataFromJSON,
    CreateSubscriptionPublicPaymentMethodRequestDataFromJSONTyped,
    CreateSubscriptionPublicPaymentMethodRequestDataToJSON,
    CreateSubscriptionPublicPaymentMethodRequestDataToJSONTyped,
} from './CreateSubscriptionPublicPaymentMethodRequestData';

/**
 * 
 * @export
 * @interface CreateSubscriptionPublicPaymentMethodRequest
 */
export interface CreateSubscriptionPublicPaymentMethodRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSubscriptionPublicPaymentMethodRequest
     */
    method: CreateSubscriptionPublicPaymentMethodRequestMethodEnum;
    /**
     * 
     * @type {CreateSubscriptionPublicPaymentMethodRequestData}
     * @memberof CreateSubscriptionPublicPaymentMethodRequest
     */
    data: CreateSubscriptionPublicPaymentMethodRequestData;
}


/**
 * @export
 */
export const CreateSubscriptionPublicPaymentMethodRequestMethodEnum = {
    Openbanking: 'openbanking',
    CreditCard: 'credit_card'
} as const;
export type CreateSubscriptionPublicPaymentMethodRequestMethodEnum = typeof CreateSubscriptionPublicPaymentMethodRequestMethodEnum[keyof typeof CreateSubscriptionPublicPaymentMethodRequestMethodEnum];


/**
 * Check if a given object implements the CreateSubscriptionPublicPaymentMethodRequest interface.
 */
export function instanceOfCreateSubscriptionPublicPaymentMethodRequest(value: object): value is CreateSubscriptionPublicPaymentMethodRequest {
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateSubscriptionPublicPaymentMethodRequestFromJSON(json: any): CreateSubscriptionPublicPaymentMethodRequest {
    return CreateSubscriptionPublicPaymentMethodRequestFromJSONTyped(json, false);
}

export function CreateSubscriptionPublicPaymentMethodRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubscriptionPublicPaymentMethodRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'method': json['method'],
        'data': CreateSubscriptionPublicPaymentMethodRequestDataFromJSON(json['data']),
    };
}

export function CreateSubscriptionPublicPaymentMethodRequestToJSON(json: any): CreateSubscriptionPublicPaymentMethodRequest {
    return CreateSubscriptionPublicPaymentMethodRequestToJSONTyped(json, false);
}

export function CreateSubscriptionPublicPaymentMethodRequestToJSONTyped(value?: CreateSubscriptionPublicPaymentMethodRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'method': value['method'],
        'data': CreateSubscriptionPublicPaymentMethodRequestDataToJSON(value['data']),
    };
}

