/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateSubscriptionPublicPaymentMethodRequestData } from './CreateSubscriptionPublicPaymentMethodRequestData';
import {
    CreateSubscriptionPublicPaymentMethodRequestDataFromJSON,
    CreateSubscriptionPublicPaymentMethodRequestDataFromJSONTyped,
    CreateSubscriptionPublicPaymentMethodRequestDataToJSON,
    CreateSubscriptionPublicPaymentMethodRequestDataToJSONTyped,
} from './CreateSubscriptionPublicPaymentMethodRequestData';

/**
 * 
 * @export
 * @interface CreateReminderPublicPaymentRequest
 */
export interface CreateReminderPublicPaymentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateReminderPublicPaymentRequest
     */
    method: CreateReminderPublicPaymentRequestMethodEnum;
    /**
     * 
     * @type {CreateSubscriptionPublicPaymentMethodRequestData}
     * @memberof CreateReminderPublicPaymentRequest
     */
    data: CreateSubscriptionPublicPaymentMethodRequestData;
}


/**
 * @export
 */
export const CreateReminderPublicPaymentRequestMethodEnum = {
    Openbanking: 'openbanking',
    CreditCard: 'credit_card',
    SepaCredit: 'sepa_credit'
} as const;
export type CreateReminderPublicPaymentRequestMethodEnum = typeof CreateReminderPublicPaymentRequestMethodEnum[keyof typeof CreateReminderPublicPaymentRequestMethodEnum];


/**
 * Check if a given object implements the CreateReminderPublicPaymentRequest interface.
 */
export function instanceOfCreateReminderPublicPaymentRequest(value: object): value is CreateReminderPublicPaymentRequest {
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateReminderPublicPaymentRequestFromJSON(json: any): CreateReminderPublicPaymentRequest {
    return CreateReminderPublicPaymentRequestFromJSONTyped(json, false);
}

export function CreateReminderPublicPaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReminderPublicPaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'method': json['method'],
        'data': CreateSubscriptionPublicPaymentMethodRequestDataFromJSON(json['data']),
    };
}

export function CreateReminderPublicPaymentRequestToJSON(json: any): CreateReminderPublicPaymentRequest {
    return CreateReminderPublicPaymentRequestToJSONTyped(json, false);
}

export function CreateReminderPublicPaymentRequestToJSONTyped(value?: CreateReminderPublicPaymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'method': value['method'],
        'data': CreateSubscriptionPublicPaymentMethodRequestDataToJSON(value['data']),
    };
}

