/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAccount200ResponseToken
 */
export interface CreateAccount200ResponseToken {
    /**
     * 
     * @type {string}
     * @memberof CreateAccount200ResponseToken
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAccount200ResponseToken
     */
    refreshToken?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateAccount200ResponseToken
     */
    expiresIn: number;
    /**
     * 
     * @type {string}
     * @memberof CreateAccount200ResponseToken
     */
    tokenType?: CreateAccount200ResponseTokenTokenTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateAccount200ResponseToken
     */
    scope?: string;
}


/**
 * @export
 */
export const CreateAccount200ResponseTokenTokenTypeEnum = {
    Bearer: 'Bearer'
} as const;
export type CreateAccount200ResponseTokenTokenTypeEnum = typeof CreateAccount200ResponseTokenTokenTypeEnum[keyof typeof CreateAccount200ResponseTokenTokenTypeEnum];


/**
 * Check if a given object implements the CreateAccount200ResponseToken interface.
 */
export function instanceOfCreateAccount200ResponseToken(value: object): value is CreateAccount200ResponseToken {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function CreateAccount200ResponseTokenFromJSON(json: any): CreateAccount200ResponseToken {
    return CreateAccount200ResponseTokenFromJSONTyped(json, false);
}

export function CreateAccount200ResponseTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccount200ResponseToken {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'expiresIn': json['expires_in'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'scope': json['scope'] == null ? undefined : json['scope'],
    };
}

export function CreateAccount200ResponseTokenToJSON(json: any): CreateAccount200ResponseToken {
    return CreateAccount200ResponseTokenToJSONTyped(json, false);
}

export function CreateAccount200ResponseTokenToJSONTyped(value?: CreateAccount200ResponseToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'refresh_token': value['refreshToken'],
        'expires_in': value['expiresIn'],
        'token_type': value['tokenType'],
        'scope': value['scope'],
    };
}

