/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';
import type { CreateAccount200ResponseToken } from './CreateAccount200ResponseToken';
import {
    CreateAccount200ResponseTokenFromJSON,
    CreateAccount200ResponseTokenFromJSONTyped,
    CreateAccount200ResponseTokenToJSON,
    CreateAccount200ResponseTokenToJSONTyped,
} from './CreateAccount200ResponseToken';

/**
 * 
 * @export
 * @interface CreateAccount200Response
 */
export interface CreateAccount200Response {
    /**
     * 
     * @type {Account}
     * @memberof CreateAccount200Response
     */
    account: Account;
    /**
     * 
     * @type {CreateAccount200ResponseToken}
     * @memberof CreateAccount200Response
     */
    token?: CreateAccount200ResponseToken;
}

/**
 * Check if a given object implements the CreateAccount200Response interface.
 */
export function instanceOfCreateAccount200Response(value: object): value is CreateAccount200Response {
    if (!('account' in value) || value['account'] === undefined) return false;
    return true;
}

export function CreateAccount200ResponseFromJSON(json: any): CreateAccount200Response {
    return CreateAccount200ResponseFromJSONTyped(json, false);
}

export function CreateAccount200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccount200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'account': AccountFromJSON(json['account']),
        'token': json['token'] == null ? undefined : CreateAccount200ResponseTokenFromJSON(json['token']),
    };
}

export function CreateAccount200ResponseToJSON(json: any): CreateAccount200Response {
    return CreateAccount200ResponseToJSONTyped(json, false);
}

export function CreateAccount200ResponseToJSONTyped(value?: CreateAccount200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': AccountToJSON(value['account']),
        'token': CreateAccount200ResponseTokenToJSON(value['token']),
    };
}

