/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSalesInvoicePublicPayment200Response
 */
export interface CreateSalesInvoicePublicPayment200Response {
    /**
     * 
     * @type {string}
     * @memberof CreateSalesInvoicePublicPayment200Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSalesInvoicePublicPayment200Response
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSalesInvoicePublicPayment200Response
     */
    state: CreateSalesInvoicePublicPayment200ResponseStateEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateSalesInvoicePublicPayment200Response
     */
    redirect?: string;
}


/**
 * @export
 */
export const CreateSalesInvoicePublicPayment200ResponseStateEnum = {
    Created: 'created',
    Processing: 'processing',
    Succeeded: 'succeeded',
    Failed: 'failed'
} as const;
export type CreateSalesInvoicePublicPayment200ResponseStateEnum = typeof CreateSalesInvoicePublicPayment200ResponseStateEnum[keyof typeof CreateSalesInvoicePublicPayment200ResponseStateEnum];


/**
 * Check if a given object implements the CreateSalesInvoicePublicPayment200Response interface.
 */
export function instanceOfCreateSalesInvoicePublicPayment200Response(value: object): value is CreateSalesInvoicePublicPayment200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function CreateSalesInvoicePublicPayment200ResponseFromJSON(json: any): CreateSalesInvoicePublicPayment200Response {
    return CreateSalesInvoicePublicPayment200ResponseFromJSONTyped(json, false);
}

export function CreateSalesInvoicePublicPayment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSalesInvoicePublicPayment200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'externalId': json['external_id'],
        'state': json['state'],
        'redirect': json['redirect'] == null ? undefined : json['redirect'],
    };
}

export function CreateSalesInvoicePublicPayment200ResponseToJSON(json: any): CreateSalesInvoicePublicPayment200Response {
    return CreateSalesInvoicePublicPayment200ResponseToJSONTyped(json, false);
}

export function CreateSalesInvoicePublicPayment200ResponseToJSONTyped(value?: CreateSalesInvoicePublicPayment200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'external_id': value['externalId'],
        'state': value['state'],
        'redirect': value['redirect'],
    };
}

