/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSalesInvoicePublicPaymentRequestDataOpenbanking
 */
export interface CreateSalesInvoicePublicPaymentRequestDataOpenbanking {
    /**
     * 
     * @type {string}
     * @memberof CreateSalesInvoicePublicPaymentRequestDataOpenbanking
     */
    bic: string;
}

/**
 * Check if a given object implements the CreateSalesInvoicePublicPaymentRequestDataOpenbanking interface.
 */
export function instanceOfCreateSalesInvoicePublicPaymentRequestDataOpenbanking(value: object): value is CreateSalesInvoicePublicPaymentRequestDataOpenbanking {
    if (!('bic' in value) || value['bic'] === undefined) return false;
    return true;
}

export function CreateSalesInvoicePublicPaymentRequestDataOpenbankingFromJSON(json: any): CreateSalesInvoicePublicPaymentRequestDataOpenbanking {
    return CreateSalesInvoicePublicPaymentRequestDataOpenbankingFromJSONTyped(json, false);
}

export function CreateSalesInvoicePublicPaymentRequestDataOpenbankingFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSalesInvoicePublicPaymentRequestDataOpenbanking {
    if (json == null) {
        return json;
    }
    return {
        
        'bic': json['bic'],
    };
}

export function CreateSalesInvoicePublicPaymentRequestDataOpenbankingToJSON(json: any): CreateSalesInvoicePublicPaymentRequestDataOpenbanking {
    return CreateSalesInvoicePublicPaymentRequestDataOpenbankingToJSONTyped(json, false);
}

export function CreateSalesInvoicePublicPaymentRequestDataOpenbankingToJSONTyped(value?: CreateSalesInvoicePublicPaymentRequestDataOpenbanking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bic': value['bic'],
    };
}

