/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { GetCompaniesAutocomplete200ResponseDataInnerEu } from './GetCompaniesAutocomplete200ResponseDataInnerEu';
import {
    GetCompaniesAutocomplete200ResponseDataInnerEuFromJSON,
    GetCompaniesAutocomplete200ResponseDataInnerEuFromJSONTyped,
    GetCompaniesAutocomplete200ResponseDataInnerEuToJSON,
    GetCompaniesAutocomplete200ResponseDataInnerEuToJSONTyped,
} from './GetCompaniesAutocomplete200ResponseDataInnerEu';

/**
 * 
 * @export
 * @interface GetCompaniesAutocomplete200ResponseDataInner
 */
export interface GetCompaniesAutocomplete200ResponseDataInner {
    /**
     * Display name based on the legal name, first, middle, and last name
     * @type {string}
     * @memberof GetCompaniesAutocomplete200ResponseDataInner
     */
    readonly name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCompaniesAutocomplete200ResponseDataInner
     */
    legalName?: string;
    /**
     * Registered number of the company
     * @type {string}
     * @memberof GetCompaniesAutocomplete200ResponseDataInner
     */
    registrationNumber?: string;
    /**
     * ISO 3166-1 alpha-2 country code
     * @type {string}
     * @memberof GetCompaniesAutocomplete200ResponseDataInner
     */
    registrationCountry?: string;
    /**
     * 
     * @type {GetCompaniesAutocomplete200ResponseDataInnerEu}
     * @memberof GetCompaniesAutocomplete200ResponseDataInner
     */
    eu?: GetCompaniesAutocomplete200ResponseDataInnerEu;
    /**
     * 
     * @type {Address}
     * @memberof GetCompaniesAutocomplete200ResponseDataInner
     */
    address?: Address;
}

/**
 * Check if a given object implements the GetCompaniesAutocomplete200ResponseDataInner interface.
 */
export function instanceOfGetCompaniesAutocomplete200ResponseDataInner(value: object): value is GetCompaniesAutocomplete200ResponseDataInner {
    return true;
}

export function GetCompaniesAutocomplete200ResponseDataInnerFromJSON(json: any): GetCompaniesAutocomplete200ResponseDataInner {
    return GetCompaniesAutocomplete200ResponseDataInnerFromJSONTyped(json, false);
}

export function GetCompaniesAutocomplete200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCompaniesAutocomplete200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'legalName': json['legal_name'] == null ? undefined : json['legal_name'],
        'registrationNumber': json['registration_number'] == null ? undefined : json['registration_number'],
        'registrationCountry': json['registration_country'] == null ? undefined : json['registration_country'],
        'eu': json['eu'] == null ? undefined : GetCompaniesAutocomplete200ResponseDataInnerEuFromJSON(json['eu']),
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
    };
}

export function GetCompaniesAutocomplete200ResponseDataInnerToJSON(json: any): GetCompaniesAutocomplete200ResponseDataInner {
    return GetCompaniesAutocomplete200ResponseDataInnerToJSONTyped(json, false);
}

export function GetCompaniesAutocomplete200ResponseDataInnerToJSONTyped(value?: Omit<GetCompaniesAutocomplete200ResponseDataInner, 'name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'legal_name': value['legalName'],
        'registration_number': value['registrationNumber'],
        'registration_country': value['registrationCountry'],
        'eu': GetCompaniesAutocomplete200ResponseDataInnerEuToJSON(value['eu']),
        'address': AddressToJSON(value['address']),
    };
}

