/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetRelationPublic200ResponseEu } from './GetRelationPublic200ResponseEu';
import {
    GetRelationPublic200ResponseEuFromJSON,
    GetRelationPublic200ResponseEuFromJSONTyped,
    GetRelationPublic200ResponseEuToJSON,
    GetRelationPublic200ResponseEuToJSONTyped,
} from './GetRelationPublic200ResponseEu';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { Language } from './Language';
import {
    LanguageFromJSON,
    LanguageFromJSONTyped,
    LanguageToJSON,
    LanguageToJSONTyped,
} from './Language';
import type { GetRelationPublic200ResponseEmbedded } from './GetRelationPublic200ResponseEmbedded';
import {
    GetRelationPublic200ResponseEmbeddedFromJSON,
    GetRelationPublic200ResponseEmbeddedFromJSONTyped,
    GetRelationPublic200ResponseEmbeddedToJSON,
    GetRelationPublic200ResponseEmbeddedToJSONTyped,
} from './GetRelationPublic200ResponseEmbedded';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
    LinksToJSONTyped,
} from './Links';

/**
 * 
 * @export
 * @interface GetRelationPublic200Response
 */
export interface GetRelationPublic200Response {
    /**
     * 
     * @type {string}
     * @memberof GetRelationPublic200Response
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof GetRelationPublic200Response
     */
    readonly uuid: string;
    /**
     * Display name based on the legal name, first, middle, and last name
     * @type {string}
     * @memberof GetRelationPublic200Response
     */
    readonly name?: string;
    /**
     * Registered number of the company
     * @type {string}
     * @memberof GetRelationPublic200Response
     */
    registeredNumber?: string;
    /**
     * 
     * @type {Language}
     * @memberof GetRelationPublic200Response
     */
    language?: Language;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetRelationPublic200Response
     */
    emails?: Array<string>;
    /**
     * ISO 3166-1 alpha-2 country code
     * @type {string}
     * @memberof GetRelationPublic200Response
     */
    registrationCountry?: string;
    /**
     * 
     * @type {GetRelationPublic200ResponseEu}
     * @memberof GetRelationPublic200Response
     */
    eu?: GetRelationPublic200ResponseEu;
    /**
     * 
     * @type {string}
     * @memberof GetRelationPublic200Response
     */
    legalName: string;
    /**
     * 
     * @type {string}
     * @memberof GetRelationPublic200Response
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof GetRelationPublic200Response
     */
    middleName: string;
    /**
     * 
     * @type {string}
     * @memberof GetRelationPublic200Response
     */
    lastName: string;
    /**
     * 
     * @type {Address}
     * @memberof GetRelationPublic200Response
     */
    address: Address;
    /**
     * Free form key/ value pair
     * @type {{ [key: string]: any; }}
     * @memberof GetRelationPublic200Response
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {Links}
     * @memberof GetRelationPublic200Response
     */
    links: Links;
    /**
     * 
     * @type {GetRelationPublic200ResponseEmbedded}
     * @memberof GetRelationPublic200Response
     */
    embedded?: GetRelationPublic200ResponseEmbedded;
    /**
     * 
     * @type {Date}
     * @memberof GetRelationPublic200Response
     */
    readonly updated: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetRelationPublic200Response
     */
    readonly created: Date;
}



/**
 * Check if a given object implements the GetRelationPublic200Response interface.
 */
export function instanceOfGetRelationPublic200Response(value: object): value is GetRelationPublic200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('legalName' in value) || value['legalName'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('middleName' in value) || value['middleName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function GetRelationPublic200ResponseFromJSON(json: any): GetRelationPublic200Response {
    return GetRelationPublic200ResponseFromJSONTyped(json, false);
}

export function GetRelationPublic200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRelationPublic200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'uuid': json['uuid'],
        'name': json['name'] == null ? undefined : json['name'],
        'registeredNumber': json['registered_number'] == null ? undefined : json['registered_number'],
        'language': json['language'] == null ? undefined : LanguageFromJSON(json['language']),
        'emails': json['emails'] == null ? undefined : json['emails'],
        'registrationCountry': json['registration_country'] == null ? undefined : json['registration_country'],
        'eu': json['eu'] == null ? undefined : GetRelationPublic200ResponseEuFromJSON(json['eu']),
        'legalName': json['legal_name'],
        'firstName': json['first_name'],
        'middleName': json['middle_name'],
        'lastName': json['last_name'],
        'address': AddressFromJSON(json['address']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'links': LinksFromJSON(json['_links']),
        'embedded': json['_embedded'] == null ? undefined : GetRelationPublic200ResponseEmbeddedFromJSON(json['_embedded']),
        'updated': (new Date(json['updated'])),
        'created': (new Date(json['created'])),
    };
}

export function GetRelationPublic200ResponseToJSON(json: any): GetRelationPublic200Response {
    return GetRelationPublic200ResponseToJSONTyped(json, false);
}

export function GetRelationPublic200ResponseToJSONTyped(value?: Omit<GetRelationPublic200Response, 'id'|'uuid'|'name'|'updated'|'created'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'registered_number': value['registeredNumber'],
        'language': LanguageToJSON(value['language']),
        'emails': value['emails'],
        'registration_country': value['registrationCountry'],
        'eu': GetRelationPublic200ResponseEuToJSON(value['eu']),
        'legal_name': value['legalName'],
        'first_name': value['firstName'],
        'middle_name': value['middleName'],
        'last_name': value['lastName'],
        'address': AddressToJSON(value['address']),
        'metadata': value['metadata'],
        '_links': LinksToJSON(value['links']),
        '_embedded': GetRelationPublic200ResponseEmbeddedToJSON(value['embedded']),
    };
}

