/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetRelationPublic200ResponseEuVies } from './GetRelationPublic200ResponseEuVies';
import {
    GetRelationPublic200ResponseEuViesFromJSON,
    GetRelationPublic200ResponseEuViesFromJSONTyped,
    GetRelationPublic200ResponseEuViesToJSON,
    GetRelationPublic200ResponseEuViesToJSONTyped,
} from './GetRelationPublic200ResponseEuVies';

/**
 * 
 * @export
 * @interface GetRelationPublic200ResponseEu
 */
export interface GetRelationPublic200ResponseEu {
    /**
     * 
     * @type {GetRelationPublic200ResponseEuVies}
     * @memberof GetRelationPublic200ResponseEu
     */
    vies?: GetRelationPublic200ResponseEuVies;
    /**
     * European Union VAT number
     * @type {string}
     * @memberof GetRelationPublic200ResponseEu
     */
    vatNumber: string;
}

/**
 * Check if a given object implements the GetRelationPublic200ResponseEu interface.
 */
export function instanceOfGetRelationPublic200ResponseEu(value: object): value is GetRelationPublic200ResponseEu {
    if (!('vatNumber' in value) || value['vatNumber'] === undefined) return false;
    return true;
}

export function GetRelationPublic200ResponseEuFromJSON(json: any): GetRelationPublic200ResponseEu {
    return GetRelationPublic200ResponseEuFromJSONTyped(json, false);
}

export function GetRelationPublic200ResponseEuFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRelationPublic200ResponseEu {
    if (json == null) {
        return json;
    }
    return {
        
        'vies': json['vies'] == null ? undefined : GetRelationPublic200ResponseEuViesFromJSON(json['vies']),
        'vatNumber': json['vat-number'],
    };
}

export function GetRelationPublic200ResponseEuToJSON(json: any): GetRelationPublic200ResponseEu {
    return GetRelationPublic200ResponseEuToJSONTyped(json, false);
}

export function GetRelationPublic200ResponseEuToJSONTyped(value?: GetRelationPublic200ResponseEu | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vies': GetRelationPublic200ResponseEuViesToJSON(value['vies']),
        'vat-number': value['vatNumber'],
    };
}

