/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetReminderPublic200ResponseAmountsBooked } from './GetReminderPublic200ResponseAmountsBooked';
import {
    GetReminderPublic200ResponseAmountsBookedFromJSON,
    GetReminderPublic200ResponseAmountsBookedFromJSONTyped,
    GetReminderPublic200ResponseAmountsBookedToJSON,
    GetReminderPublic200ResponseAmountsBookedToJSONTyped,
} from './GetReminderPublic200ResponseAmountsBooked';

/**
 * 
 * @export
 * @interface GetReminderPublic200ResponseAmounts
 */
export interface GetReminderPublic200ResponseAmounts {
    /**
     * 
     * @type {GetReminderPublic200ResponseAmountsBooked}
     * @memberof GetReminderPublic200ResponseAmounts
     */
    booked: GetReminderPublic200ResponseAmountsBooked;
    /**
     * 
     * @type {number}
     * @memberof GetReminderPublic200ResponseAmounts
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof GetReminderPublic200ResponseAmounts
     */
    subtotal: number;
    /**
     * 
     * @type {number}
     * @memberof GetReminderPublic200ResponseAmounts
     */
    payments: number;
    /**
     * 
     * @type {number}
     * @memberof GetReminderPublic200ResponseAmounts
     */
    fees: number;
    /**
     * 
     * @type {number}
     * @memberof GetReminderPublic200ResponseAmounts
     */
    interest: number;
}

/**
 * Check if a given object implements the GetReminderPublic200ResponseAmounts interface.
 */
export function instanceOfGetReminderPublic200ResponseAmounts(value: object): value is GetReminderPublic200ResponseAmounts {
    if (!('booked' in value) || value['booked'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('subtotal' in value) || value['subtotal'] === undefined) return false;
    if (!('payments' in value) || value['payments'] === undefined) return false;
    if (!('fees' in value) || value['fees'] === undefined) return false;
    if (!('interest' in value) || value['interest'] === undefined) return false;
    return true;
}

export function GetReminderPublic200ResponseAmountsFromJSON(json: any): GetReminderPublic200ResponseAmounts {
    return GetReminderPublic200ResponseAmountsFromJSONTyped(json, false);
}

export function GetReminderPublic200ResponseAmountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetReminderPublic200ResponseAmounts {
    if (json == null) {
        return json;
    }
    return {
        
        'booked': GetReminderPublic200ResponseAmountsBookedFromJSON(json['booked']),
        'total': json['total'],
        'subtotal': json['subtotal'],
        'payments': json['payments'],
        'fees': json['fees'],
        'interest': json['interest'],
    };
}

export function GetReminderPublic200ResponseAmountsToJSON(json: any): GetReminderPublic200ResponseAmounts {
    return GetReminderPublic200ResponseAmountsToJSONTyped(json, false);
}

export function GetReminderPublic200ResponseAmountsToJSONTyped(value?: GetReminderPublic200ResponseAmounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'booked': GetReminderPublic200ResponseAmountsBookedToJSON(value['booked']),
        'total': value['total'],
        'subtotal': value['subtotal'],
        'payments': value['payments'],
        'fees': value['fees'],
        'interest': value['interest'],
    };
}

