/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetSubscriptionPublic200ResponseEmbeddedLinesInner } from './GetSubscriptionPublic200ResponseEmbeddedLinesInner';
import {
    GetSubscriptionPublic200ResponseEmbeddedLinesInnerFromJSON,
    GetSubscriptionPublic200ResponseEmbeddedLinesInnerFromJSONTyped,
    GetSubscriptionPublic200ResponseEmbeddedLinesInnerToJSON,
    GetSubscriptionPublic200ResponseEmbeddedLinesInnerToJSONTyped,
} from './GetSubscriptionPublic200ResponseEmbeddedLinesInner';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
    ProfileToJSONTyped,
} from './Profile';

/**
 * 
 * @export
 * @interface GetSubscriptionPublic200ResponseEmbedded
 */
export interface GetSubscriptionPublic200ResponseEmbedded {
    /**
     * 
     * @type {Array<GetSubscriptionPublic200ResponseEmbeddedLinesInner>}
     * @memberof GetSubscriptionPublic200ResponseEmbedded
     */
    lines: Array<GetSubscriptionPublic200ResponseEmbeddedLinesInner>;
    /**
     * 
     * @type {Profile}
     * @memberof GetSubscriptionPublic200ResponseEmbedded
     */
    profile?: Profile;
}

/**
 * Check if a given object implements the GetSubscriptionPublic200ResponseEmbedded interface.
 */
export function instanceOfGetSubscriptionPublic200ResponseEmbedded(value: object): value is GetSubscriptionPublic200ResponseEmbedded {
    if (!('lines' in value) || value['lines'] === undefined) return false;
    return true;
}

export function GetSubscriptionPublic200ResponseEmbeddedFromJSON(json: any): GetSubscriptionPublic200ResponseEmbedded {
    return GetSubscriptionPublic200ResponseEmbeddedFromJSONTyped(json, false);
}

export function GetSubscriptionPublic200ResponseEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSubscriptionPublic200ResponseEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'lines': ((json['lines'] as Array<any>).map(GetSubscriptionPublic200ResponseEmbeddedLinesInnerFromJSON)),
        'profile': json['profile'] == null ? undefined : ProfileFromJSON(json['profile']),
    };
}

export function GetSubscriptionPublic200ResponseEmbeddedToJSON(json: any): GetSubscriptionPublic200ResponseEmbedded {
    return GetSubscriptionPublic200ResponseEmbeddedToJSONTyped(json, false);
}

export function GetSubscriptionPublic200ResponseEmbeddedToJSONTyped(value?: GetSubscriptionPublic200ResponseEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lines': ((value['lines'] as Array<any>).map(GetSubscriptionPublic200ResponseEmbeddedLinesInnerToJSON)),
        'profile': ProfileToJSON(value['profile']),
    };
}

