/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinksSelf
 */
export interface LinksSelf {
    /**
     * The URL of the resource
     * @type {string}
     * @memberof LinksSelf
     */
    href: string;
    /**
     * 
     * @type {string}
     * @memberof LinksSelf
     */
    type: string;
}

/**
 * Check if a given object implements the LinksSelf interface.
 */
export function instanceOfLinksSelf(value: object): value is LinksSelf {
    if (!('href' in value) || value['href'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function LinksSelfFromJSON(json: any): LinksSelf {
    return LinksSelfFromJSONTyped(json, false);
}

export function LinksSelfFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinksSelf {
    if (json == null) {
        return json;
    }
    return {
        
        'href': json['href'],
        'type': json['type'],
    };
}

export function LinksSelfToJSON(json: any): LinksSelf {
    return LinksSelfToJSONTyped(json, false);
}

export function LinksSelfToJSONTyped(value?: LinksSelf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'href': value['href'],
        'type': value['type'],
    };
}

