/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NLVATFilingDataSection5 } from './NLVATFilingDataSection5';
import {
    NLVATFilingDataSection5FromJSON,
    NLVATFilingDataSection5FromJSONTyped,
    NLVATFilingDataSection5ToJSON,
    NLVATFilingDataSection5ToJSONTyped,
} from './NLVATFilingDataSection5';
import type { NLVATFilingDataSection3 } from './NLVATFilingDataSection3';
import {
    NLVATFilingDataSection3FromJSON,
    NLVATFilingDataSection3FromJSONTyped,
    NLVATFilingDataSection3ToJSON,
    NLVATFilingDataSection3ToJSONTyped,
} from './NLVATFilingDataSection3';
import type { NLVATFilingDataSection4 } from './NLVATFilingDataSection4';
import {
    NLVATFilingDataSection4FromJSON,
    NLVATFilingDataSection4FromJSONTyped,
    NLVATFilingDataSection4ToJSON,
    NLVATFilingDataSection4ToJSONTyped,
} from './NLVATFilingDataSection4';
import type { NLVATFilingDataSection1 } from './NLVATFilingDataSection1';
import {
    NLVATFilingDataSection1FromJSON,
    NLVATFilingDataSection1FromJSONTyped,
    NLVATFilingDataSection1ToJSON,
    NLVATFilingDataSection1ToJSONTyped,
} from './NLVATFilingDataSection1';
import type { NLVATFilingDataSection2 } from './NLVATFilingDataSection2';
import {
    NLVATFilingDataSection2FromJSON,
    NLVATFilingDataSection2FromJSONTyped,
    NLVATFilingDataSection2ToJSON,
    NLVATFilingDataSection2ToJSONTyped,
} from './NLVATFilingDataSection2';

/**
 * 
 * @export
 * @interface NLVATFilingData
 */
export interface NLVATFilingData {
    /**
     * Start date of the period.
     * @type {Date}
     * @memberof NLVATFilingData
     */
    start: Date;
    /**
     * End date of the period.
     * @type {Date}
     * @memberof NLVATFilingData
     */
    end: Date;
    /**
     * 
     * @type {NLVATFilingDataSection1}
     * @memberof NLVATFilingData
     */
    section1: NLVATFilingDataSection1;
    /**
     * 
     * @type {NLVATFilingDataSection2}
     * @memberof NLVATFilingData
     */
    section2: NLVATFilingDataSection2;
    /**
     * 
     * @type {NLVATFilingDataSection3}
     * @memberof NLVATFilingData
     */
    section3: NLVATFilingDataSection3;
    /**
     * 
     * @type {NLVATFilingDataSection4}
     * @memberof NLVATFilingData
     */
    section4: NLVATFilingDataSection4;
    /**
     * 
     * @type {NLVATFilingDataSection5}
     * @memberof NLVATFilingData
     */
    section5: NLVATFilingDataSection5;
}

/**
 * Check if a given object implements the NLVATFilingData interface.
 */
export function instanceOfNLVATFilingData(value: object): value is NLVATFilingData {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('section1' in value) || value['section1'] === undefined) return false;
    if (!('section2' in value) || value['section2'] === undefined) return false;
    if (!('section3' in value) || value['section3'] === undefined) return false;
    if (!('section4' in value) || value['section4'] === undefined) return false;
    if (!('section5' in value) || value['section5'] === undefined) return false;
    return true;
}

export function NLVATFilingDataFromJSON(json: any): NLVATFilingData {
    return NLVATFilingDataFromJSONTyped(json, false);
}

export function NLVATFilingDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NLVATFilingData {
    if (json == null) {
        return json;
    }
    return {
        
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'section1': NLVATFilingDataSection1FromJSON(json['section1']),
        'section2': NLVATFilingDataSection2FromJSON(json['section2']),
        'section3': NLVATFilingDataSection3FromJSON(json['section3']),
        'section4': NLVATFilingDataSection4FromJSON(json['section4']),
        'section5': NLVATFilingDataSection5FromJSON(json['section5']),
    };
}

export function NLVATFilingDataToJSON(json: any): NLVATFilingData {
    return NLVATFilingDataToJSONTyped(json, false);
}

export function NLVATFilingDataToJSONTyped(value?: NLVATFilingData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'section1': NLVATFilingDataSection1ToJSON(value['section1']),
        'section2': NLVATFilingDataSection2ToJSON(value['section2']),
        'section3': NLVATFilingDataSection3ToJSON(value['section3']),
        'section4': NLVATFilingDataSection4ToJSON(value['section4']),
        'section5': NLVATFilingDataSection5ToJSON(value['section5']),
    };
}

