/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetSubscriptionPublic200ResponseAmounts } from './GetSubscriptionPublic200ResponseAmounts';
import {
    GetSubscriptionPublic200ResponseAmountsFromJSON,
    GetSubscriptionPublic200ResponseAmountsFromJSONTyped,
    GetSubscriptionPublic200ResponseAmountsToJSON,
    GetSubscriptionPublic200ResponseAmountsToJSONTyped,
} from './GetSubscriptionPublic200ResponseAmounts';
import type { SubscriptionFrequency } from './SubscriptionFrequency';
import {
    SubscriptionFrequencyFromJSON,
    SubscriptionFrequencyFromJSONTyped,
    SubscriptionFrequencyToJSON,
    SubscriptionFrequencyToJSONTyped,
} from './SubscriptionFrequency';
import type { ObligationEmbedded } from './ObligationEmbedded';
import {
    ObligationEmbeddedFromJSON,
    ObligationEmbeddedFromJSONTyped,
    ObligationEmbeddedToJSON,
    ObligationEmbeddedToJSONTyped,
} from './ObligationEmbedded';

/**
 * 
 * @export
 * @interface Obligation
 */
export interface Obligation {
    /**
     * 
     * @type {string}
     * @memberof Obligation
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Obligation
     */
    readonly uuid: string;
    /**
     * ISO 3166-1 alpha-2 currency code
     * @type {string}
     * @memberof Obligation
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof Obligation
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Obligation
     */
    relation: string;
    /**
     * 
     * @type {Date}
     * @memberof Obligation
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof Obligation
     */
    endDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Obligation
     */
    canceled?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Obligation
     */
    renewal?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Obligation
     */
    closed?: Date;
    /**
     * 
     * @type {GetSubscriptionPublic200ResponseAmounts}
     * @memberof Obligation
     */
    amounts: GetSubscriptionPublic200ResponseAmounts;
    /**
     * 
     * @type {SubscriptionFrequency}
     * @memberof Obligation
     */
    frequency: SubscriptionFrequency;
    /**
     * Free form key/ value pair
     * @type {{ [key: string]: any; }}
     * @memberof Obligation
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {ObligationEmbedded}
     * @memberof Obligation
     */
    embedded: ObligationEmbedded;
    /**
     * 
     * @type {Date}
     * @memberof Obligation
     */
    readonly updated: Date;
    /**
     * 
     * @type {Date}
     * @memberof Obligation
     */
    readonly created: Date;
}



/**
 * Check if a given object implements the Obligation interface.
 */
export function instanceOfObligation(value: object): value is Obligation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('relation' in value) || value['relation'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('amounts' in value) || value['amounts'] === undefined) return false;
    if (!('frequency' in value) || value['frequency'] === undefined) return false;
    if (!('embedded' in value) || value['embedded'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function ObligationFromJSON(json: any): Obligation {
    return ObligationFromJSONTyped(json, false);
}

export function ObligationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Obligation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'uuid': json['uuid'],
        'currency': json['currency'],
        'name': json['name'],
        'relation': json['relation'],
        'startDate': (new Date(json['start-date'])),
        'endDate': json['end-date'] == null ? undefined : (new Date(json['end-date'])),
        'canceled': json['canceled'] == null ? undefined : (new Date(json['canceled'])),
        'renewal': json['renewal'] == null ? undefined : (new Date(json['renewal'])),
        'closed': json['closed'] == null ? undefined : (new Date(json['closed'])),
        'amounts': GetSubscriptionPublic200ResponseAmountsFromJSON(json['amounts']),
        'frequency': SubscriptionFrequencyFromJSON(json['frequency']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'embedded': ObligationEmbeddedFromJSON(json['_embedded']),
        'updated': (new Date(json['updated'])),
        'created': (new Date(json['created'])),
    };
}

export function ObligationToJSON(json: any): Obligation {
    return ObligationToJSONTyped(json, false);
}

export function ObligationToJSONTyped(value?: Omit<Obligation, 'id'|'uuid'|'updated'|'created'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'name': value['name'],
        'relation': value['relation'],
        'start-date': ((value['startDate']).toISOString().substring(0,10)),
        'end-date': value['endDate'] == null ? undefined : ((value['endDate']).toISOString().substring(0,10)),
        'canceled': value['canceled'] == null ? undefined : ((value['canceled']).toISOString().substring(0,10)),
        'renewal': value['renewal'] == null ? undefined : ((value['renewal']).toISOString().substring(0,10)),
        'closed': value['closed'] == null ? undefined : ((value['closed']).toISOString().substring(0,10)),
        'amounts': GetSubscriptionPublic200ResponseAmountsToJSON(value['amounts']),
        'frequency': SubscriptionFrequencyToJSON(value['frequency']),
        'metadata': value['metadata'],
        '_embedded': ObligationEmbeddedToJSON(value['embedded']),
    };
}

