/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfilePublicNlVat } from './ProfilePublicNlVat';
import {
    ProfilePublicNlVatFromJSON,
    ProfilePublicNlVatFromJSONTyped,
    ProfilePublicNlVatToJSON,
    ProfilePublicNlVatToJSONTyped,
} from './ProfilePublicNlVat';

/**
 * 
 * @export
 * @interface ProfilePublicNl
 */
export interface ProfilePublicNl {
    /**
     * 
     * @type {string}
     * @memberof ProfilePublicNl
     */
    chamberOfCommerce: string;
    /**
     * 
     * @type {ProfilePublicNlVat}
     * @memberof ProfilePublicNl
     */
    vat?: ProfilePublicNlVat;
}

/**
 * Check if a given object implements the ProfilePublicNl interface.
 */
export function instanceOfProfilePublicNl(value: object): value is ProfilePublicNl {
    if (!('chamberOfCommerce' in value) || value['chamberOfCommerce'] === undefined) return false;
    return true;
}

export function ProfilePublicNlFromJSON(json: any): ProfilePublicNl {
    return ProfilePublicNlFromJSONTyped(json, false);
}

export function ProfilePublicNlFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilePublicNl {
    if (json == null) {
        return json;
    }
    return {
        
        'chamberOfCommerce': json['chamber_of_commerce'],
        'vat': json['vat'] == null ? undefined : ProfilePublicNlVatFromJSON(json['vat']),
    };
}

export function ProfilePublicNlToJSON(json: any): ProfilePublicNl {
    return ProfilePublicNlToJSONTyped(json, false);
}

export function ProfilePublicNlToJSONTyped(value?: ProfilePublicNl | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chamber_of_commerce': value['chamberOfCommerce'],
        'vat': ProfilePublicNlVatToJSON(value['vat']),
    };
}

