/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PurchaseOrderLine } from './PurchaseOrderLine';
import {
    PurchaseOrderLineFromJSON,
    PurchaseOrderLineFromJSONTyped,
    PurchaseOrderLineToJSON,
    PurchaseOrderLineToJSONTyped,
} from './PurchaseOrderLine';
import type { Relation } from './Relation';
import {
    RelationFromJSON,
    RelationFromJSONTyped,
    RelationToJSON,
    RelationToJSONTyped,
} from './Relation';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
    ProfileToJSONTyped,
} from './Profile';

/**
 * 
 * @export
 * @interface PurchaseOrderEmbedded
 */
export interface PurchaseOrderEmbedded {
    /**
     * 
     * @type {Profile}
     * @memberof PurchaseOrderEmbedded
     */
    profile: Profile;
    /**
     * 
     * @type {Relation}
     * @memberof PurchaseOrderEmbedded
     */
    relation: Relation;
    /**
     * 
     * @type {Array<PurchaseOrderLine>}
     * @memberof PurchaseOrderEmbedded
     */
    lines: Array<PurchaseOrderLine>;
}

/**
 * Check if a given object implements the PurchaseOrderEmbedded interface.
 */
export function instanceOfPurchaseOrderEmbedded(value: object): value is PurchaseOrderEmbedded {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('relation' in value) || value['relation'] === undefined) return false;
    if (!('lines' in value) || value['lines'] === undefined) return false;
    return true;
}

export function PurchaseOrderEmbeddedFromJSON(json: any): PurchaseOrderEmbedded {
    return PurchaseOrderEmbeddedFromJSONTyped(json, false);
}

export function PurchaseOrderEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseOrderEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': ProfileFromJSON(json['profile']),
        'relation': RelationFromJSON(json['relation']),
        'lines': ((json['lines'] as Array<any>).map(PurchaseOrderLineFromJSON)),
    };
}

export function PurchaseOrderEmbeddedToJSON(json: any): PurchaseOrderEmbedded {
    return PurchaseOrderEmbeddedToJSONTyped(json, false);
}

export function PurchaseOrderEmbeddedToJSONTyped(value?: PurchaseOrderEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile': ProfileToJSON(value['profile']),
        'relation': RelationToJSON(value['relation']),
        'lines': ((value['lines'] as Array<any>).map(PurchaseOrderLineToJSON)),
    };
}

