/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RelationEuVies
 */
export interface RelationEuVies {
    /**
     * Whether the VAT number is valid
     * @type {boolean}
     * @memberof RelationEuVies
     */
    valid: boolean;
    /**
     * Name of the company
     * @type {string}
     * @memberof RelationEuVies
     */
    name?: string;
    /**
     * Address of the company
     * @type {string}
     * @memberof RelationEuVies
     */
    address?: string;
}

/**
 * Check if a given object implements the RelationEuVies interface.
 */
export function instanceOfRelationEuVies(value: object): value is RelationEuVies {
    if (!('valid' in value) || value['valid'] === undefined) return false;
    return true;
}

export function RelationEuViesFromJSON(json: any): RelationEuVies {
    return RelationEuViesFromJSONTyped(json, false);
}

export function RelationEuViesFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationEuVies {
    if (json == null) {
        return json;
    }
    return {
        
        'valid': json['valid'],
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function RelationEuViesToJSON(json: any): RelationEuVies {
    return RelationEuViesToJSONTyped(json, false);
}

export function RelationEuViesToJSONTyped(value?: RelationEuVies | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valid': value['valid'],
        'name': value['name'],
        'address': value['address'],
    };
}

