/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReminderAmountsBooked
 */
export interface ReminderAmountsBooked {
    /**
     * 
     * @type {number}
     * @memberof ReminderAmountsBooked
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ReminderAmountsBooked
     */
    fees: number;
}

/**
 * Check if a given object implements the ReminderAmountsBooked interface.
 */
export function instanceOfReminderAmountsBooked(value: object): value is ReminderAmountsBooked {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('fees' in value) || value['fees'] === undefined) return false;
    return true;
}

export function ReminderAmountsBookedFromJSON(json: any): ReminderAmountsBooked {
    return ReminderAmountsBookedFromJSONTyped(json, false);
}

export function ReminderAmountsBookedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReminderAmountsBooked {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'fees': json['fees'],
    };
}

export function ReminderAmountsBookedToJSON(json: any): ReminderAmountsBooked {
    return ReminderAmountsBookedToJSONTyped(json, false);
}

export function ReminderAmountsBookedToJSONTyped(value?: ReminderAmountsBooked | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'fees': value['fees'],
    };
}

