/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReminderAmountsBooked } from './ReminderAmountsBooked';
import {
    ReminderAmountsBookedFromJSON,
    ReminderAmountsBookedFromJSONTyped,
    ReminderAmountsBookedToJSON,
    ReminderAmountsBookedToJSONTyped,
} from './ReminderAmountsBooked';

/**
 * 
 * @export
 * @interface ReminderAmounts
 */
export interface ReminderAmounts {
    /**
     * 
     * @type {ReminderAmountsBooked}
     * @memberof ReminderAmounts
     */
    booked: ReminderAmountsBooked;
    /**
     * 
     * @type {number}
     * @memberof ReminderAmounts
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ReminderAmounts
     */
    payments: number;
    /**
     * 
     * @type {number}
     * @memberof ReminderAmounts
     */
    fees: number;
}

/**
 * Check if a given object implements the ReminderAmounts interface.
 */
export function instanceOfReminderAmounts(value: object): value is ReminderAmounts {
    if (!('booked' in value) || value['booked'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('payments' in value) || value['payments'] === undefined) return false;
    if (!('fees' in value) || value['fees'] === undefined) return false;
    return true;
}

export function ReminderAmountsFromJSON(json: any): ReminderAmounts {
    return ReminderAmountsFromJSONTyped(json, false);
}

export function ReminderAmountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReminderAmounts {
    if (json == null) {
        return json;
    }
    return {
        
        'booked': ReminderAmountsBookedFromJSON(json['booked']),
        'total': json['total'],
        'payments': json['payments'],
        'fees': json['fees'],
    };
}

export function ReminderAmountsToJSON(json: any): ReminderAmounts {
    return ReminderAmountsToJSONTyped(json, false);
}

export function ReminderAmountsToJSONTyped(value?: ReminderAmounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'booked': ReminderAmountsBookedToJSON(value['booked']),
        'total': value['total'],
        'payments': value['payments'],
        'fees': value['fees'],
    };
}

