/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetAccountPasswordRequest
 */
export interface ResetAccountPasswordRequest {
    /**
     * JWT token of the password reset request
     * @type {string}
     * @memberof ResetAccountPasswordRequest
     */
    token: string;
    /**
     * New password
     * @type {string}
     * @memberof ResetAccountPasswordRequest
     */
    password: string;
}

/**
 * Check if a given object implements the ResetAccountPasswordRequest interface.
 */
export function instanceOfResetAccountPasswordRequest(value: object): value is ResetAccountPasswordRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function ResetAccountPasswordRequestFromJSON(json: any): ResetAccountPasswordRequest {
    return ResetAccountPasswordRequestFromJSONTyped(json, false);
}

export function ResetAccountPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetAccountPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'password': json['password'],
    };
}

export function ResetAccountPasswordRequestToJSON(json: any): ResetAccountPasswordRequest {
    return ResetAccountPasswordRequestToJSONTyped(json, false);
}

export function ResetAccountPasswordRequestToJSONTyped(value?: ResetAccountPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'password': value['password'],
    };
}

