/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendResetPasswordRequestRequest
 */
export interface SendResetPasswordRequestRequest {
    /**
     * Account ID
     * @type {string}
     * @memberof SendResetPasswordRequestRequest
     */
    id: string;
}

/**
 * Check if a given object implements the SendResetPasswordRequestRequest interface.
 */
export function instanceOfSendResetPasswordRequestRequest(value: object): value is SendResetPasswordRequestRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SendResetPasswordRequestRequestFromJSON(json: any): SendResetPasswordRequestRequest {
    return SendResetPasswordRequestRequestFromJSONTyped(json, false);
}

export function SendResetPasswordRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendResetPasswordRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function SendResetPasswordRequestRequestToJSON(json: any): SendResetPasswordRequestRequest {
    return SendResetPasswordRequestRequestToJSONTyped(json, false);
}

export function SendResetPasswordRequestRequestToJSONTyped(value?: SendResetPasswordRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

