/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnauthorisedError
 */
export interface UnauthorisedError {
    /**
     * 
     * @type {string}
     * @memberof UnauthorisedError
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof UnauthorisedError
     */
    errorDescription?: string;
}

/**
 * Check if a given object implements the UnauthorisedError interface.
 */
export function instanceOfUnauthorisedError(value: object): value is UnauthorisedError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function UnauthorisedErrorFromJSON(json: any): UnauthorisedError {
    return UnauthorisedErrorFromJSONTyped(json, false);
}

export function UnauthorisedErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnauthorisedError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'errorDescription': json['error_description'] == null ? undefined : json['error_description'],
    };
}

export function UnauthorisedErrorToJSON(json: any): UnauthorisedError {
    return UnauthorisedErrorToJSONTyped(json, false);
}

export function UnauthorisedErrorToJSONTyped(value?: UnauthorisedError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'error_description': value['errorDescription'],
    };
}

