/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProfileRequestNlVat
 */
export interface CreateProfileRequestNlVat {
    /**
     * 
     * @type {string}
     * @memberof CreateProfileRequestNlVat
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProfileRequestNlVat
     */
    number: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProfileRequestNlVat
     */
    timeframe: CreateProfileRequestNlVatTimeframeEnum;
}


/**
 * @export
 */
export const CreateProfileRequestNlVatTimeframeEnum = {
    Month: 'month',
    Quarter: 'quarter',
    Year: 'year'
} as const;
export type CreateProfileRequestNlVatTimeframeEnum = typeof CreateProfileRequestNlVatTimeframeEnum[keyof typeof CreateProfileRequestNlVatTimeframeEnum];


/**
 * Check if a given object implements the CreateProfileRequestNlVat interface.
 */
export function instanceOfCreateProfileRequestNlVat(value: object): value is CreateProfileRequestNlVat {
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('timeframe' in value) || value['timeframe'] === undefined) return false;
    return true;
}

export function CreateProfileRequestNlVatFromJSON(json: any): CreateProfileRequestNlVat {
    return CreateProfileRequestNlVatFromJSONTyped(json, false);
}

export function CreateProfileRequestNlVatFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProfileRequestNlVat {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'number': json['number'],
        'timeframe': json['timeframe'],
    };
}

export function CreateProfileRequestNlVatToJSON(json: any): CreateProfileRequestNlVat {
    return CreateProfileRequestNlVatToJSONTyped(json, false);
}

export function CreateProfileRequestNlVatToJSONTyped(value?: CreateProfileRequestNlVat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'number': value['number'],
        'timeframe': value['timeframe'],
    };
}

