/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProfileRequestSettingsPurchaseInvoice
 */
export interface CreateProfileRequestSettingsPurchaseInvoice {
    /**
     * 
     * @type {number}
     * @memberof CreateProfileRequestSettingsPurchaseInvoice
     */
    paymentDays?: number;
}

/**
 * Check if a given object implements the CreateProfileRequestSettingsPurchaseInvoice interface.
 */
export function instanceOfCreateProfileRequestSettingsPurchaseInvoice(value: object): value is CreateProfileRequestSettingsPurchaseInvoice {
    return true;
}

export function CreateProfileRequestSettingsPurchaseInvoiceFromJSON(json: any): CreateProfileRequestSettingsPurchaseInvoice {
    return CreateProfileRequestSettingsPurchaseInvoiceFromJSONTyped(json, false);
}

export function CreateProfileRequestSettingsPurchaseInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProfileRequestSettingsPurchaseInvoice {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentDays': json['payment_days'] == null ? undefined : json['payment_days'],
    };
}

export function CreateProfileRequestSettingsPurchaseInvoiceToJSON(json: any): CreateProfileRequestSettingsPurchaseInvoice {
    return CreateProfileRequestSettingsPurchaseInvoiceToJSONTyped(json, false);
}

export function CreateProfileRequestSettingsPurchaseInvoiceToJSONTyped(value?: CreateProfileRequestSettingsPurchaseInvoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_days': value['paymentDays'],
    };
}

