/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateProfileRequestSettingsSalesInvoice } from './CreateProfileRequestSettingsSalesInvoice';
import {
    CreateProfileRequestSettingsSalesInvoiceFromJSON,
    CreateProfileRequestSettingsSalesInvoiceFromJSONTyped,
    CreateProfileRequestSettingsSalesInvoiceToJSON,
    CreateProfileRequestSettingsSalesInvoiceToJSONTyped,
} from './CreateProfileRequestSettingsSalesInvoice';
import type { CreateProfileRequestSettingsPurchaseInvoice } from './CreateProfileRequestSettingsPurchaseInvoice';
import {
    CreateProfileRequestSettingsPurchaseInvoiceFromJSON,
    CreateProfileRequestSettingsPurchaseInvoiceFromJSONTyped,
    CreateProfileRequestSettingsPurchaseInvoiceToJSON,
    CreateProfileRequestSettingsPurchaseInvoiceToJSONTyped,
} from './CreateProfileRequestSettingsPurchaseInvoice';
import type { CreateProfileRequestSettingsBranding } from './CreateProfileRequestSettingsBranding';
import {
    CreateProfileRequestSettingsBrandingFromJSON,
    CreateProfileRequestSettingsBrandingFromJSONTyped,
    CreateProfileRequestSettingsBrandingToJSON,
    CreateProfileRequestSettingsBrandingToJSONTyped,
} from './CreateProfileRequestSettingsBranding';
import type { CreateProfileRequestSettingsEmail } from './CreateProfileRequestSettingsEmail';
import {
    CreateProfileRequestSettingsEmailFromJSON,
    CreateProfileRequestSettingsEmailFromJSONTyped,
    CreateProfileRequestSettingsEmailToJSON,
    CreateProfileRequestSettingsEmailToJSONTyped,
} from './CreateProfileRequestSettingsEmail';

/**
 * 
 * @export
 * @interface CreateProfileRequestSettings
 */
export interface CreateProfileRequestSettings {
    /**
     * 
     * @type {CreateProfileRequestSettingsEmail}
     * @memberof CreateProfileRequestSettings
     */
    email?: CreateProfileRequestSettingsEmail;
    /**
     * 
     * @type {CreateProfileRequestSettingsSalesInvoice}
     * @memberof CreateProfileRequestSettings
     */
    salesInvoice?: CreateProfileRequestSettingsSalesInvoice;
    /**
     * 
     * @type {CreateProfileRequestSettingsPurchaseInvoice}
     * @memberof CreateProfileRequestSettings
     */
    purchaseInvoice?: CreateProfileRequestSettingsPurchaseInvoice;
    /**
     * 
     * @type {CreateProfileRequestSettingsBranding}
     * @memberof CreateProfileRequestSettings
     */
    branding?: CreateProfileRequestSettingsBranding;
}

/**
 * Check if a given object implements the CreateProfileRequestSettings interface.
 */
export function instanceOfCreateProfileRequestSettings(value: object): value is CreateProfileRequestSettings {
    return true;
}

export function CreateProfileRequestSettingsFromJSON(json: any): CreateProfileRequestSettings {
    return CreateProfileRequestSettingsFromJSONTyped(json, false);
}

export function CreateProfileRequestSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProfileRequestSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : CreateProfileRequestSettingsEmailFromJSON(json['email']),
        'salesInvoice': json['sales_invoice'] == null ? undefined : CreateProfileRequestSettingsSalesInvoiceFromJSON(json['sales_invoice']),
        'purchaseInvoice': json['purchase_invoice'] == null ? undefined : CreateProfileRequestSettingsPurchaseInvoiceFromJSON(json['purchase_invoice']),
        'branding': json['branding'] == null ? undefined : CreateProfileRequestSettingsBrandingFromJSON(json['branding']),
    };
}

export function CreateProfileRequestSettingsToJSON(json: any): CreateProfileRequestSettings {
    return CreateProfileRequestSettingsToJSONTyped(json, false);
}

export function CreateProfileRequestSettingsToJSONTyped(value?: CreateProfileRequestSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': CreateProfileRequestSettingsEmailToJSON(value['email']),
        'sales_invoice': CreateProfileRequestSettingsSalesInvoiceToJSON(value['salesInvoice']),
        'purchase_invoice': CreateProfileRequestSettingsPurchaseInvoiceToJSON(value['purchaseInvoice']),
        'branding': CreateProfileRequestSettingsBrandingToJSON(value['branding']),
    };
}

