/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAssetWriteoffRequest
 */
export interface CreateAssetWriteoffRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAssetWriteoffRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateAssetWriteoffRequest
     */
    amount: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateAssetWriteoffRequest
     */
    date: Date;
    /**
     * Free form key/ value pair
     * @type {{ [key: string]: any; }}
     * @memberof CreateAssetWriteoffRequest
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateAssetWriteoffRequest interface.
 */
export function instanceOfCreateAssetWriteoffRequest(value: object): value is CreateAssetWriteoffRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    return true;
}

export function CreateAssetWriteoffRequestFromJSON(json: any): CreateAssetWriteoffRequest {
    return CreateAssetWriteoffRequestFromJSONTyped(json, false);
}

export function CreateAssetWriteoffRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAssetWriteoffRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'],
        'date': (new Date(json['date'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateAssetWriteoffRequestToJSON(json: any): CreateAssetWriteoffRequest {
    return CreateAssetWriteoffRequestToJSONTyped(json, false);
}

export function CreateAssetWriteoffRequestToJSONTyped(value?: CreateAssetWriteoffRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'amount': value['amount'],
        'date': ((value['date']).toISOString().substring(0,10)),
        'metadata': value['metadata'],
    };
}

