/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1
 */
export interface CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1 {
    /**
     * ID of the product
     * @type {string}
     * @memberof CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1
     */
    product: string;
    /**
     * The price of one item in cents, excluding taxes
     * @type {number}
     * @memberof CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1
     */
    price: number;
    /**
     * The total discount in cents of the one x quantity of the line, do not use a 0 or non positive values.
     * @type {number}
     * @memberof CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1
     */
    discount?: number;
    /**
     * Quantity of the line
     * @type {number}
     * @memberof CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1
     */
    quantity: number;
    /**
     * Free form key/ value pair
     * @type {{ [key: string]: any; }}
     * @memberof CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1 interface.
 */
export function instanceOfCreatePurchaseInvoiceFinalRequestLinesInnerOneOf1(value: object): value is CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1 {
    if (!('product' in value) || value['product'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1FromJSON(json: any): CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1 {
    return CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1FromJSONTyped(json, false);
}

export function CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'product': json['product'],
        'price': json['price'],
        'discount': json['discount'] == null ? undefined : json['discount'],
        'quantity': json['quantity'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1ToJSON(json: any): CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1 {
    return CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1ToJSONTyped(json, false);
}

export function CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1ToJSONTyped(value?: CreatePurchaseInvoiceFinalRequestLinesInnerOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product': value['product'],
        'price': value['price'],
        'discount': value['discount'],
        'quantity': value['quantity'],
        'metadata': value['metadata'],
    };
}

