/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionFrequency } from './SubscriptionFrequency';
import {
    SubscriptionFrequencyFromJSON,
    SubscriptionFrequencyFromJSONTyped,
    SubscriptionFrequencyToJSON,
    SubscriptionFrequencyToJSONTyped,
} from './SubscriptionFrequency';

/**
 * 
 * @export
 * @interface CreateObligaitonBasedOnPurchaseInvoiceRequest
 */
export interface CreateObligaitonBasedOnPurchaseInvoiceRequest {
    /**
     * 
     * @type {Date}
     * @memberof CreateObligaitonBasedOnPurchaseInvoiceRequest
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateObligaitonBasedOnPurchaseInvoiceRequest
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateObligaitonBasedOnPurchaseInvoiceRequest
     */
    name: string;
    /**
     * 
     * @type {SubscriptionFrequency}
     * @memberof CreateObligaitonBasedOnPurchaseInvoiceRequest
     */
    frequency: SubscriptionFrequency;
}



/**
 * Check if a given object implements the CreateObligaitonBasedOnPurchaseInvoiceRequest interface.
 */
export function instanceOfCreateObligaitonBasedOnPurchaseInvoiceRequest(value: object): value is CreateObligaitonBasedOnPurchaseInvoiceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('frequency' in value) || value['frequency'] === undefined) return false;
    return true;
}

export function CreateObligaitonBasedOnPurchaseInvoiceRequestFromJSON(json: any): CreateObligaitonBasedOnPurchaseInvoiceRequest {
    return CreateObligaitonBasedOnPurchaseInvoiceRequestFromJSONTyped(json, false);
}

export function CreateObligaitonBasedOnPurchaseInvoiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateObligaitonBasedOnPurchaseInvoiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['start-date'] == null ? undefined : (new Date(json['start-date'])),
        'endDate': json['end-date'] == null ? undefined : (new Date(json['end-date'])),
        'name': json['name'],
        'frequency': SubscriptionFrequencyFromJSON(json['frequency']),
    };
}

export function CreateObligaitonBasedOnPurchaseInvoiceRequestToJSON(json: any): CreateObligaitonBasedOnPurchaseInvoiceRequest {
    return CreateObligaitonBasedOnPurchaseInvoiceRequestToJSONTyped(json, false);
}

export function CreateObligaitonBasedOnPurchaseInvoiceRequestToJSONTyped(value?: CreateObligaitonBasedOnPurchaseInvoiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start-date': value['startDate'] == null ? undefined : ((value['startDate']).toISOString().substring(0,10)),
        'end-date': value['endDate'] == null ? undefined : ((value['endDate']).toISOString().substring(0,10)),
        'name': value['name'],
        'frequency': SubscriptionFrequencyToJSON(value['frequency']),
    };
}

