/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonetaryAccountType } from './MonetaryAccountType';
import {
    MonetaryAccountTypeFromJSON,
    MonetaryAccountTypeFromJSONTyped,
    MonetaryAccountTypeToJSON,
    MonetaryAccountTypeToJSONTyped,
} from './MonetaryAccountType';

/**
 * 
 * @export
 * @interface CreateMonetaryAccountRequest
 */
export interface CreateMonetaryAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateMonetaryAccountRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMonetaryAccountRequest
     */
    ledger?: string;
    /**
     * 
     * @type {MonetaryAccountType}
     * @memberof CreateMonetaryAccountRequest
     */
    type: MonetaryAccountType;
    /**
     * ISO 3166-1 alpha-2 currency code
     * @type {string}
     * @memberof CreateMonetaryAccountRequest
     */
    currency: string;
    /**
     * Free form key/ value pair
     * @type {object}
     * @memberof CreateMonetaryAccountRequest
     */
    metadata?: object;
}



/**
 * Check if a given object implements the CreateMonetaryAccountRequest interface.
 */
export function instanceOfCreateMonetaryAccountRequest(value: object): value is CreateMonetaryAccountRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function CreateMonetaryAccountRequestFromJSON(json: any): CreateMonetaryAccountRequest {
    return CreateMonetaryAccountRequestFromJSONTyped(json, false);
}

export function CreateMonetaryAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMonetaryAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ledger': json['ledger'] == null ? undefined : json['ledger'],
        'type': MonetaryAccountTypeFromJSON(json['type']),
        'currency': json['currency'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateMonetaryAccountRequestToJSON(json: any): CreateMonetaryAccountRequest {
    return CreateMonetaryAccountRequestToJSONTyped(json, false);
}

export function CreateMonetaryAccountRequestToJSONTyped(value?: CreateMonetaryAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'ledger': value['ledger'],
        'type': MonetaryAccountTypeToJSON(value['type']),
        'currency': value['currency'],
        'metadata': value['metadata'],
    };
}

