/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductCategoryRequest
 */
export interface CreateProductCategoryRequest {
    /**
     * Name of the product category
     * @type {string}
     * @memberof CreateProductCategoryRequest
     */
    name: string;
    /**
     * Free form key/ value pair
     * @type {object}
     * @memberof CreateProductCategoryRequest
     */
    metadata?: object;
}

/**
 * Check if a given object implements the CreateProductCategoryRequest interface.
 */
export function instanceOfCreateProductCategoryRequest(value: object): value is CreateProductCategoryRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateProductCategoryRequestFromJSON(json: any): CreateProductCategoryRequest {
    return CreateProductCategoryRequestFromJSONTyped(json, false);
}

export function CreateProductCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductCategoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateProductCategoryRequestToJSON(json: any): CreateProductCategoryRequest {
    return CreateProductCategoryRequestToJSONTyped(json, false);
}

export function CreateProductCategoryRequestToJSONTyped(value?: CreateProductCategoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'metadata': value['metadata'],
    };
}

