/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The details of on how to process the payment, if you book onto a suspense account, you must enter this field in order to process the suspense entries
 * @export
 * @interface CreateMonetaryAccountPaymentRequestInnerProcess
 */
export interface CreateMonetaryAccountPaymentRequestInnerProcess {
    /**
     * The sales invoice ID to attach to the payment
     * @type {string}
     * @memberof CreateMonetaryAccountPaymentRequestInnerProcess
     */
    salesInvoice?: string;
    /**
     * The purchase invoice ID to attach to the payment
     * @type {string}
     * @memberof CreateMonetaryAccountPaymentRequestInnerProcess
     */
    purchaseInvoice?: string;
    /**
     * The debit loan ID to attach to the payment
     * @type {string}
     * @memberof CreateMonetaryAccountPaymentRequestInnerProcess
     */
    debitLoan?: string;
    /**
     * The credit loan ID to attach to the payment
     * @type {string}
     * @memberof CreateMonetaryAccountPaymentRequestInnerProcess
     */
    creditLoan?: string;
    /**
     * The relation ID to attach to the payment
     * @type {string}
     * @memberof CreateMonetaryAccountPaymentRequestInnerProcess
     */
    relation?: string;
    /**
     * The current account ID to attach to the payment
     * @type {string}
     * @memberof CreateMonetaryAccountPaymentRequestInnerProcess
     */
    currentAccount?: string;
}

/**
 * Check if a given object implements the CreateMonetaryAccountPaymentRequestInnerProcess interface.
 */
export function instanceOfCreateMonetaryAccountPaymentRequestInnerProcess(value: object): value is CreateMonetaryAccountPaymentRequestInnerProcess {
    return true;
}

export function CreateMonetaryAccountPaymentRequestInnerProcessFromJSON(json: any): CreateMonetaryAccountPaymentRequestInnerProcess {
    return CreateMonetaryAccountPaymentRequestInnerProcessFromJSONTyped(json, false);
}

export function CreateMonetaryAccountPaymentRequestInnerProcessFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMonetaryAccountPaymentRequestInnerProcess {
    if (json == null) {
        return json;
    }
    return {
        
        'salesInvoice': json['sales-invoice'] == null ? undefined : json['sales-invoice'],
        'purchaseInvoice': json['purchase-invoice'] == null ? undefined : json['purchase-invoice'],
        'debitLoan': json['debit-loan'] == null ? undefined : json['debit-loan'],
        'creditLoan': json['credit-loan'] == null ? undefined : json['credit-loan'],
        'relation': json['relation'] == null ? undefined : json['relation'],
        'currentAccount': json['current-account'] == null ? undefined : json['current-account'],
    };
}

export function CreateMonetaryAccountPaymentRequestInnerProcessToJSON(json: any): CreateMonetaryAccountPaymentRequestInnerProcess {
    return CreateMonetaryAccountPaymentRequestInnerProcessToJSONTyped(json, false);
}

export function CreateMonetaryAccountPaymentRequestInnerProcessToJSONTyped(value?: CreateMonetaryAccountPaymentRequestInnerProcess | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sales-invoice': value['salesInvoice'],
        'purchase-invoice': value['purchaseInvoice'],
        'debit-loan': value['debitLoan'],
        'credit-loan': value['creditLoan'],
        'relation': value['relation'],
        'current-account': value['currentAccount'],
    };
}

