/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRelationsImportRequest
 */
export interface CreateRelationsImportRequest {
    /**
     * The CSV content
     * @type {string}
     * @memberof CreateRelationsImportRequest
     */
    csv?: string;
}

/**
 * Check if a given object implements the CreateRelationsImportRequest interface.
 */
export function instanceOfCreateRelationsImportRequest(value: object): value is CreateRelationsImportRequest {
    return true;
}

export function CreateRelationsImportRequestFromJSON(json: any): CreateRelationsImportRequest {
    return CreateRelationsImportRequestFromJSONTyped(json, false);
}

export function CreateRelationsImportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRelationsImportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'csv': json['csv'] == null ? undefined : json['csv'],
    };
}

export function CreateRelationsImportRequestToJSON(json: any): CreateRelationsImportRequest {
    return CreateRelationsImportRequestToJSONTyped(json, false);
}

export function CreateRelationsImportRequestToJSONTyped(value?: CreateRelationsImportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'csv': value['csv'],
    };
}

