/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateQuoteRequest
 */
export interface CreateQuoteRequest {
    /**
     * ISO 3166-1 alpha-2 currency code
     * @type {string}
     * @memberof CreateQuoteRequest
     */
    currency?: string;
    /**
     * ID of the relation to use
     * @type {string}
     * @memberof CreateQuoteRequest
     */
    relation?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateQuoteRequest
     */
    reference?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateQuoteRequest
     */
    legalName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateQuoteRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateQuoteRequest
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateQuoteRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateQuoteRequest
     */
    memo?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateQuoteRequest
     */
    footer?: string;
    /**
     * Free form key/ value pair
     * @type {{ [key: string]: any; }}
     * @memberof CreateQuoteRequest
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateQuoteRequest interface.
 */
export function instanceOfCreateQuoteRequest(value: object): value is CreateQuoteRequest {
    return true;
}

export function CreateQuoteRequestFromJSON(json: any): CreateQuoteRequest {
    return CreateQuoteRequestFromJSONTyped(json, false);
}

export function CreateQuoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateQuoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'relation': json['relation'] == null ? undefined : json['relation'],
        'reference': json['reference'] == null ? undefined : json['reference'],
        'legalName': json['legal-name'] == null ? undefined : json['legal-name'],
        'firstName': json['first-name'] == null ? undefined : json['first-name'],
        'middleName': json['middle-name'] == null ? undefined : json['middle-name'],
        'lastName': json['last-name'] == null ? undefined : json['last-name'],
        'memo': json['memo'] == null ? undefined : json['memo'],
        'footer': json['footer'] == null ? undefined : json['footer'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateQuoteRequestToJSON(json: any): CreateQuoteRequest {
    return CreateQuoteRequestToJSONTyped(json, false);
}

export function CreateQuoteRequestToJSONTyped(value?: CreateQuoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'relation': value['relation'],
        'reference': value['reference'],
        'legal-name': value['legalName'],
        'first-name': value['firstName'],
        'middle-name': value['middleName'],
        'last-name': value['lastName'],
        'memo': value['memo'],
        'footer': value['footer'],
        'metadata': value['metadata'],
    };
}

