/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePurchaseInvoicePaymentRequest
 */
export interface CreatePurchaseInvoicePaymentRequest {
    /**
     * Monetary account ID
     * @type {string}
     * @memberof CreatePurchaseInvoicePaymentRequest
     */
    monetaryAccount: string;
    /**
     * 
     * @type {Date}
     * @memberof CreatePurchaseInvoicePaymentRequest
     */
    execution?: Date;
    /**
     * Non required field of the amount that should be paid, defaults to total invoice amount
     * @type {number}
     * @memberof CreatePurchaseInvoicePaymentRequest
     */
    amount?: number;
}

/**
 * Check if a given object implements the CreatePurchaseInvoicePaymentRequest interface.
 */
export function instanceOfCreatePurchaseInvoicePaymentRequest(value: object): value is CreatePurchaseInvoicePaymentRequest {
    if (!('monetaryAccount' in value) || value['monetaryAccount'] === undefined) return false;
    return true;
}

export function CreatePurchaseInvoicePaymentRequestFromJSON(json: any): CreatePurchaseInvoicePaymentRequest {
    return CreatePurchaseInvoicePaymentRequestFromJSONTyped(json, false);
}

export function CreatePurchaseInvoicePaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePurchaseInvoicePaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'monetaryAccount': json['monetary-account'],
        'execution': json['execution'] == null ? undefined : (new Date(json['execution'])),
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function CreatePurchaseInvoicePaymentRequestToJSON(json: any): CreatePurchaseInvoicePaymentRequest {
    return CreatePurchaseInvoicePaymentRequestToJSONTyped(json, false);
}

export function CreatePurchaseInvoicePaymentRequestToJSONTyped(value?: CreatePurchaseInvoicePaymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'monetary-account': value['monetaryAccount'],
        'execution': value['execution'] == null ? undefined : ((value['execution']).toISOString().substring(0,10)),
        'amount': value['amount'],
    };
}

