/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateChat200ResponseMessagesInnerFunctionsValueInner } from './CreateChat200ResponseMessagesInnerFunctionsValueInner';
import {
    CreateChat200ResponseMessagesInnerFunctionsValueInnerFromJSON,
    CreateChat200ResponseMessagesInnerFunctionsValueInnerFromJSONTyped,
    CreateChat200ResponseMessagesInnerFunctionsValueInnerToJSON,
    CreateChat200ResponseMessagesInnerFunctionsValueInnerToJSONTyped,
} from './CreateChat200ResponseMessagesInnerFunctionsValueInner';

/**
 * 
 * @export
 * @interface CreateChat200ResponseMessagesInner
 */
export interface CreateChat200ResponseMessagesInner {
    /**
     * 
     * @type {string}
     * @memberof CreateChat200ResponseMessagesInner
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChat200ResponseMessagesInner
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChat200ResponseMessagesInner
     */
    source: CreateChat200ResponseMessagesInnerSourceEnum;
    /**
     * 
     * @type {{ [key: string]: Array<CreateChat200ResponseMessagesInnerFunctionsValueInner>; }}
     * @memberof CreateChat200ResponseMessagesInner
     */
    functions?: { [key: string]: Array<CreateChat200ResponseMessagesInnerFunctionsValueInner>; };
    /**
     * 
     * @type {Date}
     * @memberof CreateChat200ResponseMessagesInner
     */
    readonly created: Date;
}


/**
 * @export
 */
export const CreateChat200ResponseMessagesInnerSourceEnum = {
    Ai: 'ai',
    User: 'user'
} as const;
export type CreateChat200ResponseMessagesInnerSourceEnum = typeof CreateChat200ResponseMessagesInnerSourceEnum[keyof typeof CreateChat200ResponseMessagesInnerSourceEnum];


/**
 * Check if a given object implements the CreateChat200ResponseMessagesInner interface.
 */
export function instanceOfCreateChat200ResponseMessagesInner(value: object): value is CreateChat200ResponseMessagesInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function CreateChat200ResponseMessagesInnerFromJSON(json: any): CreateChat200ResponseMessagesInner {
    return CreateChat200ResponseMessagesInnerFromJSONTyped(json, false);
}

export function CreateChat200ResponseMessagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChat200ResponseMessagesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'] == null ? undefined : json['content'],
        'source': json['source'],
        'functions': json['functions'] == null ? undefined : json['functions'],
        'created': (new Date(json['created'])),
    };
}

export function CreateChat200ResponseMessagesInnerToJSON(json: any): CreateChat200ResponseMessagesInner {
    return CreateChat200ResponseMessagesInnerToJSONTyped(json, false);
}

export function CreateChat200ResponseMessagesInnerToJSONTyped(value?: Omit<CreateChat200ResponseMessagesInner, 'id'|'created'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'source': value['source'],
        'functions': value['functions'],
    };
}

