/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset
 */
export interface CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset {
    /**
     * 
     * @type {string}
     * @memberof CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset
     */
    code?: string;
    /**
     * Lifespan in months
     * @type {number}
     * @memberof CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset
     */
    lifespan: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset
     */
    residualValue: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset
     */
    ledger: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset
     */
    writeoffLedger: string;
    /**
     * Free form key/ value pair
     * @type {object}
     * @memberof CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset
     */
    metadata?: object;
}

/**
 * Check if a given object implements the CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset interface.
 */
export function instanceOfCreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset(value: object): value is CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset {
    if (!('lifespan' in value) || value['lifespan'] === undefined) return false;
    if (!('residualValue' in value) || value['residualValue'] === undefined) return false;
    if (!('ledger' in value) || value['ledger'] === undefined) return false;
    if (!('writeoffLedger' in value) || value['writeoffLedger'] === undefined) return false;
    return true;
}

export function CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2AssetFromJSON(json: any): CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset {
    return CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2AssetFromJSONTyped(json, false);
}

export function CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2AssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'lifespan': json['lifespan'],
        'residualValue': json['residual_value'],
        'ledger': json['ledger'],
        'writeoffLedger': json['writeoff_ledger'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2AssetToJSON(json: any): CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset {
    return CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2AssetToJSONTyped(json, false);
}

export function CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2AssetToJSONTyped(value?: CreatePurchaseInvoiceFinalRequestLinesInnerOneOf2Asset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'lifespan': value['lifespan'],
        'residual_value': value['residualValue'],
        'ledger': value['ledger'],
        'writeoff_ledger': value['writeoffLedger'],
        'metadata': value['metadata'],
    };
}

