/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatePurchaseInvoiceFinalRequestFile } from './CreatePurchaseInvoiceFinalRequestFile';
import {
    CreatePurchaseInvoiceFinalRequestFileFromJSON,
    CreatePurchaseInvoiceFinalRequestFileFromJSONTyped,
    CreatePurchaseInvoiceFinalRequestFileToJSON,
    CreatePurchaseInvoiceFinalRequestFileToJSONTyped,
} from './CreatePurchaseInvoiceFinalRequestFile';
import type { CreatePackingSlibRequestLinesInner } from './CreatePackingSlibRequestLinesInner';
import {
    CreatePackingSlibRequestLinesInnerFromJSON,
    CreatePackingSlibRequestLinesInnerFromJSONTyped,
    CreatePackingSlibRequestLinesInnerToJSON,
    CreatePackingSlibRequestLinesInnerToJSONTyped,
} from './CreatePackingSlibRequestLinesInner';

/**
 * 
 * @export
 * @interface CreatePackingSlibRequest
 */
export interface CreatePackingSlibRequest {
    /**
     * ISO 3166-1 alpha-2 currency code
     * @type {string}
     * @memberof CreatePackingSlibRequest
     */
    currency: string;
    /**
     * Packing slib number
     * @type {string}
     * @memberof CreatePackingSlibRequest
     */
    number?: string;
    /**
     * Packing slib of the purchase order
     * @type {string}
     * @memberof CreatePackingSlibRequest
     */
    purchaseOrder: string;
    /**
     * 
     * @type {CreatePurchaseInvoiceFinalRequestFile}
     * @memberof CreatePackingSlibRequest
     */
    file?: CreatePurchaseInvoiceFinalRequestFile;
    /**
     * ID of the relation to use
     * @type {string}
     * @memberof CreatePackingSlibRequest
     */
    relation: string;
    /**
     * Date of the invoice
     * @type {Date}
     * @memberof CreatePackingSlibRequest
     */
    date: Date;
    /**
     * Free form key/ value pair
     * @type {{ [key: string]: any; }}
     * @memberof CreatePackingSlibRequest
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {Array<CreatePackingSlibRequestLinesInner>}
     * @memberof CreatePackingSlibRequest
     */
    lines: Array<CreatePackingSlibRequestLinesInner>;
}

/**
 * Check if a given object implements the CreatePackingSlibRequest interface.
 */
export function instanceOfCreatePackingSlibRequest(value: object): value is CreatePackingSlibRequest {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('purchaseOrder' in value) || value['purchaseOrder'] === undefined) return false;
    if (!('relation' in value) || value['relation'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('lines' in value) || value['lines'] === undefined) return false;
    return true;
}

export function CreatePackingSlibRequestFromJSON(json: any): CreatePackingSlibRequest {
    return CreatePackingSlibRequestFromJSONTyped(json, false);
}

export function CreatePackingSlibRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePackingSlibRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'number': json['number'] == null ? undefined : json['number'],
        'purchaseOrder': json['purchase-order'],
        'file': json['file'] == null ? undefined : CreatePurchaseInvoiceFinalRequestFileFromJSON(json['file']),
        'relation': json['relation'],
        'date': (new Date(json['date'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'lines': ((json['lines'] as Array<any>).map(CreatePackingSlibRequestLinesInnerFromJSON)),
    };
}

export function CreatePackingSlibRequestToJSON(json: any): CreatePackingSlibRequest {
    return CreatePackingSlibRequestToJSONTyped(json, false);
}

export function CreatePackingSlibRequestToJSONTyped(value?: CreatePackingSlibRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'number': value['number'],
        'purchase-order': value['purchaseOrder'],
        'file': CreatePurchaseInvoiceFinalRequestFileToJSON(value['file']),
        'relation': value['relation'],
        'date': ((value['date']).toISOString().substring(0,10)),
        'metadata': value['metadata'],
        'lines': ((value['lines'] as Array<any>).map(CreatePackingSlibRequestLinesInnerToJSON)),
    };
}

