/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateExpenseCategoryRequest
 */
export interface CreateExpenseCategoryRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateExpenseCategoryRequest
     */
    name: string;
    /**
     * Numberical number that represents the ledger
     * @type {string}
     * @memberof CreateExpenseCategoryRequest
     */
    ledger: string;
    /**
     * ID of the ledger that falls below
     * @type {string}
     * @memberof CreateExpenseCategoryRequest
     */
    category?: string;
    /**
     * Free form key/ value pair
     * @type {object}
     * @memberof CreateExpenseCategoryRequest
     */
    metadata?: object;
}

/**
 * Check if a given object implements the CreateExpenseCategoryRequest interface.
 */
export function instanceOfCreateExpenseCategoryRequest(value: object): value is CreateExpenseCategoryRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ledger' in value) || value['ledger'] === undefined) return false;
    return true;
}

export function CreateExpenseCategoryRequestFromJSON(json: any): CreateExpenseCategoryRequest {
    return CreateExpenseCategoryRequestFromJSONTyped(json, false);
}

export function CreateExpenseCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExpenseCategoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ledger': json['ledger'],
        'category': json['category'] == null ? undefined : json['category'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateExpenseCategoryRequestToJSON(json: any): CreateExpenseCategoryRequest {
    return CreateExpenseCategoryRequestToJSONTyped(json, false);
}

export function CreateExpenseCategoryRequestToJSONTyped(value?: CreateExpenseCategoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'ledger': value['ledger'],
        'category': value['category'],
        'metadata': value['metadata'],
    };
}

