/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePurchaseInvoicePayment200Response
 */
export interface CreatePurchaseInvoicePayment200Response {
    /**
     * Redirect URL for authorisation
     * @type {string}
     * @memberof CreatePurchaseInvoicePayment200Response
     */
    redirect?: string;
}

/**
 * Check if a given object implements the CreatePurchaseInvoicePayment200Response interface.
 */
export function instanceOfCreatePurchaseInvoicePayment200Response(value: object): value is CreatePurchaseInvoicePayment200Response {
    return true;
}

export function CreatePurchaseInvoicePayment200ResponseFromJSON(json: any): CreatePurchaseInvoicePayment200Response {
    return CreatePurchaseInvoicePayment200ResponseFromJSONTyped(json, false);
}

export function CreatePurchaseInvoicePayment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePurchaseInvoicePayment200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'redirect': json['redirect'] == null ? undefined : json['redirect'],
    };
}

export function CreatePurchaseInvoicePayment200ResponseToJSON(json: any): CreatePurchaseInvoicePayment200Response {
    return CreatePurchaseInvoicePayment200ResponseToJSONTyped(json, false);
}

export function CreatePurchaseInvoicePayment200ResponseToJSONTyped(value?: CreatePurchaseInvoicePayment200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirect': value['redirect'],
    };
}

