/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductRequest
 */
export interface CreateProductRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProductRequest
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    type?: CreateProductRequestTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateProductRequest
     */
    taxCodes: Array<CreateProductRequestTaxCodesEnum>;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    expenseCategory?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    balanceCategory?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    revenueCategory?: string;
    /**
     * Free form key/ value pair
     * @type {object}
     * @memberof CreateProductRequest
     */
    metadata?: object;
}


/**
 * @export
 */
export const CreateProductRequestTypeEnum = {
    Goods: 'goods',
    Services: 'services'
} as const;
export type CreateProductRequestTypeEnum = typeof CreateProductRequestTypeEnum[keyof typeof CreateProductRequestTypeEnum];

/**
 * @export
 */
export const CreateProductRequestTaxCodesEnum = {
    Nl2012High: 'NL_2012_HIGH',
    Nl2019Low: 'NL_2019_LOW',
    Nl2001High: 'NL_2001_HIGH',
    Nl2001Low: 'NL_2001_LOW',
    Nl2024Exempt: 'NL_2024_EXEMPT',
    Nl2024Null: 'NL_2024_NULL',
    Nl2024Transfer: 'NL_2024_TRANSFER',
    EuDirective2006112EcArticle40: 'EU_Directive_2006/112/EC_Article_40'
} as const;
export type CreateProductRequestTaxCodesEnum = typeof CreateProductRequestTaxCodesEnum[keyof typeof CreateProductRequestTaxCodesEnum];


/**
 * Check if a given object implements the CreateProductRequest interface.
 */
export function instanceOfCreateProductRequest(value: object): value is CreateProductRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('taxCodes' in value) || value['taxCodes'] === undefined) return false;
    return true;
}

export function CreateProductRequestFromJSON(json: any): CreateProductRequest {
    return CreateProductRequestFromJSONTyped(json, false);
}

export function CreateProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'],
        'price': json['price'],
        'type': json['type'] == null ? undefined : json['type'],
        'taxCodes': json['tax-codes'],
        'category': json['category'] == null ? undefined : json['category'],
        'expenseCategory': json['expense-category'] == null ? undefined : json['expense-category'],
        'balanceCategory': json['balance-category'] == null ? undefined : json['balance-category'],
        'revenueCategory': json['revenue-category'] == null ? undefined : json['revenue-category'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateProductRequestToJSON(json: any): CreateProductRequest {
    return CreateProductRequestToJSONTyped(json, false);
}

export function CreateProductRequestToJSONTyped(value?: CreateProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        'price': value['price'],
        'type': value['type'],
        'tax-codes': value['taxCodes'],
        'category': value['category'],
        'expense-category': value['expenseCategory'],
        'balance-category': value['balanceCategory'],
        'revenue-category': value['revenueCategory'],
        'metadata': value['metadata'],
    };
}

