/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReminderRequest
 */
export interface CreateReminderRequest {
    /**
     * ISO 3166-1 alpha-2 currency code
     * @type {string}
     * @memberof CreateReminderRequest
     */
    currency?: string;
    /**
     * ID of the relation to use
     * @type {string}
     * @memberof CreateReminderRequest
     */
    relation?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReminderRequest
     */
    legalName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReminderRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReminderRequest
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReminderRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReminderRequest
     */
    content?: string;
    /**
     * Free form key/ value pair
     * @type {object}
     * @memberof CreateReminderRequest
     */
    metadata?: object;
}

/**
 * Check if a given object implements the CreateReminderRequest interface.
 */
export function instanceOfCreateReminderRequest(value: object): value is CreateReminderRequest {
    return true;
}

export function CreateReminderRequestFromJSON(json: any): CreateReminderRequest {
    return CreateReminderRequestFromJSONTyped(json, false);
}

export function CreateReminderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReminderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'] == null ? undefined : json['currency'],
        'relation': json['relation'] == null ? undefined : json['relation'],
        'legalName': json['legal-name'] == null ? undefined : json['legal-name'],
        'firstName': json['first-name'] == null ? undefined : json['first-name'],
        'middleName': json['middle-name'] == null ? undefined : json['middle-name'],
        'lastName': json['last-name'] == null ? undefined : json['last-name'],
        'content': json['content'] == null ? undefined : json['content'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateReminderRequestToJSON(json: any): CreateReminderRequest {
    return CreateReminderRequestToJSONTyped(json, false);
}

export function CreateReminderRequestToJSONTyped(value?: CreateReminderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'relation': value['relation'],
        'legal-name': value['legalName'],
        'first-name': value['firstName'],
        'middle-name': value['middleName'],
        'last-name': value['lastName'],
        'content': value['content'],
        'metadata': value['metadata'],
    };
}

