/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProfileRequestSettingsEmailSmtp
 */
export interface CreateProfileRequestSettingsEmailSmtp {
    /**
     * The SMTP host
     * @type {string}
     * @memberof CreateProfileRequestSettingsEmailSmtp
     */
    host: string;
    /**
     * The username of the SMTP host
     * @type {string}
     * @memberof CreateProfileRequestSettingsEmailSmtp
     */
    username: string;
    /**
     * The password of the SMTP host
     * @type {string}
     * @memberof CreateProfileRequestSettingsEmailSmtp
     */
    password: string;
}

/**
 * Check if a given object implements the CreateProfileRequestSettingsEmailSmtp interface.
 */
export function instanceOfCreateProfileRequestSettingsEmailSmtp(value: object): value is CreateProfileRequestSettingsEmailSmtp {
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function CreateProfileRequestSettingsEmailSmtpFromJSON(json: any): CreateProfileRequestSettingsEmailSmtp {
    return CreateProfileRequestSettingsEmailSmtpFromJSONTyped(json, false);
}

export function CreateProfileRequestSettingsEmailSmtpFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProfileRequestSettingsEmailSmtp {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function CreateProfileRequestSettingsEmailSmtpToJSON(json: any): CreateProfileRequestSettingsEmailSmtp {
    return CreateProfileRequestSettingsEmailSmtpToJSONTyped(json, false);
}

export function CreateProfileRequestSettingsEmailSmtpToJSONTyped(value?: CreateProfileRequestSettingsEmailSmtp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'host': value['host'],
        'username': value['username'],
        'password': value['password'],
    };
}

