/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePurchaseInvoiceFinalRequestFile
 */
export interface CreatePurchaseInvoiceFinalRequestFile {
    /**
     * 
     * @type {string}
     * @memberof CreatePurchaseInvoiceFinalRequestFile
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePurchaseInvoiceFinalRequestFile
     */
    mime: string;
    /**
     * base64 encoded string of the binary file
     * @type {string}
     * @memberof CreatePurchaseInvoiceFinalRequestFile
     */
    data: string;
}

/**
 * Check if a given object implements the CreatePurchaseInvoiceFinalRequestFile interface.
 */
export function instanceOfCreatePurchaseInvoiceFinalRequestFile(value: object): value is CreatePurchaseInvoiceFinalRequestFile {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('mime' in value) || value['mime'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreatePurchaseInvoiceFinalRequestFileFromJSON(json: any): CreatePurchaseInvoiceFinalRequestFile {
    return CreatePurchaseInvoiceFinalRequestFileFromJSONTyped(json, false);
}

export function CreatePurchaseInvoiceFinalRequestFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePurchaseInvoiceFinalRequestFile {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'mime': json['mime'],
        'data': json['data'],
    };
}

export function CreatePurchaseInvoiceFinalRequestFileToJSON(json: any): CreatePurchaseInvoiceFinalRequestFile {
    return CreatePurchaseInvoiceFinalRequestFileToJSONTyped(json, false);
}

export function CreatePurchaseInvoiceFinalRequestFileToJSONTyped(value?: CreatePurchaseInvoiceFinalRequestFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'mime': value['mime'],
        'data': value['data'],
    };
}

