/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRelationRequestBankIban
 */
export interface CreateRelationRequestBankIban {
    /**
     * ISO 3166-1 alpha-2 country code
     * @type {string}
     * @memberof CreateRelationRequestBankIban
     */
    country: string;
    /**
     * International Bank Account Number
     * @type {string}
     * @memberof CreateRelationRequestBankIban
     */
    iban: string;
    /**
     * BIC code for IBAN
     * @type {string}
     * @memberof CreateRelationRequestBankIban
     */
    bic: string;
    /**
     * Holder name
     * @type {string}
     * @memberof CreateRelationRequestBankIban
     */
    holderName: string;
}

/**
 * Check if a given object implements the CreateRelationRequestBankIban interface.
 */
export function instanceOfCreateRelationRequestBankIban(value: object): value is CreateRelationRequestBankIban {
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('iban' in value) || value['iban'] === undefined) return false;
    if (!('bic' in value) || value['bic'] === undefined) return false;
    if (!('holderName' in value) || value['holderName'] === undefined) return false;
    return true;
}

export function CreateRelationRequestBankIbanFromJSON(json: any): CreateRelationRequestBankIban {
    return CreateRelationRequestBankIbanFromJSONTyped(json, false);
}

export function CreateRelationRequestBankIbanFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRelationRequestBankIban {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'],
        'iban': json['iban'],
        'bic': json['bic'],
        'holderName': json['holder_name'],
    };
}

export function CreateRelationRequestBankIbanToJSON(json: any): CreateRelationRequestBankIban {
    return CreateRelationRequestBankIbanToJSONTyped(json, false);
}

export function CreateRelationRequestBankIbanToJSONTyped(value?: CreateRelationRequestBankIban | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country': value['country'],
        'iban': value['iban'],
        'bic': value['bic'],
        'holder_name': value['holderName'],
    };
}

