/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMonetaryAccountOpenbankingAuthorisation201Response
 */
export interface CreateMonetaryAccountOpenbankingAuthorisation201Response {
    /**
     * 
     * @type {string}
     * @memberof CreateMonetaryAccountOpenbankingAuthorisation201Response
     */
    url?: string;
}

/**
 * Check if a given object implements the CreateMonetaryAccountOpenbankingAuthorisation201Response interface.
 */
export function instanceOfCreateMonetaryAccountOpenbankingAuthorisation201Response(value: object): value is CreateMonetaryAccountOpenbankingAuthorisation201Response {
    return true;
}

export function CreateMonetaryAccountOpenbankingAuthorisation201ResponseFromJSON(json: any): CreateMonetaryAccountOpenbankingAuthorisation201Response {
    return CreateMonetaryAccountOpenbankingAuthorisation201ResponseFromJSONTyped(json, false);
}

export function CreateMonetaryAccountOpenbankingAuthorisation201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMonetaryAccountOpenbankingAuthorisation201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function CreateMonetaryAccountOpenbankingAuthorisation201ResponseToJSON(json: any): CreateMonetaryAccountOpenbankingAuthorisation201Response {
    return CreateMonetaryAccountOpenbankingAuthorisation201ResponseToJSONTyped(json, false);
}

export function CreateMonetaryAccountOpenbankingAuthorisation201ResponseToJSONTyped(value?: CreateMonetaryAccountOpenbankingAuthorisation201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

