/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMonetaryAccountBankPaymentRequest
 */
export interface CreateMonetaryAccountBankPaymentRequest {
    /**
     * Relation ID
     * @type {string}
     * @memberof CreateMonetaryAccountBankPaymentRequest
     */
    relation: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateMonetaryAccountBankPaymentRequest
     */
    execution?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateMonetaryAccountBankPaymentRequest
     */
    description?: string;
    /**
     * Non required field of the amount that should be paid, defaults to total invoice amount
     * @type {number}
     * @memberof CreateMonetaryAccountBankPaymentRequest
     */
    amount: number;
}

/**
 * Check if a given object implements the CreateMonetaryAccountBankPaymentRequest interface.
 */
export function instanceOfCreateMonetaryAccountBankPaymentRequest(value: object): value is CreateMonetaryAccountBankPaymentRequest {
    if (!('relation' in value) || value['relation'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CreateMonetaryAccountBankPaymentRequestFromJSON(json: any): CreateMonetaryAccountBankPaymentRequest {
    return CreateMonetaryAccountBankPaymentRequestFromJSONTyped(json, false);
}

export function CreateMonetaryAccountBankPaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMonetaryAccountBankPaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'relation': json['relation'],
        'execution': json['execution'] == null ? undefined : (new Date(json['execution'])),
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'],
    };
}

export function CreateMonetaryAccountBankPaymentRequestToJSON(json: any): CreateMonetaryAccountBankPaymentRequest {
    return CreateMonetaryAccountBankPaymentRequestToJSONTyped(json, false);
}

export function CreateMonetaryAccountBankPaymentRequestToJSONTyped(value?: CreateMonetaryAccountBankPaymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relation': value['relation'],
        'execution': value['execution'] == null ? undefined : ((value['execution']).toISOString().substring(0,10)),
        'description': value['description'],
        'amount': value['amount'],
    };
}

