/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionFrequency } from './SubscriptionFrequency';
import {
    SubscriptionFrequencyFromJSON,
    SubscriptionFrequencyFromJSONTyped,
    SubscriptionFrequencyToJSON,
    SubscriptionFrequencyToJSONTyped,
} from './SubscriptionFrequency';

/**
 * 
 * @export
 * @interface CreateSubscriptionBasedOnSalesInvoiceRequest
 */
export interface CreateSubscriptionBasedOnSalesInvoiceRequest {
    /**
     * 
     * @type {Date}
     * @memberof CreateSubscriptionBasedOnSalesInvoiceRequest
     */
    endDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateSubscriptionBasedOnSalesInvoiceRequest
     */
    canceled?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateSubscriptionBasedOnSalesInvoiceRequest
     */
    name: string;
    /**
     * 
     * @type {SubscriptionFrequency}
     * @memberof CreateSubscriptionBasedOnSalesInvoiceRequest
     */
    frequency: SubscriptionFrequency;
    /**
     * Free form key/ value pair
     * @type {object}
     * @memberof CreateSubscriptionBasedOnSalesInvoiceRequest
     */
    metadata?: object;
}



/**
 * Check if a given object implements the CreateSubscriptionBasedOnSalesInvoiceRequest interface.
 */
export function instanceOfCreateSubscriptionBasedOnSalesInvoiceRequest(value: object): value is CreateSubscriptionBasedOnSalesInvoiceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('frequency' in value) || value['frequency'] === undefined) return false;
    return true;
}

export function CreateSubscriptionBasedOnSalesInvoiceRequestFromJSON(json: any): CreateSubscriptionBasedOnSalesInvoiceRequest {
    return CreateSubscriptionBasedOnSalesInvoiceRequestFromJSONTyped(json, false);
}

export function CreateSubscriptionBasedOnSalesInvoiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubscriptionBasedOnSalesInvoiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'endDate': json['end-date'] == null ? undefined : (new Date(json['end-date'])),
        'canceled': json['canceled'] == null ? undefined : (new Date(json['canceled'])),
        'name': json['name'],
        'frequency': SubscriptionFrequencyFromJSON(json['frequency']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateSubscriptionBasedOnSalesInvoiceRequestToJSON(json: any): CreateSubscriptionBasedOnSalesInvoiceRequest {
    return CreateSubscriptionBasedOnSalesInvoiceRequestToJSONTyped(json, false);
}

export function CreateSubscriptionBasedOnSalesInvoiceRequestToJSONTyped(value?: CreateSubscriptionBasedOnSalesInvoiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end-date': value['endDate'] == null ? undefined : ((value['endDate']).toISOString().substring(0,10)),
        'canceled': value['canceled'] == null ? undefined : ((value['canceled']).toISOString().substring(0,10)),
        'name': value['name'],
        'frequency': SubscriptionFrequencyToJSON(value['frequency']),
        'metadata': value['metadata'],
    };
}

