/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VATFilingType } from './VATFilingType';
import {
    VATFilingTypeFromJSON,
    VATFilingTypeFromJSONTyped,
    VATFilingTypeToJSON,
    VATFilingTypeToJSONTyped,
} from './VATFilingType';

/**
 * 
 * @export
 * @interface CreateVATFilingRequest
 */
export interface CreateVATFilingRequest {
    /**
     * 
     * @type {VATFilingType}
     * @memberof CreateVATFilingRequest
     */
    type: VATFilingType;
    /**
     * 
     * @type {Date}
     * @memberof CreateVATFilingRequest
     */
    readonly from: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateVATFilingRequest
     */
    readonly to: Date;
}



/**
 * Check if a given object implements the CreateVATFilingRequest interface.
 */
export function instanceOfCreateVATFilingRequest(value: object): value is CreateVATFilingRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function CreateVATFilingRequestFromJSON(json: any): CreateVATFilingRequest {
    return CreateVATFilingRequestFromJSONTyped(json, false);
}

export function CreateVATFilingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVATFilingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': VATFilingTypeFromJSON(json['type']),
        'from': (new Date(json['from'])),
        'to': (new Date(json['to'])),
    };
}

export function CreateVATFilingRequestToJSON(json: any): CreateVATFilingRequest {
    return CreateVATFilingRequestToJSONTyped(json, false);
}

export function CreateVATFilingRequestToJSONTyped(value?: Omit<CreateVATFilingRequest, 'from'|'to'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': VATFilingTypeToJSON(value['type']),
    };
}

