/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditSalesInvoiceRequest
 */
export interface CreditSalesInvoiceRequest {
    /**
     * 
     * @type {boolean}
     * @memberof CreditSalesInvoiceRequest
     */
    close?: boolean;
}

/**
 * Check if a given object implements the CreditSalesInvoiceRequest interface.
 */
export function instanceOfCreditSalesInvoiceRequest(value: object): value is CreditSalesInvoiceRequest {
    return true;
}

export function CreditSalesInvoiceRequestFromJSON(json: any): CreditSalesInvoiceRequest {
    return CreditSalesInvoiceRequestFromJSONTyped(json, false);
}

export function CreditSalesInvoiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditSalesInvoiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'close': json['close'] == null ? undefined : json['close'],
    };
}

export function CreditSalesInvoiceRequestToJSON(json: any): CreditSalesInvoiceRequest {
    return CreditSalesInvoiceRequestToJSONTyped(json, false);
}

export function CreditSalesInvoiceRequestToJSONTyped(value?: CreditSalesInvoiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'close': value['close'],
    };
}

