/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteObligationRequest
 */
export interface DeleteObligationRequest {
    /**
     * Date on which the Obligation should be cenacelled
     * @type {Date}
     * @memberof DeleteObligationRequest
     */
    canceled?: Date;
}

/**
 * Check if a given object implements the DeleteObligationRequest interface.
 */
export function instanceOfDeleteObligationRequest(value: object): value is DeleteObligationRequest {
    return true;
}

export function DeleteObligationRequestFromJSON(json: any): DeleteObligationRequest {
    return DeleteObligationRequestFromJSONTyped(json, false);
}

export function DeleteObligationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteObligationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'canceled': json['canceled'] == null ? undefined : (new Date(json['canceled'])),
    };
}

export function DeleteObligationRequestToJSON(json: any): DeleteObligationRequest {
    return DeleteObligationRequestToJSONTyped(json, false);
}

export function DeleteObligationRequestToJSONTyped(value?: DeleteObligationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'canceled': value['canceled'] == null ? undefined : ((value['canceled']).toISOString().substring(0,10)),
    };
}

