/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForbiddenError
 */
export interface ForbiddenError {
    /**
     * 
     * @type {string}
     * @memberof ForbiddenError
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof ForbiddenError
     */
    errorDescription?: string;
}

/**
 * Check if a given object implements the ForbiddenError interface.
 */
export function instanceOfForbiddenError(value: object): value is ForbiddenError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ForbiddenErrorFromJSON(json: any): ForbiddenError {
    return ForbiddenErrorFromJSONTyped(json, false);
}

export function ForbiddenErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForbiddenError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'errorDescription': json['error_description'] == null ? undefined : json['error_description'],
    };
}

export function ForbiddenErrorToJSON(json: any): ForbiddenError {
    return ForbiddenErrorToJSONTyped(json, false);
}

export function ForbiddenErrorToJSONTyped(value?: ForbiddenError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'error_description': value['errorDescription'],
    };
}

