/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAllMonetaryAccountPaymentsDateParameter
 */
export interface GetAllMonetaryAccountPaymentsDateParameter {
    /**
     * 
     * @type {Date}
     * @memberof GetAllMonetaryAccountPaymentsDateParameter
     */
    min?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetAllMonetaryAccountPaymentsDateParameter
     */
    max?: Date;
}

/**
 * Check if a given object implements the GetAllMonetaryAccountPaymentsDateParameter interface.
 */
export function instanceOfGetAllMonetaryAccountPaymentsDateParameter(value: object): value is GetAllMonetaryAccountPaymentsDateParameter {
    return true;
}

export function GetAllMonetaryAccountPaymentsDateParameterFromJSON(json: any): GetAllMonetaryAccountPaymentsDateParameter {
    return GetAllMonetaryAccountPaymentsDateParameterFromJSONTyped(json, false);
}

export function GetAllMonetaryAccountPaymentsDateParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllMonetaryAccountPaymentsDateParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'min': json['min'] == null ? undefined : (new Date(json['min'])),
        'max': json['max'] == null ? undefined : (new Date(json['max'])),
    };
}

export function GetAllMonetaryAccountPaymentsDateParameterToJSON(json: any): GetAllMonetaryAccountPaymentsDateParameter {
    return GetAllMonetaryAccountPaymentsDateParameterToJSONTyped(json, false);
}

export function GetAllMonetaryAccountPaymentsDateParameterToJSONTyped(value?: GetAllMonetaryAccountPaymentsDateParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min': value['min'] == null ? undefined : ((value['min']).toISOString().substring(0,10)),
        'max': value['max'] == null ? undefined : ((value['max']).toISOString().substring(0,10)),
    };
}

