/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Employee } from './Employee';
import {
    EmployeeFromJSON,
    EmployeeFromJSONTyped,
    EmployeeToJSON,
    EmployeeToJSONTyped,
} from './Employee';

/**
 * 
 * @export
 * @interface GetEmployees200Response
 */
export interface GetEmployees200Response {
    /**
     * The current page
     * @type {number}
     * @memberof GetEmployees200Response
     */
    page: number;
    /**
     * The total number of pages
     * @type {number}
     * @memberof GetEmployees200Response
     */
    pages: number;
    /**
     * Size of the page returned
     * @type {number}
     * @memberof GetEmployees200Response
     */
    size: number;
    /**
     * The total count of the resource
     * @type {number}
     * @memberof GetEmployees200Response
     */
    count: number;
    /**
     * 
     * @type {Array<Employee>}
     * @memberof GetEmployees200Response
     */
    data: Array<Employee>;
}

/**
 * Check if a given object implements the GetEmployees200Response interface.
 */
export function instanceOfGetEmployees200Response(value: object): value is GetEmployees200Response {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pages' in value) || value['pages'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetEmployees200ResponseFromJSON(json: any): GetEmployees200Response {
    return GetEmployees200ResponseFromJSONTyped(json, false);
}

export function GetEmployees200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmployees200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pages': json['pages'],
        'size': json['size'],
        'count': json['count'],
        'data': ((json['data'] as Array<any>).map(EmployeeFromJSON)),
    };
}

export function GetEmployees200ResponseToJSON(json: any): GetEmployees200Response {
    return GetEmployees200ResponseToJSONTyped(json, false);
}

export function GetEmployees200ResponseToJSONTyped(value?: GetEmployees200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pages': value['pages'],
        'size': value['size'],
        'count': value['count'],
        'data': ((value['data'] as Array<any>).map(EmployeeToJSON)),
    };
}

