/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProfileFinancialLedger200ResponseInner
 */
export interface GetProfileFinancialLedger200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof GetProfileFinancialLedger200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetProfileFinancialLedger200ResponseInner
     */
    correlation?: string;
    /**
     * 
     * @type {number}
     * @memberof GetProfileFinancialLedger200ResponseInner
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof GetProfileFinancialLedger200ResponseInner
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof GetProfileFinancialLedger200ResponseInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof GetProfileFinancialLedger200ResponseInner
     */
    ledger: string;
    /**
     * 
     * @type {Date}
     * @memberof GetProfileFinancialLedger200ResponseInner
     */
    date: Date;
    /**
     * Indicates if the booking is a 'copy' of another booking
     * @type {boolean}
     * @memberof GetProfileFinancialLedger200ResponseInner
     */
    generated?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof GetProfileFinancialLedger200ResponseInner
     */
    created: Date;
}

/**
 * Check if a given object implements the GetProfileFinancialLedger200ResponseInner interface.
 */
export function instanceOfGetProfileFinancialLedger200ResponseInner(value: object): value is GetProfileFinancialLedger200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('ledger' in value) || value['ledger'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function GetProfileFinancialLedger200ResponseInnerFromJSON(json: any): GetProfileFinancialLedger200ResponseInner {
    return GetProfileFinancialLedger200ResponseInnerFromJSONTyped(json, false);
}

export function GetProfileFinancialLedger200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileFinancialLedger200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'correlation': json['correlation'] == null ? undefined : json['correlation'],
        'amount': json['amount'],
        'description': json['description'],
        'type': json['type'],
        'ledger': json['ledger'],
        'date': (new Date(json['date'])),
        'generated': json['generated'] == null ? undefined : json['generated'],
        'created': (new Date(json['created'])),
    };
}

export function GetProfileFinancialLedger200ResponseInnerToJSON(json: any): GetProfileFinancialLedger200ResponseInner {
    return GetProfileFinancialLedger200ResponseInnerToJSONTyped(json, false);
}

export function GetProfileFinancialLedger200ResponseInnerToJSONTyped(value?: GetProfileFinancialLedger200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'correlation': value['correlation'],
        'amount': value['amount'],
        'description': value['description'],
        'type': value['type'],
        'ledger': value['ledger'],
        'date': ((value['date']).toISOString().substring(0,10)),
        'generated': value['generated'],
        'created': ((value['created']).toISOString().substring(0,10)),
    };
}

