/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProfileLedgerChart200ResponseCategoriesValue
 */
export interface GetProfileLedgerChart200ResponseCategoriesValue {
    /**
     * 
     * @type {string}
     * @memberof GetProfileLedgerChart200ResponseCategoriesValue
     */
    name: string;
    /**
     * ID of the section
     * @type {string}
     * @memberof GetProfileLedgerChart200ResponseCategoriesValue
     */
    section: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetProfileLedgerChart200ResponseCategoriesValue
     */
    tags?: Array<GetProfileLedgerChart200ResponseCategoriesValueTagsEnum>;
}


/**
 * @export
 */
export const GetProfileLedgerChart200ResponseCategoriesValueTagsEnum = {
    Revenue: 'revenue',
    Expense: 'expense',
    Asset: 'asset',
    Cash: 'cash'
} as const;
export type GetProfileLedgerChart200ResponseCategoriesValueTagsEnum = typeof GetProfileLedgerChart200ResponseCategoriesValueTagsEnum[keyof typeof GetProfileLedgerChart200ResponseCategoriesValueTagsEnum];


/**
 * Check if a given object implements the GetProfileLedgerChart200ResponseCategoriesValue interface.
 */
export function instanceOfGetProfileLedgerChart200ResponseCategoriesValue(value: object): value is GetProfileLedgerChart200ResponseCategoriesValue {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('section' in value) || value['section'] === undefined) return false;
    return true;
}

export function GetProfileLedgerChart200ResponseCategoriesValueFromJSON(json: any): GetProfileLedgerChart200ResponseCategoriesValue {
    return GetProfileLedgerChart200ResponseCategoriesValueFromJSONTyped(json, false);
}

export function GetProfileLedgerChart200ResponseCategoriesValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileLedgerChart200ResponseCategoriesValue {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'section': json['section'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function GetProfileLedgerChart200ResponseCategoriesValueToJSON(json: any): GetProfileLedgerChart200ResponseCategoriesValue {
    return GetProfileLedgerChart200ResponseCategoriesValueToJSONTyped(json, false);
}

export function GetProfileLedgerChart200ResponseCategoriesValueToJSONTyped(value?: GetProfileLedgerChart200ResponseCategoriesValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'section': value['section'],
        'tags': value['tags'],
    };
}

