/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetProfileStatus200ResponseEmbedded } from './GetProfileStatus200ResponseEmbedded';
import {
    GetProfileStatus200ResponseEmbeddedFromJSON,
    GetProfileStatus200ResponseEmbeddedFromJSONTyped,
    GetProfileStatus200ResponseEmbeddedToJSON,
    GetProfileStatus200ResponseEmbeddedToJSONTyped,
} from './GetProfileStatus200ResponseEmbedded';

/**
 * 
 * @export
 * @interface GetProfileStatus200Response
 */
export interface GetProfileStatus200Response {
    /**
     * 
     * @type {string}
     * @memberof GetProfileStatus200Response
     */
    status: GetProfileStatus200ResponseStatusEnum;
    /**
     * 
     * @type {GetProfileStatus200ResponseEmbedded}
     * @memberof GetProfileStatus200Response
     */
    embedded: GetProfileStatus200ResponseEmbedded;
}


/**
 * @export
 */
export const GetProfileStatus200ResponseStatusEnum = {
    Active: 'active',
    NeedsSubscription: 'needs_subscription',
    Inactive: 'inactive',
    RequiresPayment: 'requires_payment',
    OpenPayment: 'open_payment'
} as const;
export type GetProfileStatus200ResponseStatusEnum = typeof GetProfileStatus200ResponseStatusEnum[keyof typeof GetProfileStatus200ResponseStatusEnum];


/**
 * Check if a given object implements the GetProfileStatus200Response interface.
 */
export function instanceOfGetProfileStatus200Response(value: object): value is GetProfileStatus200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('embedded' in value) || value['embedded'] === undefined) return false;
    return true;
}

export function GetProfileStatus200ResponseFromJSON(json: any): GetProfileStatus200Response {
    return GetProfileStatus200ResponseFromJSONTyped(json, false);
}

export function GetProfileStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'embedded': GetProfileStatus200ResponseEmbeddedFromJSON(json['_embedded']),
    };
}

export function GetProfileStatus200ResponseToJSON(json: any): GetProfileStatus200Response {
    return GetProfileStatus200ResponseToJSONTyped(json, false);
}

export function GetProfileStatus200ResponseToJSONTyped(value?: GetProfileStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        '_embedded': GetProfileStatus200ResponseEmbeddedToJSON(value['embedded']),
    };
}

