/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetProfileAnalyticsDebtors200ResponseConcept } from './GetProfileAnalyticsDebtors200ResponseConcept';
import {
    GetProfileAnalyticsDebtors200ResponseConceptFromJSON,
    GetProfileAnalyticsDebtors200ResponseConceptFromJSONTyped,
    GetProfileAnalyticsDebtors200ResponseConceptToJSON,
    GetProfileAnalyticsDebtors200ResponseConceptToJSONTyped,
} from './GetProfileAnalyticsDebtors200ResponseConcept';

/**
 * 
 * @export
 * @interface GetProfileAnalyticsCreditors200Response
 */
export interface GetProfileAnalyticsCreditors200Response {
    /**
     * 
     * @type {GetProfileAnalyticsDebtors200ResponseConcept}
     * @memberof GetProfileAnalyticsCreditors200Response
     */
    concept: GetProfileAnalyticsDebtors200ResponseConcept;
    /**
     * 
     * @type {GetProfileAnalyticsDebtors200ResponseConcept}
     * @memberof GetProfileAnalyticsCreditors200Response
     */
    open: GetProfileAnalyticsDebtors200ResponseConcept;
    /**
     * 
     * @type {GetProfileAnalyticsDebtors200ResponseConcept}
     * @memberof GetProfileAnalyticsCreditors200Response
     */
    overdue: GetProfileAnalyticsDebtors200ResponseConcept;
    /**
     * 
     * @type {GetProfileAnalyticsDebtors200ResponseConcept}
     * @memberof GetProfileAnalyticsCreditors200Response
     */
    late: GetProfileAnalyticsDebtors200ResponseConcept;
    /**
     * 
     * @type {GetProfileAnalyticsDebtors200ResponseConcept}
     * @memberof GetProfileAnalyticsCreditors200Response
     */
    disputed: GetProfileAnalyticsDebtors200ResponseConcept;
}

/**
 * Check if a given object implements the GetProfileAnalyticsCreditors200Response interface.
 */
export function instanceOfGetProfileAnalyticsCreditors200Response(value: object): value is GetProfileAnalyticsCreditors200Response {
    if (!('concept' in value) || value['concept'] === undefined) return false;
    if (!('open' in value) || value['open'] === undefined) return false;
    if (!('overdue' in value) || value['overdue'] === undefined) return false;
    if (!('late' in value) || value['late'] === undefined) return false;
    if (!('disputed' in value) || value['disputed'] === undefined) return false;
    return true;
}

export function GetProfileAnalyticsCreditors200ResponseFromJSON(json: any): GetProfileAnalyticsCreditors200Response {
    return GetProfileAnalyticsCreditors200ResponseFromJSONTyped(json, false);
}

export function GetProfileAnalyticsCreditors200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileAnalyticsCreditors200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'concept': GetProfileAnalyticsDebtors200ResponseConceptFromJSON(json['concept']),
        'open': GetProfileAnalyticsDebtors200ResponseConceptFromJSON(json['open']),
        'overdue': GetProfileAnalyticsDebtors200ResponseConceptFromJSON(json['overdue']),
        'late': GetProfileAnalyticsDebtors200ResponseConceptFromJSON(json['late']),
        'disputed': GetProfileAnalyticsDebtors200ResponseConceptFromJSON(json['disputed']),
    };
}

export function GetProfileAnalyticsCreditors200ResponseToJSON(json: any): GetProfileAnalyticsCreditors200Response {
    return GetProfileAnalyticsCreditors200ResponseToJSONTyped(json, false);
}

export function GetProfileAnalyticsCreditors200ResponseToJSONTyped(value?: GetProfileAnalyticsCreditors200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'concept': GetProfileAnalyticsDebtors200ResponseConceptToJSON(value['concept']),
        'open': GetProfileAnalyticsDebtors200ResponseConceptToJSON(value['open']),
        'overdue': GetProfileAnalyticsDebtors200ResponseConceptToJSON(value['overdue']),
        'late': GetProfileAnalyticsDebtors200ResponseConceptToJSON(value['late']),
        'disputed': GetProfileAnalyticsDebtors200ResponseConceptToJSON(value['disputed']),
    };
}

