/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfilePublic } from './ProfilePublic';
import {
    ProfilePublicFromJSON,
    ProfilePublicFromJSONTyped,
    ProfilePublicToJSON,
    ProfilePublicToJSONTyped,
} from './ProfilePublic';
import type { GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedLinesInner } from './GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedLinesInner';
import {
    GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedLinesInnerFromJSON,
    GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedLinesInnerFromJSONTyped,
    GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedLinesInnerToJSON,
    GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedLinesInnerToJSONTyped,
} from './GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedLinesInner';

/**
 * 
 * @export
 * @interface GetProfileStatus200ResponseEmbeddedSubscriptionEmbedded
 */
export interface GetProfileStatus200ResponseEmbeddedSubscriptionEmbedded {
    /**
     * 
     * @type {Array<GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedLinesInner>}
     * @memberof GetProfileStatus200ResponseEmbeddedSubscriptionEmbedded
     */
    lines: Array<GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedLinesInner>;
    /**
     * 
     * @type {ProfilePublic}
     * @memberof GetProfileStatus200ResponseEmbeddedSubscriptionEmbedded
     */
    profile?: ProfilePublic;
}

/**
 * Check if a given object implements the GetProfileStatus200ResponseEmbeddedSubscriptionEmbedded interface.
 */
export function instanceOfGetProfileStatus200ResponseEmbeddedSubscriptionEmbedded(value: object): value is GetProfileStatus200ResponseEmbeddedSubscriptionEmbedded {
    if (!('lines' in value) || value['lines'] === undefined) return false;
    return true;
}

export function GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedFromJSON(json: any): GetProfileStatus200ResponseEmbeddedSubscriptionEmbedded {
    return GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedFromJSONTyped(json, false);
}

export function GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileStatus200ResponseEmbeddedSubscriptionEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'lines': ((json['lines'] as Array<any>).map(GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedLinesInnerFromJSON)),
        'profile': json['profile'] == null ? undefined : ProfilePublicFromJSON(json['profile']),
    };
}

export function GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedToJSON(json: any): GetProfileStatus200ResponseEmbeddedSubscriptionEmbedded {
    return GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedToJSONTyped(json, false);
}

export function GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedToJSONTyped(value?: GetProfileStatus200ResponseEmbeddedSubscriptionEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lines': ((value['lines'] as Array<any>).map(GetProfileStatus200ResponseEmbeddedSubscriptionEmbeddedLinesInnerToJSON)),
        'profile': ProfilePublicToJSON(value['profile']),
    };
}

