/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectTime } from './ProjectTime';
import {
    ProjectTimeFromJSON,
    ProjectTimeFromJSONTyped,
    ProjectTimeToJSON,
    ProjectTimeToJSONTyped,
} from './ProjectTime';

/**
 * 
 * @export
 * @interface GetProjectsTimes200Response
 */
export interface GetProjectsTimes200Response {
    /**
     * The current page
     * @type {number}
     * @memberof GetProjectsTimes200Response
     */
    page: number;
    /**
     * The total number of pages
     * @type {number}
     * @memberof GetProjectsTimes200Response
     */
    pages: number;
    /**
     * Size of the page returned
     * @type {number}
     * @memberof GetProjectsTimes200Response
     */
    size: number;
    /**
     * The total count of the resource
     * @type {number}
     * @memberof GetProjectsTimes200Response
     */
    count: number;
    /**
     * 
     * @type {Array<ProjectTime>}
     * @memberof GetProjectsTimes200Response
     */
    data: Array<ProjectTime>;
}

/**
 * Check if a given object implements the GetProjectsTimes200Response interface.
 */
export function instanceOfGetProjectsTimes200Response(value: object): value is GetProjectsTimes200Response {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pages' in value) || value['pages'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetProjectsTimes200ResponseFromJSON(json: any): GetProjectsTimes200Response {
    return GetProjectsTimes200ResponseFromJSONTyped(json, false);
}

export function GetProjectsTimes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProjectsTimes200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pages': json['pages'],
        'size': json['size'],
        'count': json['count'],
        'data': ((json['data'] as Array<any>).map(ProjectTimeFromJSON)),
    };
}

export function GetProjectsTimes200ResponseToJSON(json: any): GetProjectsTimes200Response {
    return GetProjectsTimes200ResponseToJSONTyped(json, false);
}

export function GetProjectsTimes200ResponseToJSONTyped(value?: GetProjectsTimes200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pages': value['pages'],
        'size': value['size'],
        'count': value['count'],
        'data': ((value['data'] as Array<any>).map(ProjectTimeToJSON)),
    };
}

