/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcessDocument } from './ProcessDocument';
import {
    ProcessDocumentFromJSON,
    ProcessDocumentFromJSONTyped,
    ProcessDocumentToJSON,
    ProcessDocumentToJSONTyped,
} from './ProcessDocument';

/**
 * 
 * @export
 * @interface GetProcessDocuments200Response
 */
export interface GetProcessDocuments200Response {
    /**
     * The current page
     * @type {number}
     * @memberof GetProcessDocuments200Response
     */
    page: number;
    /**
     * The total number of pages
     * @type {number}
     * @memberof GetProcessDocuments200Response
     */
    pages: number;
    /**
     * Size of the page returned
     * @type {number}
     * @memberof GetProcessDocuments200Response
     */
    size: number;
    /**
     * The total count of the resource
     * @type {number}
     * @memberof GetProcessDocuments200Response
     */
    count: number;
    /**
     * 
     * @type {Array<ProcessDocument>}
     * @memberof GetProcessDocuments200Response
     */
    data: Array<ProcessDocument>;
}

/**
 * Check if a given object implements the GetProcessDocuments200Response interface.
 */
export function instanceOfGetProcessDocuments200Response(value: object): value is GetProcessDocuments200Response {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pages' in value) || value['pages'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetProcessDocuments200ResponseFromJSON(json: any): GetProcessDocuments200Response {
    return GetProcessDocuments200ResponseFromJSONTyped(json, false);
}

export function GetProcessDocuments200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProcessDocuments200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pages': json['pages'],
        'size': json['size'],
        'count': json['count'],
        'data': ((json['data'] as Array<any>).map(ProcessDocumentFromJSON)),
    };
}

export function GetProcessDocuments200ResponseToJSON(json: any): GetProcessDocuments200Response {
    return GetProcessDocuments200ResponseToJSONTyped(json, false);
}

export function GetProcessDocuments200ResponseToJSONTyped(value?: GetProcessDocuments200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pages': value['pages'],
        'size': value['size'],
        'count': value['count'],
        'data': ((value['data'] as Array<any>).map(ProcessDocumentToJSON)),
    };
}

