/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProfileAnalyticsRevenue200ResponseValue
 */
export interface GetProfileAnalyticsRevenue200ResponseValue {
    /**
     * 
     * @type {number}
     * @memberof GetProfileAnalyticsRevenue200ResponseValue
     */
    amount: number;
}

/**
 * Check if a given object implements the GetProfileAnalyticsRevenue200ResponseValue interface.
 */
export function instanceOfGetProfileAnalyticsRevenue200ResponseValue(value: object): value is GetProfileAnalyticsRevenue200ResponseValue {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function GetProfileAnalyticsRevenue200ResponseValueFromJSON(json: any): GetProfileAnalyticsRevenue200ResponseValue {
    return GetProfileAnalyticsRevenue200ResponseValueFromJSONTyped(json, false);
}

export function GetProfileAnalyticsRevenue200ResponseValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileAnalyticsRevenue200ResponseValue {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
    };
}

export function GetProfileAnalyticsRevenue200ResponseValueToJSON(json: any): GetProfileAnalyticsRevenue200ResponseValue {
    return GetProfileAnalyticsRevenue200ResponseValueToJSONTyped(json, false);
}

export function GetProfileAnalyticsRevenue200ResponseValueToJSONTyped(value?: GetProfileAnalyticsRevenue200ResponseValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
    };
}

