/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRelationsAutocomplete200ResponseDataInnerEu
 */
export interface GetRelationsAutocomplete200ResponseDataInnerEu {
    /**
     * European Union VAT number
     * @type {string}
     * @memberof GetRelationsAutocomplete200ResponseDataInnerEu
     */
    vatNumber: string;
}

/**
 * Check if a given object implements the GetRelationsAutocomplete200ResponseDataInnerEu interface.
 */
export function instanceOfGetRelationsAutocomplete200ResponseDataInnerEu(value: object): value is GetRelationsAutocomplete200ResponseDataInnerEu {
    if (!('vatNumber' in value) || value['vatNumber'] === undefined) return false;
    return true;
}

export function GetRelationsAutocomplete200ResponseDataInnerEuFromJSON(json: any): GetRelationsAutocomplete200ResponseDataInnerEu {
    return GetRelationsAutocomplete200ResponseDataInnerEuFromJSONTyped(json, false);
}

export function GetRelationsAutocomplete200ResponseDataInnerEuFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRelationsAutocomplete200ResponseDataInnerEu {
    if (json == null) {
        return json;
    }
    return {
        
        'vatNumber': json['vat-number'],
    };
}

export function GetRelationsAutocomplete200ResponseDataInnerEuToJSON(json: any): GetRelationsAutocomplete200ResponseDataInnerEu {
    return GetRelationsAutocomplete200ResponseDataInnerEuToJSONTyped(json, false);
}

export function GetRelationsAutocomplete200ResponseDataInnerEuToJSONTyped(value?: GetRelationsAutocomplete200ResponseDataInnerEu | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vat-number': value['vatNumber'],
    };
}

