/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSalesInvoicesDateParameter
 */
export interface GetSalesInvoicesDateParameter {
    /**
     * 
     * @type {Date}
     * @memberof GetSalesInvoicesDateParameter
     */
    min?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetSalesInvoicesDateParameter
     */
    max?: Date;
}

/**
 * Check if a given object implements the GetSalesInvoicesDateParameter interface.
 */
export function instanceOfGetSalesInvoicesDateParameter(value: object): value is GetSalesInvoicesDateParameter {
    return true;
}

export function GetSalesInvoicesDateParameterFromJSON(json: any): GetSalesInvoicesDateParameter {
    return GetSalesInvoicesDateParameterFromJSONTyped(json, false);
}

export function GetSalesInvoicesDateParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSalesInvoicesDateParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'min': json['min'] == null ? undefined : (new Date(json['min'])),
        'max': json['max'] == null ? undefined : (new Date(json['max'])),
    };
}

export function GetSalesInvoicesDateParameterToJSON(json: any): GetSalesInvoicesDateParameter {
    return GetSalesInvoicesDateParameterToJSONTyped(json, false);
}

export function GetSalesInvoicesDateParameterToJSONTyped(value?: GetSalesInvoicesDateParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min': value['min'] == null ? undefined : ((value['min']).toISOString().substring(0,10)),
        'max': value['max'] == null ? undefined : ((value['max']).toISOString().substring(0,10)),
    };
}

