/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SalesInvoice } from './SalesInvoice';
import {
    SalesInvoiceFromJSON,
    SalesInvoiceFromJSONTyped,
    SalesInvoiceToJSON,
    SalesInvoiceToJSONTyped,
} from './SalesInvoice';

/**
 * 
 * @export
 * @interface GetSalesInvoices200Response
 */
export interface GetSalesInvoices200Response {
    /**
     * The current page
     * @type {number}
     * @memberof GetSalesInvoices200Response
     */
    page?: number;
    /**
     * The total number of pages
     * @type {number}
     * @memberof GetSalesInvoices200Response
     */
    pages?: number;
    /**
     * Size of the page returned
     * @type {number}
     * @memberof GetSalesInvoices200Response
     */
    size?: number;
    /**
     * The total count of the resource
     * @type {number}
     * @memberof GetSalesInvoices200Response
     */
    count?: number;
    /**
     * 
     * @type {Array<SalesInvoice>}
     * @memberof GetSalesInvoices200Response
     */
    data?: Array<SalesInvoice>;
}

/**
 * Check if a given object implements the GetSalesInvoices200Response interface.
 */
export function instanceOfGetSalesInvoices200Response(value: object): value is GetSalesInvoices200Response {
    return true;
}

export function GetSalesInvoices200ResponseFromJSON(json: any): GetSalesInvoices200Response {
    return GetSalesInvoices200ResponseFromJSONTyped(json, false);
}

export function GetSalesInvoices200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSalesInvoices200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'pages': json['pages'] == null ? undefined : json['pages'],
        'size': json['size'] == null ? undefined : json['size'],
        'count': json['count'] == null ? undefined : json['count'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SalesInvoiceFromJSON)),
    };
}

export function GetSalesInvoices200ResponseToJSON(json: any): GetSalesInvoices200Response {
    return GetSalesInvoices200ResponseToJSONTyped(json, false);
}

export function GetSalesInvoices200ResponseToJSONTyped(value?: GetSalesInvoices200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pages': value['pages'],
        'size': value['size'],
        'count': value['count'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SalesInvoiceToJSON)),
    };
}

