/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportMonetaryAccountBookedCSVRequest
 */
export interface ImportMonetaryAccountBookedCSVRequest {
    /**
     * 
     * @type {any}
     * @memberof ImportMonetaryAccountBookedCSVRequest
     */
    data?: any | null;
}

/**
 * Check if a given object implements the ImportMonetaryAccountBookedCSVRequest interface.
 */
export function instanceOfImportMonetaryAccountBookedCSVRequest(value: object): value is ImportMonetaryAccountBookedCSVRequest {
    return true;
}

export function ImportMonetaryAccountBookedCSVRequestFromJSON(json: any): ImportMonetaryAccountBookedCSVRequest {
    return ImportMonetaryAccountBookedCSVRequestFromJSONTyped(json, false);
}

export function ImportMonetaryAccountBookedCSVRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportMonetaryAccountBookedCSVRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ImportMonetaryAccountBookedCSVRequestToJSON(json: any): ImportMonetaryAccountBookedCSVRequest {
    return ImportMonetaryAccountBookedCSVRequestToJSONTyped(json, false);
}

export function ImportMonetaryAccountBookedCSVRequestToJSONTyped(value?: ImportMonetaryAccountBookedCSVRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

