/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LinksSelf } from './LinksSelf';
import {
    LinksSelfFromJSON,
    LinksSelfFromJSONTyped,
    LinksSelfToJSON,
    LinksSelfToJSONTyped,
} from './LinksSelf';
import type { LinksValue } from './LinksValue';
import {
    LinksValueFromJSON,
    LinksValueFromJSONTyped,
    LinksValueToJSON,
    LinksValueToJSONTyped,
} from './LinksValue';

/**
 * An account that represents a user
 * @export
 * @interface Links
 */
export interface Links {
    [key: string]: LinksValue | any;
    /**
     * 
     * @type {LinksSelf}
     * @memberof Links
     */
    self: LinksSelf;
}

/**
 * Check if a given object implements the Links interface.
 */
export function instanceOfLinks(value: object): value is Links {
    if (!('self' in value) || value['self'] === undefined) return false;
    return true;
}

export function LinksFromJSON(json: any): Links {
    return LinksFromJSONTyped(json, false);
}

export function LinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): Links {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'self': LinksSelfFromJSON(json['self']),
    };
}

export function LinksToJSON(json: any): Links {
    return LinksToJSONTyped(json, false);
}

export function LinksToJSONTyped(value?: Links | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'self': LinksSelfToJSON(value['self']),
    };
}

