/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
    LinksToJSONTyped,
} from './Links';
import type { MemorialEntryEmbedded } from './MemorialEntryEmbedded';
import {
    MemorialEntryEmbeddedFromJSON,
    MemorialEntryEmbeddedFromJSONTyped,
    MemorialEntryEmbeddedToJSON,
    MemorialEntryEmbeddedToJSONTyped,
} from './MemorialEntryEmbedded';

/**
 * 
 * @export
 * @interface MemorialEntry
 */
export interface MemorialEntry {
    /**
     * 
     * @type {string}
     * @memberof MemorialEntry
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof MemorialEntry
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof MemorialEntry
     */
    readonly date: Date;
    /**
     * 
     * @type {string}
     * @memberof MemorialEntry
     */
    createdBy?: string;
    /**
     * Free form key/ value pair
     * @type {{ [key: string]: any; }}
     * @memberof MemorialEntry
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {MemorialEntryEmbedded}
     * @memberof MemorialEntry
     */
    embedded: MemorialEntryEmbedded;
    /**
     * 
     * @type {Links}
     * @memberof MemorialEntry
     */
    links?: Links;
    /**
     * 
     * @type {Date}
     * @memberof MemorialEntry
     */
    readonly updated: Date;
    /**
     * 
     * @type {Date}
     * @memberof MemorialEntry
     */
    readonly created: Date;
}

/**
 * Check if a given object implements the MemorialEntry interface.
 */
export function instanceOfMemorialEntry(value: object): value is MemorialEntry {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('embedded' in value) || value['embedded'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function MemorialEntryFromJSON(json: any): MemorialEntry {
    return MemorialEntryFromJSONTyped(json, false);
}

export function MemorialEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemorialEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'date': (new Date(json['date'])),
        'createdBy': json['created-by'] == null ? undefined : json['created-by'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'embedded': MemorialEntryEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : LinksFromJSON(json['_links']),
        'updated': (new Date(json['updated'])),
        'created': (new Date(json['created'])),
    };
}

export function MemorialEntryToJSON(json: any): MemorialEntry {
    return MemorialEntryToJSONTyped(json, false);
}

export function MemorialEntryToJSONTyped(value?: Omit<MemorialEntry, 'id'|'date'|'updated'|'created'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'created-by': value['createdBy'],
        'metadata': value['metadata'],
        '_embedded': MemorialEntryEmbeddedToJSON(value['embedded']),
        '_links': LinksToJSON(value['links']),
    };
}

