/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpateMonetaryAccountAutoProcessRequestRulesInner } from './UpateMonetaryAccountAutoProcessRequestRulesInner';
import {
    UpateMonetaryAccountAutoProcessRequestRulesInnerFromJSON,
    UpateMonetaryAccountAutoProcessRequestRulesInnerFromJSONTyped,
    UpateMonetaryAccountAutoProcessRequestRulesInnerToJSON,
    UpateMonetaryAccountAutoProcessRequestRulesInnerToJSONTyped,
} from './UpateMonetaryAccountAutoProcessRequestRulesInner';
import type { UpateMonetaryAccountAutoProcessRequestProcess } from './UpateMonetaryAccountAutoProcessRequestProcess';
import {
    UpateMonetaryAccountAutoProcessRequestProcessFromJSON,
    UpateMonetaryAccountAutoProcessRequestProcessFromJSONTyped,
    UpateMonetaryAccountAutoProcessRequestProcessToJSON,
    UpateMonetaryAccountAutoProcessRequestProcessToJSONTyped,
} from './UpateMonetaryAccountAutoProcessRequestProcess';

/**
 * 
 * @export
 * @interface MonetaryAccountAutoProcess
 */
export interface MonetaryAccountAutoProcess {
    /**
     * 
     * @type {string}
     * @memberof MonetaryAccountAutoProcess
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof MonetaryAccountAutoProcess
     */
    name: string;
    /**
     * 
     * @type {Array<UpateMonetaryAccountAutoProcessRequestRulesInner>}
     * @memberof MonetaryAccountAutoProcess
     */
    rules: Array<UpateMonetaryAccountAutoProcessRequestRulesInner>;
    /**
     * 
     * @type {UpateMonetaryAccountAutoProcessRequestProcess}
     * @memberof MonetaryAccountAutoProcess
     */
    process: UpateMonetaryAccountAutoProcessRequestProcess;
    /**
     * 
     * @type {Date}
     * @memberof MonetaryAccountAutoProcess
     */
    readonly updated: Date;
    /**
     * 
     * @type {Date}
     * @memberof MonetaryAccountAutoProcess
     */
    readonly created: Date;
}

/**
 * Check if a given object implements the MonetaryAccountAutoProcess interface.
 */
export function instanceOfMonetaryAccountAutoProcess(value: object): value is MonetaryAccountAutoProcess {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('rules' in value) || value['rules'] === undefined) return false;
    if (!('process' in value) || value['process'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function MonetaryAccountAutoProcessFromJSON(json: any): MonetaryAccountAutoProcess {
    return MonetaryAccountAutoProcessFromJSONTyped(json, false);
}

export function MonetaryAccountAutoProcessFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonetaryAccountAutoProcess {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'rules': ((json['rules'] as Array<any>).map(UpateMonetaryAccountAutoProcessRequestRulesInnerFromJSON)),
        'process': UpateMonetaryAccountAutoProcessRequestProcessFromJSON(json['process']),
        'updated': (new Date(json['updated'])),
        'created': (new Date(json['created'])),
    };
}

export function MonetaryAccountAutoProcessToJSON(json: any): MonetaryAccountAutoProcess {
    return MonetaryAccountAutoProcessToJSONTyped(json, false);
}

export function MonetaryAccountAutoProcessToJSONTyped(value?: Omit<MonetaryAccountAutoProcess, 'id'|'updated'|'created'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'rules': ((value['rules'] as Array<any>).map(UpateMonetaryAccountAutoProcessRequestRulesInnerToJSON)),
        'process': UpateMonetaryAccountAutoProcessRequestProcessToJSON(value['process']),
    };
}

