/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
    LinksToJSONTyped,
} from './Links';
import type { PurchaseInvoiceLineEmbedded } from './PurchaseInvoiceLineEmbedded';
import {
    PurchaseInvoiceLineEmbeddedFromJSON,
    PurchaseInvoiceLineEmbeddedFromJSONTyped,
    PurchaseInvoiceLineEmbeddedToJSON,
    PurchaseInvoiceLineEmbeddedToJSONTyped,
} from './PurchaseInvoiceLineEmbedded';

/**
 * 
 * @export
 * @interface PackingSlibLine
 */
export interface PackingSlibLine {
    /**
     * 
     * @type {string}
     * @memberof PackingSlibLine
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof PackingSlibLine
     */
    name: string;
    /**
     * ID of the asset attached
     * @type {string}
     * @memberof PackingSlibLine
     */
    asset?: string;
    /**
     * 
     * @type {string}
     * @memberof PackingSlibLine
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PackingSlibLine
     */
    product?: string;
    /**
     * ID of the project to use to apply the revenue to
     * @type {string}
     * @memberof PackingSlibLine
     */
    project?: string;
    /**
     * 
     * @type {number}
     * @memberof PackingSlibLine
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof PackingSlibLine
     */
    discount?: number;
    /**
     * 
     * @type {number}
     * @memberof PackingSlibLine
     */
    quantity: number;
    /**
     * Free form key/ value pair
     * @type {{ [key: string]: any; }}
     * @memberof PackingSlibLine
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {Links}
     * @memberof PackingSlibLine
     */
    links: Links;
    /**
     * 
     * @type {PurchaseInvoiceLineEmbedded}
     * @memberof PackingSlibLine
     */
    embedded: PurchaseInvoiceLineEmbedded;
    /**
     * 
     * @type {Date}
     * @memberof PackingSlibLine
     */
    readonly updated: Date;
    /**
     * 
     * @type {Date}
     * @memberof PackingSlibLine
     */
    readonly created: Date;
}

/**
 * Check if a given object implements the PackingSlibLine interface.
 */
export function instanceOfPackingSlibLine(value: object): value is PackingSlibLine {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    if (!('embedded' in value) || value['embedded'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function PackingSlibLineFromJSON(json: any): PackingSlibLine {
    return PackingSlibLineFromJSONTyped(json, false);
}

export function PackingSlibLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackingSlibLine {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'asset': json['asset'] == null ? undefined : json['asset'],
        'description': json['description'] == null ? undefined : json['description'],
        'product': json['product'] == null ? undefined : json['product'],
        'project': json['project'] == null ? undefined : json['project'],
        'price': json['price'],
        'discount': json['discount'] == null ? undefined : json['discount'],
        'quantity': json['quantity'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'links': LinksFromJSON(json['_links']),
        'embedded': PurchaseInvoiceLineEmbeddedFromJSON(json['_embedded']),
        'updated': (new Date(json['updated'])),
        'created': (new Date(json['created'])),
    };
}

export function PackingSlibLineToJSON(json: any): PackingSlibLine {
    return PackingSlibLineToJSONTyped(json, false);
}

export function PackingSlibLineToJSONTyped(value?: Omit<PackingSlibLine, 'id'|'updated'|'created'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'asset': value['asset'],
        'description': value['description'],
        'product': value['product'],
        'project': value['project'],
        'price': value['price'],
        'discount': value['discount'],
        'quantity': value['quantity'],
        'metadata': value['metadata'],
        '_links': LinksToJSON(value['links']),
        '_embedded': PurchaseInvoiceLineEmbeddedToJSON(value['embedded']),
    };
}

