/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
    ProfileToJSONTyped,
} from './Profile';

/**
 * 
 * @export
 * @interface ProcessDocumentEmbedded
 */
export interface ProcessDocumentEmbedded {
    /**
     * 
     * @type {Profile}
     * @memberof ProcessDocumentEmbedded
     */
    profile: Profile;
}

/**
 * Check if a given object implements the ProcessDocumentEmbedded interface.
 */
export function instanceOfProcessDocumentEmbedded(value: object): value is ProcessDocumentEmbedded {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    return true;
}

export function ProcessDocumentEmbeddedFromJSON(json: any): ProcessDocumentEmbedded {
    return ProcessDocumentEmbeddedFromJSONTyped(json, false);
}

export function ProcessDocumentEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessDocumentEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': ProfileFromJSON(json['profile']),
    };
}

export function ProcessDocumentEmbeddedToJSON(json: any): ProcessDocumentEmbedded {
    return ProcessDocumentEmbeddedToJSONTyped(json, false);
}

export function ProcessDocumentEmbeddedToJSONTyped(value?: ProcessDocumentEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile': ProfileToJSON(value['profile']),
    };
}

