/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessMonetaryAccountPaymentReminderRequest
 */
export interface ProcessMonetaryAccountPaymentReminderRequest {
    /**
     * 
     * @type {string}
     * @memberof ProcessMonetaryAccountPaymentReminderRequest
     */
    reminder: string;
}

/**
 * Check if a given object implements the ProcessMonetaryAccountPaymentReminderRequest interface.
 */
export function instanceOfProcessMonetaryAccountPaymentReminderRequest(value: object): value is ProcessMonetaryAccountPaymentReminderRequest {
    if (!('reminder' in value) || value['reminder'] === undefined) return false;
    return true;
}

export function ProcessMonetaryAccountPaymentReminderRequestFromJSON(json: any): ProcessMonetaryAccountPaymentReminderRequest {
    return ProcessMonetaryAccountPaymentReminderRequestFromJSONTyped(json, false);
}

export function ProcessMonetaryAccountPaymentReminderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessMonetaryAccountPaymentReminderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reminder': json['reminder'],
    };
}

export function ProcessMonetaryAccountPaymentReminderRequestToJSON(json: any): ProcessMonetaryAccountPaymentReminderRequest {
    return ProcessMonetaryAccountPaymentReminderRequestToJSONTyped(json, false);
}

export function ProcessMonetaryAccountPaymentReminderRequestToJSONTyped(value?: ProcessMonetaryAccountPaymentReminderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reminder': value['reminder'],
    };
}

