/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProcessMonetaryAccountPaymentMemorialRequestItemsInnerProcess } from './ProcessMonetaryAccountPaymentMemorialRequestItemsInnerProcess';
import {
    ProcessMonetaryAccountPaymentMemorialRequestItemsInnerProcessFromJSON,
    ProcessMonetaryAccountPaymentMemorialRequestItemsInnerProcessFromJSONTyped,
    ProcessMonetaryAccountPaymentMemorialRequestItemsInnerProcessToJSON,
    ProcessMonetaryAccountPaymentMemorialRequestItemsInnerProcessToJSONTyped,
} from './ProcessMonetaryAccountPaymentMemorialRequestItemsInnerProcess';

/**
 * 
 * @export
 * @interface ProcessMonetaryAccountPaymentMemorialRequestItemsInner
 */
export interface ProcessMonetaryAccountPaymentMemorialRequestItemsInner {
    /**
     * 
     * @type {string}
     * @memberof ProcessMonetaryAccountPaymentMemorialRequestItemsInner
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ProcessMonetaryAccountPaymentMemorialRequestItemsInner
     */
    amount: number;
    /**
     * 
     * @type {ProcessMonetaryAccountPaymentMemorialRequestItemsInnerProcess}
     * @memberof ProcessMonetaryAccountPaymentMemorialRequestItemsInner
     */
    process: ProcessMonetaryAccountPaymentMemorialRequestItemsInnerProcess;
}

/**
 * Check if a given object implements the ProcessMonetaryAccountPaymentMemorialRequestItemsInner interface.
 */
export function instanceOfProcessMonetaryAccountPaymentMemorialRequestItemsInner(value: object): value is ProcessMonetaryAccountPaymentMemorialRequestItemsInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('process' in value) || value['process'] === undefined) return false;
    return true;
}

export function ProcessMonetaryAccountPaymentMemorialRequestItemsInnerFromJSON(json: any): ProcessMonetaryAccountPaymentMemorialRequestItemsInner {
    return ProcessMonetaryAccountPaymentMemorialRequestItemsInnerFromJSONTyped(json, false);
}

export function ProcessMonetaryAccountPaymentMemorialRequestItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessMonetaryAccountPaymentMemorialRequestItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'amount': json['amount'],
        'process': ProcessMonetaryAccountPaymentMemorialRequestItemsInnerProcessFromJSON(json['process']),
    };
}

export function ProcessMonetaryAccountPaymentMemorialRequestItemsInnerToJSON(json: any): ProcessMonetaryAccountPaymentMemorialRequestItemsInner {
    return ProcessMonetaryAccountPaymentMemorialRequestItemsInnerToJSONTyped(json, false);
}

export function ProcessMonetaryAccountPaymentMemorialRequestItemsInnerToJSONTyped(value?: ProcessMonetaryAccountPaymentMemorialRequestItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'amount': value['amount'],
        'process': ProcessMonetaryAccountPaymentMemorialRequestItemsInnerProcessToJSON(value['process']),
    };
}

