/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessMonetaryAccountPaymentLedgerRequest
 */
export interface ProcessMonetaryAccountPaymentLedgerRequest {
    /**
     * 
     * @type {string}
     * @memberof ProcessMonetaryAccountPaymentLedgerRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessMonetaryAccountPaymentLedgerRequest
     */
    ledger: string;
    /**
     * Optional project ID to process the payment to
     * @type {string}
     * @memberof ProcessMonetaryAccountPaymentLedgerRequest
     */
    project?: string;
}

/**
 * Check if a given object implements the ProcessMonetaryAccountPaymentLedgerRequest interface.
 */
export function instanceOfProcessMonetaryAccountPaymentLedgerRequest(value: object): value is ProcessMonetaryAccountPaymentLedgerRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ledger' in value) || value['ledger'] === undefined) return false;
    return true;
}

export function ProcessMonetaryAccountPaymentLedgerRequestFromJSON(json: any): ProcessMonetaryAccountPaymentLedgerRequest {
    return ProcessMonetaryAccountPaymentLedgerRequestFromJSONTyped(json, false);
}

export function ProcessMonetaryAccountPaymentLedgerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessMonetaryAccountPaymentLedgerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ledger': json['ledger'],
        'project': json['project'] == null ? undefined : json['project'],
    };
}

export function ProcessMonetaryAccountPaymentLedgerRequestToJSON(json: any): ProcessMonetaryAccountPaymentLedgerRequest {
    return ProcessMonetaryAccountPaymentLedgerRequestToJSONTyped(json, false);
}

export function ProcessMonetaryAccountPaymentLedgerRequestToJSONTyped(value?: ProcessMonetaryAccountPaymentLedgerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'ledger': value['ledger'],
        'project': value['project'],
    };
}

