/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PullMonetaryAccount200Response
 */
export interface PullMonetaryAccount200Response {
    /**
     * 
     * @type {string}
     * @memberof PullMonetaryAccount200Response
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof PullMonetaryAccount200Response
     */
    token?: string;
}

/**
 * Check if a given object implements the PullMonetaryAccount200Response interface.
 */
export function instanceOfPullMonetaryAccount200Response(value: object): value is PullMonetaryAccount200Response {
    return true;
}

export function PullMonetaryAccount200ResponseFromJSON(json: any): PullMonetaryAccount200Response {
    return PullMonetaryAccount200ResponseFromJSONTyped(json, false);
}

export function PullMonetaryAccount200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PullMonetaryAccount200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function PullMonetaryAccount200ResponseToJSON(json: any): PullMonetaryAccount200Response {
    return PullMonetaryAccount200ResponseToJSONTyped(json, false);
}

export function PullMonetaryAccount200ResponseToJSONTyped(value?: PullMonetaryAccount200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'token': value['token'],
    };
}

