/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateRelationRequestBank } from './CreateRelationRequestBank';
import {
    CreateRelationRequestBankFromJSON,
    CreateRelationRequestBankFromJSONTyped,
    CreateRelationRequestBankToJSON,
    CreateRelationRequestBankToJSONTyped,
} from './CreateRelationRequestBank';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { Language } from './Language';
import {
    LanguageFromJSON,
    LanguageFromJSONTyped,
    LanguageToJSON,
    LanguageToJSONTyped,
} from './Language';
import type { Links } from './Links';
import {
    LinksFromJSON,
    LinksFromJSONTyped,
    LinksToJSON,
    LinksToJSONTyped,
} from './Links';
import type { CreateRelationRequestEu } from './CreateRelationRequestEu';
import {
    CreateRelationRequestEuFromJSON,
    CreateRelationRequestEuFromJSONTyped,
    CreateRelationRequestEuToJSON,
    CreateRelationRequestEuToJSONTyped,
} from './CreateRelationRequestEu';

/**
 * 
 * @export
 * @interface Relation
 */
export interface Relation {
    /**
     * 
     * @type {string}
     * @memberof Relation
     */
    readonly id: string;
    /**
     * Display name based on the legal name, first, middle, and last name
     * @type {string}
     * @memberof Relation
     */
    readonly name?: string;
    /**
     * Tags for the relation
     * @type {Array<string>}
     * @memberof Relation
     */
    tags: Array<RelationTagsEnum>;
    /**
     * Registered number of the company
     * @type {string}
     * @memberof Relation
     */
    registeredNumber?: string;
    /**
     * 
     * @type {Language}
     * @memberof Relation
     */
    language?: Language;
    /**
     * 
     * @type {Array<string>}
     * @memberof Relation
     */
    emails?: Array<string>;
    /**
     * ISO 3166-1 alpha-2 country code
     * @type {string}
     * @memberof Relation
     */
    registrationCountry?: string;
    /**
     * 
     * @type {CreateRelationRequestBank}
     * @memberof Relation
     */
    bank?: CreateRelationRequestBank;
    /**
     * 
     * @type {CreateRelationRequestEu}
     * @memberof Relation
     */
    eu?: CreateRelationRequestEu;
    /**
     * 
     * @type {string}
     * @memberof Relation
     */
    legalName: string;
    /**
     * 
     * @type {string}
     * @memberof Relation
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof Relation
     */
    middleName: string;
    /**
     * 
     * @type {string}
     * @memberof Relation
     */
    lastName: string;
    /**
     * 
     * @type {Address}
     * @memberof Relation
     */
    address: Address;
    /**
     * Free form key/ value pair
     * @type {{ [key: string]: any; }}
     * @memberof Relation
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {Links}
     * @memberof Relation
     */
    links?: Links;
    /**
     * 
     * @type {Date}
     * @memberof Relation
     */
    readonly updated: Date;
    /**
     * 
     * @type {Date}
     * @memberof Relation
     */
    readonly created: Date;
}


/**
 * @export
 */
export const RelationTagsEnum = {
    Supplier: 'supplier',
    Customer: 'customer',
    Debtor: 'debtor',
    Creditor: 'creditor',
    Current: 'current',
    Active: 'active',
    Inactive: 'inactive',
    Finbaze: 'finbaze',
    TaxAuthority: 'tax-authority'
} as const;
export type RelationTagsEnum = typeof RelationTagsEnum[keyof typeof RelationTagsEnum];


/**
 * Check if a given object implements the Relation interface.
 */
export function instanceOfRelation(value: object): value is Relation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('legalName' in value) || value['legalName'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('middleName' in value) || value['middleName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function RelationFromJSON(json: any): Relation {
    return RelationFromJSONTyped(json, false);
}

export function RelationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Relation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'tags': json['tags'],
        'registeredNumber': json['registered_number'] == null ? undefined : json['registered_number'],
        'language': json['language'] == null ? undefined : LanguageFromJSON(json['language']),
        'emails': json['emails'] == null ? undefined : json['emails'],
        'registrationCountry': json['registration_country'] == null ? undefined : json['registration_country'],
        'bank': json['bank'] == null ? undefined : CreateRelationRequestBankFromJSON(json['bank']),
        'eu': json['eu'] == null ? undefined : CreateRelationRequestEuFromJSON(json['eu']),
        'legalName': json['legal_name'],
        'firstName': json['first_name'],
        'middleName': json['middle_name'],
        'lastName': json['last_name'],
        'address': AddressFromJSON(json['address']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'links': json['_links'] == null ? undefined : LinksFromJSON(json['_links']),
        'updated': (new Date(json['updated'])),
        'created': (new Date(json['created'])),
    };
}

export function RelationToJSON(json: any): Relation {
    return RelationToJSONTyped(json, false);
}

export function RelationToJSONTyped(value?: Omit<Relation, 'id'|'name'|'updated'|'created'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': value['tags'],
        'registered_number': value['registeredNumber'],
        'language': LanguageToJSON(value['language']),
        'emails': value['emails'],
        'registration_country': value['registrationCountry'],
        'bank': CreateRelationRequestBankToJSON(value['bank']),
        'eu': CreateRelationRequestEuToJSON(value['eu']),
        'legal_name': value['legalName'],
        'first_name': value['firstName'],
        'middle_name': value['middleName'],
        'last_name': value['lastName'],
        'address': AddressToJSON(value['address']),
        'metadata': value['metadata'],
        '_links': LinksToJSON(value['links']),
    };
}

