/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscribeProfilePlanRequestOpenbanking } from './SubscribeProfilePlanRequestOpenbanking';
import {
    SubscribeProfilePlanRequestOpenbankingFromJSON,
    SubscribeProfilePlanRequestOpenbankingFromJSONTyped,
    SubscribeProfilePlanRequestOpenbankingToJSON,
    SubscribeProfilePlanRequestOpenbankingToJSONTyped,
} from './SubscribeProfilePlanRequestOpenbanking';
import type { SubscriptionFrequency } from './SubscriptionFrequency';
import {
    SubscriptionFrequencyFromJSON,
    SubscriptionFrequencyFromJSONTyped,
    SubscriptionFrequencyToJSON,
    SubscriptionFrequencyToJSONTyped,
} from './SubscriptionFrequency';

/**
 * 
 * @export
 * @interface SubscribeProfilePlanRequest
 */
export interface SubscribeProfilePlanRequest {
    /**
     * JWT signed token that includes specific pricing rules, and may also include an plan
     * @type {string}
     * @memberof SubscribeProfilePlanRequest
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscribeProfilePlanRequest
     */
    plan: string;
    /**
     * 
     * @type {string}
     * @memberof SubscribeProfilePlanRequest
     */
    method: SubscribeProfilePlanRequestMethodEnum;
    /**
     * 
     * @type {SubscriptionFrequency}
     * @memberof SubscribeProfilePlanRequest
     */
    frequency?: SubscriptionFrequency;
    /**
     * 
     * @type {SubscribeProfilePlanRequestOpenbanking}
     * @memberof SubscribeProfilePlanRequest
     */
    openbanking?: SubscribeProfilePlanRequestOpenbanking;
}


/**
 * @export
 */
export const SubscribeProfilePlanRequestMethodEnum = {
    Openbanking: 'openbanking',
    Invoiced: 'invoiced'
} as const;
export type SubscribeProfilePlanRequestMethodEnum = typeof SubscribeProfilePlanRequestMethodEnum[keyof typeof SubscribeProfilePlanRequestMethodEnum];


/**
 * Check if a given object implements the SubscribeProfilePlanRequest interface.
 */
export function instanceOfSubscribeProfilePlanRequest(value: object): value is SubscribeProfilePlanRequest {
    if (!('plan' in value) || value['plan'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    return true;
}

export function SubscribeProfilePlanRequestFromJSON(json: any): SubscribeProfilePlanRequest {
    return SubscribeProfilePlanRequestFromJSONTyped(json, false);
}

export function SubscribeProfilePlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscribeProfilePlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'plan': json['plan'],
        'method': json['method'],
        'frequency': json['frequency'] == null ? undefined : SubscriptionFrequencyFromJSON(json['frequency']),
        'openbanking': json['openbanking'] == null ? undefined : SubscribeProfilePlanRequestOpenbankingFromJSON(json['openbanking']),
    };
}

export function SubscribeProfilePlanRequestToJSON(json: any): SubscribeProfilePlanRequest {
    return SubscribeProfilePlanRequestToJSONTyped(json, false);
}

export function SubscribeProfilePlanRequestToJSONTyped(value?: SubscribeProfilePlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'plan': value['plan'],
        'method': value['method'],
        'frequency': SubscriptionFrequencyToJSON(value['frequency']),
        'openbanking': SubscribeProfilePlanRequestOpenbankingToJSON(value['openbanking']),
    };
}

