/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscribeProfile201ResponsePlanEmbedded } from './SubscribeProfile201ResponsePlanEmbedded';
import {
    SubscribeProfile201ResponsePlanEmbeddedFromJSON,
    SubscribeProfile201ResponsePlanEmbeddedFromJSONTyped,
    SubscribeProfile201ResponsePlanEmbeddedToJSON,
    SubscribeProfile201ResponsePlanEmbeddedToJSONTyped,
} from './SubscribeProfile201ResponsePlanEmbedded';

/**
 * 
 * @export
 * @interface SubscribeProfile201ResponsePlan
 */
export interface SubscribeProfile201ResponsePlan {
    /**
     * 
     * @type {string}
     * @memberof SubscribeProfile201ResponsePlan
     */
    readonly id: string;
    /**
     * 
     * @type {Date}
     * @memberof SubscribeProfile201ResponsePlan
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SubscribeProfile201ResponsePlan
     */
    end?: Date;
    /**
     * 
     * @type {SubscribeProfile201ResponsePlanEmbedded}
     * @memberof SubscribeProfile201ResponsePlan
     */
    embedded: SubscribeProfile201ResponsePlanEmbedded;
    /**
     * 
     * @type {Date}
     * @memberof SubscribeProfile201ResponsePlan
     */
    readonly updated: Date;
    /**
     * 
     * @type {Date}
     * @memberof SubscribeProfile201ResponsePlan
     */
    readonly created: Date;
}

/**
 * Check if a given object implements the SubscribeProfile201ResponsePlan interface.
 */
export function instanceOfSubscribeProfile201ResponsePlan(value: object): value is SubscribeProfile201ResponsePlan {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('embedded' in value) || value['embedded'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function SubscribeProfile201ResponsePlanFromJSON(json: any): SubscribeProfile201ResponsePlan {
    return SubscribeProfile201ResponsePlanFromJSONTyped(json, false);
}

export function SubscribeProfile201ResponsePlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscribeProfile201ResponsePlan {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'embedded': SubscribeProfile201ResponsePlanEmbeddedFromJSON(json['_embedded']),
        'updated': (new Date(json['updated'])),
        'created': (new Date(json['created'])),
    };
}

export function SubscribeProfile201ResponsePlanToJSON(json: any): SubscribeProfile201ResponsePlan {
    return SubscribeProfile201ResponsePlanToJSONTyped(json, false);
}

export function SubscribeProfile201ResponsePlanToJSONTyped(value?: Omit<SubscribeProfile201ResponsePlan, 'id'|'updated'|'created'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'] == null ? undefined : ((value['start']).toISOString()),
        'end': value['end'] == null ? undefined : ((value['end']).toISOString()),
        '_embedded': SubscribeProfile201ResponsePlanEmbeddedToJSON(value['embedded']),
    };
}

