/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ISO 3166-1 alpha-2 country code
 * @export
 */
export const TaxCode = {
    Nl2012High: 'NL_2012_HIGH',
    Nl2019Low: 'NL_2019_LOW',
    Nl2001High: 'NL_2001_HIGH',
    Nl2001Low: 'NL_2001_LOW',
    Nl2024Exempt: 'NL_2024_EXEMPT',
    Nl2024Null: 'NL_2024_NULL',
    Nl2024Transfer: 'NL_2024_TRANSFER',
    EuDirective2006112EcArticle40: 'EU_Directive_2006/112/EC_Article_40',
    Gb2024Standard: 'GB_2024_STANDARD',
    Gb2024Reduced: 'GB_2024_REDUCED',
    Gb2024Zero: 'GB_2024_ZERO',
    Gb2024Exempt: 'GB_2024_EXEMPT'
} as const;
export type TaxCode = typeof TaxCode[keyof typeof TaxCode];


export function instanceOfTaxCode(value: any): boolean {
    for (const key in TaxCode) {
        if (Object.prototype.hasOwnProperty.call(TaxCode, key)) {
            if (TaxCode[key as keyof typeof TaxCode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TaxCodeFromJSON(json: any): TaxCode {
    return TaxCodeFromJSONTyped(json, false);
}

export function TaxCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxCode {
    return json as TaxCode;
}

export function TaxCodeToJSON(value?: TaxCode | null): any {
    return value as any;
}

export function TaxCodeToJSONTyped(value: any, ignoreDiscriminator: boolean): TaxCode {
    return value as TaxCode;
}

