/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpateMonetaryAccountAutoProcessRequestRulesInner
 */
export interface UpateMonetaryAccountAutoProcessRequestRulesInner {
    /**
     * Regex to match with the holder name field
     * @type {string}
     * @memberof UpateMonetaryAccountAutoProcessRequestRulesInner
     */
    holderName?: string;
    /**
     * Regex to match with the iban field
     * @type {string}
     * @memberof UpateMonetaryAccountAutoProcessRequestRulesInner
     */
    iban?: string;
    /**
     * Regex to match with the reference field
     * @type {string}
     * @memberof UpateMonetaryAccountAutoProcessRequestRulesInner
     */
    reference?: string;
    /**
     * Regex to match with the description field
     * @type {string}
     * @memberof UpateMonetaryAccountAutoProcessRequestRulesInner
     */
    description?: string;
    /**
     * Amount to match lte
     * @type {number}
     * @memberof UpateMonetaryAccountAutoProcessRequestRulesInner
     */
    amountLte?: number;
    /**
     * Amount to match gte
     * @type {number}
     * @memberof UpateMonetaryAccountAutoProcessRequestRulesInner
     */
    amountGte?: number;
}

/**
 * Check if a given object implements the UpateMonetaryAccountAutoProcessRequestRulesInner interface.
 */
export function instanceOfUpateMonetaryAccountAutoProcessRequestRulesInner(value: object): value is UpateMonetaryAccountAutoProcessRequestRulesInner {
    return true;
}

export function UpateMonetaryAccountAutoProcessRequestRulesInnerFromJSON(json: any): UpateMonetaryAccountAutoProcessRequestRulesInner {
    return UpateMonetaryAccountAutoProcessRequestRulesInnerFromJSONTyped(json, false);
}

export function UpateMonetaryAccountAutoProcessRequestRulesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpateMonetaryAccountAutoProcessRequestRulesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'holderName': json['holder_name'] == null ? undefined : json['holder_name'],
        'iban': json['iban'] == null ? undefined : json['iban'],
        'reference': json['reference'] == null ? undefined : json['reference'],
        'description': json['description'] == null ? undefined : json['description'],
        'amountLte': json['amount_lte'] == null ? undefined : json['amount_lte'],
        'amountGte': json['amount_gte'] == null ? undefined : json['amount_gte'],
    };
}

export function UpateMonetaryAccountAutoProcessRequestRulesInnerToJSON(json: any): UpateMonetaryAccountAutoProcessRequestRulesInner {
    return UpateMonetaryAccountAutoProcessRequestRulesInnerToJSONTyped(json, false);
}

export function UpateMonetaryAccountAutoProcessRequestRulesInnerToJSONTyped(value?: UpateMonetaryAccountAutoProcessRequestRulesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'holder_name': value['holderName'],
        'iban': value['iban'],
        'reference': value['reference'],
        'description': value['description'],
        'amount_lte': value['amountLte'],
        'amount_gte': value['amountGte'],
    };
}

