/* tslint:disable */
/* eslint-disable */
/**
 * Finbaze profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCurrentAccountRequest
 */
export interface UpdateCurrentAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentAccountRequest
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCurrentAccountRequest
     */
    name: string;
    /**
     * ID of the relation the loan has given
     * @type {string}
     * @memberof UpdateCurrentAccountRequest
     */
    relation: string;
    /**
     * Interest percentage with an exponent of 4, this an rate of 1.2345 will be set as 12345
     * @type {number}
     * @memberof UpdateCurrentAccountRequest
     */
    interest: number;
    /**
     * ISO 3166-1 alpha-2 currency code
     * @type {string}
     * @memberof UpdateCurrentAccountRequest
     */
    currency: string;
    /**
     * Free form key/ value pair
     * @type {{ [key: string]: any; }}
     * @memberof UpdateCurrentAccountRequest
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the UpdateCurrentAccountRequest interface.
 */
export function instanceOfUpdateCurrentAccountRequest(value: object): value is UpdateCurrentAccountRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('relation' in value) || value['relation'] === undefined) return false;
    if (!('interest' in value) || value['interest'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function UpdateCurrentAccountRequestFromJSON(json: any): UpdateCurrentAccountRequest {
    return UpdateCurrentAccountRequestFromJSONTyped(json, false);
}

export function UpdateCurrentAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCurrentAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'],
        'relation': json['relation'],
        'interest': json['interest'],
        'currency': json['currency'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function UpdateCurrentAccountRequestToJSON(json: any): UpdateCurrentAccountRequest {
    return UpdateCurrentAccountRequestToJSONTyped(json, false);
}

export function UpdateCurrentAccountRequestToJSONTyped(value?: UpdateCurrentAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        'relation': value['relation'],
        'interest': value['interest'],
        'currency': value['currency'],
        'metadata': value['metadata'],
    };
}

