/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze developers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NLVATFilingDataSection1High } from './NLVATFilingDataSection1High';
import {
    NLVATFilingDataSection1HighFromJSON,
    NLVATFilingDataSection1HighFromJSONTyped,
    NLVATFilingDataSection1HighToJSON,
    NLVATFilingDataSection1HighToJSONTyped,
} from './NLVATFilingDataSection1High';

/**
 * 
 * @export
 * @interface NLVATFilingDataSection1
 */
export interface NLVATFilingDataSection1 {
    /**
     * 
     * @type {NLVATFilingDataSection1High}
     * @memberof NLVATFilingDataSection1
     */
    high?: NLVATFilingDataSection1High;
    /**
     * 
     * @type {NLVATFilingDataSection1High}
     * @memberof NLVATFilingDataSection1
     */
    low?: NLVATFilingDataSection1High;
    /**
     * 
     * @type {NLVATFilingDataSection1High}
     * @memberof NLVATFilingDataSection1
     */
    other?: NLVATFilingDataSection1High;
    /**
     * 
     * @type {NLVATFilingDataSection1High}
     * @memberof NLVATFilingDataSection1
     */
    _private?: NLVATFilingDataSection1High;
    /**
     * Value representing no turnover or taxes.
     * @type {number}
     * @memberof NLVATFilingDataSection1
     */
    none?: number;
}

/**
 * Check if a given object implements the NLVATFilingDataSection1 interface.
 */
export function instanceOfNLVATFilingDataSection1(value: object): value is NLVATFilingDataSection1 {
    return true;
}

export function NLVATFilingDataSection1FromJSON(json: any): NLVATFilingDataSection1 {
    return NLVATFilingDataSection1FromJSONTyped(json, false);
}

export function NLVATFilingDataSection1FromJSONTyped(json: any, ignoreDiscriminator: boolean): NLVATFilingDataSection1 {
    if (json == null) {
        return json;
    }
    return {
        
        'high': json['high'] == null ? undefined : NLVATFilingDataSection1HighFromJSON(json['high']),
        'low': json['low'] == null ? undefined : NLVATFilingDataSection1HighFromJSON(json['low']),
        'other': json['other'] == null ? undefined : NLVATFilingDataSection1HighFromJSON(json['other']),
        '_private': json['private'] == null ? undefined : NLVATFilingDataSection1HighFromJSON(json['private']),
        'none': json['none'] == null ? undefined : json['none'],
    };
}

export function NLVATFilingDataSection1ToJSON(json: any): NLVATFilingDataSection1 {
    return NLVATFilingDataSection1ToJSONTyped(json, false);
}

export function NLVATFilingDataSection1ToJSONTyped(value?: NLVATFilingDataSection1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'high': NLVATFilingDataSection1HighToJSON(value['high']),
        'low': NLVATFilingDataSection1HighToJSON(value['low']),
        'other': NLVATFilingDataSection1HighToJSON(value['other']),
        'private': NLVATFilingDataSection1HighToJSON(value['_private']),
        'none': value['none'],
    };
}

