/* tslint:disable */
/* eslint-disable */
/**
 * FinBaze developers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SortValue = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SortValue = typeof SortValue[keyof typeof SortValue];


export function instanceOfSortValue(value: any): boolean {
    for (const key in SortValue) {
        if (Object.prototype.hasOwnProperty.call(SortValue, key)) {
            if (SortValue[key as keyof typeof SortValue] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SortValueFromJSON(json: any): SortValue {
    return SortValueFromJSONTyped(json, false);
}

export function SortValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortValue {
    return json as SortValue;
}

export function SortValueToJSON(value?: SortValue | null): any {
    return value as any;
}

export function SortValueToJSONTyped(value: any, ignoreDiscriminator: boolean): SortValue {
    return value as SortValue;
}

