name: Build and Commit on External Repo Change
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: finbaze/openapi
          path: ./openapi
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Run install openapi
        run: npm run install:openapi

      - name: Run build
        run: npm run build

      - name: Check for changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Automated build update from external repository"
          git push https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main